distribution/src/assemble/bin.xml

This commits adds the JDBC plugin jar to the assembly so that it can be
loaded by Drill as a storage plugin.

DRILL-3916: Add JDBC plugin to assembly

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JSONFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JsonRecordWriter.java

Use system dependent line-feed to seperate records when pretty printing is turned off
Refactor ExecConstants to eliminate unneeded modifier & accessor declarations

DRILL-4089: make JSON pretty printing configurable

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/zk/ZkAbstractStore.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/zk/ZkEStore.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/zk/ZkEStoreProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/zk/ZkPStore.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/zk/ZkPStoreProvider.java

Make ZK node creation/updates logic optimistic.
Refactor ZkAbstractStore to eliminate redundant code around node creation logic.
Enhanced documentation.

DRILL-3171: handle concurrent Zookeeper node creation gracefully

---

contrib/storage-hive/core/src/main/java/org/apache/drill/exec/planner/sql/logical/ConvertHiveParquetScanToDrillParquetScan.java
contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveDrillNativeParquetScan.java
contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveMetadataProvider.java
contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveScan.java
contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveStoragePlugin.java

+ Use the stats (numRows) stored in Hive metastore whenever available to
calculate the costs for planning purpose
+ Delay the costly operation of loading of InputSplits until needed. When
InputSplits are loaded, cache them at query level to speedup subsequent
access.
@jinfengni, @amansinha100  Could you please review the patch?

DRILL-4194: Improve the performance of metadata fetch operation in HiveScan

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerType.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillConvertletTable.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillSqlWorker.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SqlConverter.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/CreateTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DefaultSqlHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DescribeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DropTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ExplainHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/RefreshMetadataHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowFileHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowTablesHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/SqlHandlerConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/AbstractStoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/Foreman.java
exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
exec/java-exec/src/test/java/org/apache/drill/exec/planner/sql/TestDrillSQLWorker.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestSqlBracketlessSyntax.java
exec/jdbc/src/test/java/org/apache/drill/jdbc/DatabaseMetaDataGetColumnsTest.java
exec/jdbc/src/test/java/org/apache/drill/jdbc/test/TestInformationSchemaColumns.java
exec/jdbc/src/test/resources/null_ordering_and_grouping_data.json

- Canonicalize Planning phases with PlannerPhase enumeration
- Canonicalize PlannerType transforms
- Remove dependency on Calcite's Frameworks.Planner since Drill need stop heavily customize interactions
- Update AbstractStoragePlugin to implement a phase-aware planning rule injection behavior.
- Avoid (or at least reduce) duplicated registerSchemas() invocations

DRILL-4465: Simplify Calcite parsing & planning integration

---

pom.xml

Excluded `netty-all` from the list of transitive dependencies pulled by `hbase-client`.

DRILL-4727: Exclude netty from HBase Client's transitive dependencies

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaDrillTable.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilter.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilterBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaRecordGenerator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaStoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaSubScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaTable.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaTableType.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchema.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/ischema/TestInfoSchemaFilterPushDown.java

1. Add support for pushing the filter on following fields into InfoSchemaRecordGenerator:
- CATALOG_NAME
- COLUMN_NAME
2. Pushdown LIKE with ESCAPE. Add test TestInfoSchemaFilterPushDown#testFilterPushdown_LikeWithEscape
3. Add a method visitCatalog() to InfoSchemaRecordGenerator to decide whether to explore the catalog or not
4. Refactor CATALOG_DESCRIPTION and CATALOG_CONNECT as constant strings in InfoSchemaConstants.java
5. Update TestInfoSchemaFilterPushDown#testPartialFilterPushDownWithProject as
we are now pushing the filter on COLUMN_NAME field
6. Cleanup:
Rename RecordGenerator -> InfoSchemaRecordGenerator
Add comments in RecordGenerator
Rename SelectedTable -> InfoSchemaTableType
@parthchandra Can you please review this change?

DRILL-4725: Improvements to InfoSchema RecordGenerator needed for DRILL-4714

---

contrib/storage-hive/core/pom.xml

Exclude 'hadoop-mapreduce-client-core' and 'hadoop-auth' as transitive dependencies from 'hbase-server'

DRILL-4894: Fix unit test failure in 'storage-hive/core' module

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/LateralContract.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/LateralJoinBatchCreator.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/MockRecordBatch.java

@ilooner can you please check these. Looks like the latest commit(s) went in with some broken license headers.

DRILL-6323: Fix license headers

---

.travis.yml

The fix was to change the log level maven when downloading artifacts.

DRILL-6437: Removed excess maven logging when downloading dependencies. This fixed Travis failures due to log overflow.

---

exec/java-exec/src/main/resources/rest/profile/list.ftl

When running a query in Drill, the `/profiles` page will show the search (and pagination) capabilities only for the top most visible table (i.e. Running Queries ).
The _Completed Queries_ table will show the search feature only when there are no _Running Queries_. This is because the backend uses a generalized freemarker macro to define the seach capabilities for the tables being rendered. With running queries, both, _Running_ and _Completed_ queries tables have the same element ID, resulting in the search capability only being applied to the first table.
This modifies the Freemarker macro to take an additional argument for distinguishing between _Running_ and _Completed_ _Queries_ tables.

DRILL-6443: Enable Search for both running AND completed queries

---

_docs/architecture/010-architecture-introduction.md

Minor copy editing change. Apache ZooKeeper uses camel case (https://zookeeper.apache.org/).

updated ZooKeeper to CamelCase

---

_docs/odbc-jdbc-interfaces/015-using-jdbc-driver.md

Fix the bug:correct the drill directory in zookeeper to dirll from Drill,because the value is case Sensitive.

fix the default drill directory in zookeeper

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl

Having the capability to only print the visualized query plan means the user can specify the zoom level (in the printer settings) when printing large complex plans that might span multiple pages.

DRILL-6432: Show Button to print visualized query plan

---

exec/java-exec/src/main/resources/rest/index.ftl

The memory reported as a percentage is incorrectly reported as 0%, irrespective of the actual usage.
This is because of a snippet in the Javascript that computes the percentage:
```javascript
//Compute Usage
function computeMemUsage(used, max) {
let percent = 0;
if ( max > 0) {
let percent = Math.round((100 * used / max), 2);
}
let usage   =  bytesInGB(used, 2) + "GB (" + Math.max(0, percent) + "% of "+ bytesInGB(max, 2) +"GB)";
return usage;
}
```
Turns out, the `let` keyword creates a new `percent` variable within the scope of the `if (max > 0) { .. }` block, so the original variable never got updated. The fix was to simply remove the `let` preceding the percentage computation.

DRILL-6467: Percentage usage of memory is reported as zero by the WebUI

---

exec/java-exec/src/main/resources/rest/static/js/graph.js

1. Unnest operator is expected to specify srcOp=##-## to help identify the source of its input.
2. Implicit Source Map is leveraged to capture implicit data flow pipelines between Unnest and Lateral. (Can be expanded to other operators too).
3. In addition, code refactored for more readability.
Sample Screenshot:

DRILL-6515: Render a link between the Unnest operator and it's source

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillLateralJoinRelBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillLateralJoinRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillUnnestRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/ProjectComplexRexNodeCorrelateTransposeRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/LateralJoinPrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/UnnestPrule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/JoinPrelRenameVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/CompoundIdentifierConverter.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/lateraljoin/TestE2EUnnestAndLateral.java

- Added new rule `ProjectComplexRexNodeCorrelateTransposeRule` which takes a complex expression from the `Project` below `Uncollect` rel node and creates new project with expressions from the left side of `Correlate` and this complex expression. 
For example, part of the plan before applying the rule:
```
LogicalCorrelate(correlation=[$cor0], joinType=[inner], requiredColumns=[{1}]): rowcount = 1.0, cumulative cost = {inf}, id = 100
EnumerableTableScan(subset=[rel#94:Subset#0.ENUMERABLE.ANY([]).[]], table=[[cp, lateraljoin/nested-customer.parquet]]): rowcount = 100.0, cumulative cost = {100.0 rows, 101.0 cpu, 0.0 io, 0.0 network, 0.0 memory}, id = 7
Uncollect(subset=[rel#99:Subset#3.NONE.ANY([]).[]]): rowcount = 1.0, cumulative cost = {1.0 rows, 1.0 cpu, 0.0 io, 0.0 network, 0.0 memory}, …
```

DRILL-6546: Allow unnest function with nested columns and complex expressions

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenColumnBulkEntry.java

Reserving same size intermediary buffers to handle the case of false-positive; that is, a column is first thought to be fixed length (after sampling), then reverted to variable length as we read more values.

DRILL-6570: Fixed IndexOutofBoundException in Parquet Reader

---

exec/java-exec/src/main/resources/rest/profile/list.ftl

Inject a small space to improve readability of the pagination links (CSS).
Before fix:
After fix:
@sohami can you review this minor change for the bug filed by @Khurram?

DRILL-6583: Add space between pagination links in Profiles (WebUI) list

---

exec/java-exec/src/main/codegen/templates/Decimal/CastDecimalVarDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/CastFloatDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/CastIntDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/CastVarCharDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SqlConverter.java
exec/java-exec/src/test/java/org/apache/drill/TestFunctionsQuery.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestCastFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestVarDecimalFunctions.java
exec/java-exec/src/test/resources/decimal/cast_decimal_int.json
exec/java-exec/src/test/resources/decimal/cast_decimal_vardecimal.json
exec/java-exec/src/test/resources/decimal/cast_int_decimal.json
exec/java-exec/src/test/resources/decimal/cast_vardecimal_decimal.json
exec/vector/src/main/java/org/apache/drill/exec/util/DecimalUtility.java

- Add check for the correctness of scale value;
- Add check for fitting the value to the value with the concrete scale and precision;
- Implement `negative` UDF for VarDecimal;
- Add unit tests for new checks and UDF.

DRILL-6472: Prevent using zero precision in CAST function

---

exec/java-exec/src/main/java/org/apache/drill/exec/rpc/AbstractDisposableUserClientConnection.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryWrapper.java

When query fails on Web UI result page no error is shown, only "No result found." 
This was because DRILL-6477 (PR #1309) switched to `WebUserConnection.await(long timeoutInMillis)` . Unlike the original `WebUserConnection.await()`, this method did not throw any UserException generated by a query failure.
The fix was to add a new WebUser-only method - `WebUserConnection.timedWait(long timeoutInMillis)` 
This ensures that other callers to the `WebUserConnection.await(timeoutInMillis)` are unaffected by the expected behaviour.
This is what the UI returns after this patch:
_When running query which hits memory limits (DRILL-6477), we get this:_
```
org.apache.drill.common.exceptions.UserException: RESOURCE ERROR: There is not enough heap memory to run this query using the web interface. …
```

DRILL-6591: Show Exception for failed queries submitted in WebUI

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/RecordDataType.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pojo/NonNullable.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pojo/PojoDataType.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/BitToUserConnectionIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/DrillbitIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ExtendedOptionIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/MemoryIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/OptionIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ProfileInfoIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ProfileJsonIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ThreadsIterator.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/TestSystemTable.java

This addresses the issue of columns in the System tables being marked as non-nullable. While these tables are immutable, they can carry nullable values as well. (e.g. `num_val` in `sys.options`)
This commit introduces an annotation for the `PojoReader` that applies the nullable property if explicitly defined for a column (i.e. explicitly defined `isNullable` for a member of the POJO instance).
```
apache drill 1.14.0-SNAPSHOT 
"just drill it"
0: jdbc:drill:schema=sys> select count(*) from sys.options where num_val is null;
+---------+
| EXPR$0  |
+---------+
| 108     |
+---------+
1 row selected (2.703 seconds)
0: jdbc:drill:schema=sys> select count(*) from sys.options where isnull(num_val);
+---------+
| EXPR$0  |
+---------+
| 108     |
+---------+
1 row selected (0.3 seconds)
0: …
```

DRILL-6588: Make Sys tables of nullable datatypes

---

exec/jdbc-all/pom.xml

Increased the jdbc-all jar file size limit to allow a Release build (for 1.14)

DRILL-6632: Increase jdbc-all jar size limit to 36500000

---

pom.xml

Commented out (may revisit in the future) the dependency on "tests" for drill-java-exec and drill-common in the maven-javadoc-plugin in the root pom.xml ; otherwise the "Preparing the release" step fails, probably due to confusion between 1.14.0-SNAPSHOT build just made and the needed 1.14.0 .

DRILL-6637: Remove dependency on tests in the maven-javadoc-plugin in  the drill-root pom

---

contrib/native/client/src/protobuf/UserBitShared.pb.cc
contrib/native/client/src/protobuf/UserBitShared.pb.h
exec/java-exec/src/main/java/org/apache/drill/exec/physical/config/PartitionLimit.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/limit/PartitionLimitBatchCreator.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/limit/PartitionLimitRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/unnest/UnnestRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/LimitPrel.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/BaseTestOpBatchEmitOutcome.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/MockRecordBatch.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/PartitionLimit/TestPartitionLimitBatch.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/lateraljoin/TestE2EUnnestAndLateral.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/unnest/MockLateralJoinBatch.java
protocol/src/main/java/org/apache/drill/exec/proto/UserBitShared.java
protocol/src/main/java/org/apache/drill/exec/proto/beans/CoreOperatorType.java
protocol/src/main/protobuf/UserBitShared.proto

This PR includes some commits which are not part of PartitionLimit fix. Please ignore those commits. Here are the list of commits to be ignored.
DRILL-6616: Batch Processing for Lateral/Unnest
DRILL-6619: Lateral changes for implicit column  …
DRILL-6618: Unnest changes for implicit column  …
DRILL-6617: Planner Side changed to propagate $drill_implicit_field$ … …
The commits which pertain to ParitionLimit build upon the above commits, hence these are included in this PR. While merging this PR please cherry-pick only the below relevant commits and then merge them accordingly.
As regards to other commits which are related to execution changes for PartitionLimit, @parthchandra  can you please review the changes.
@amansinha100 Please review the planner side changes for handling …

DRILL-6652: PartitionLimit changes for Lateral and Unnest

---

src/main/resources/checkstyle-config.xml

This checkstyle check prevents errors with package declarations (https://issues.apache.org/jira/browse/DRILL-6651) from sneaking in.

DRILL-6655: Require package declaration in files.

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java

Changed the internal configuration of the Parquet reader to cap the maximum number of rows per batch to 64k. This is precautionary as downstream operators expect batches of no more than 64k rows.

DRILL-6664: Limit the maximum parquet reader batch rows to 64k

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/HashAggBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/HashAggTemplate.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinHelperSizeCalculatorImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinMemoryCalculatorImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/validate/IteratorValidatorBatchIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/ExternalSortBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/RecordBatch.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestBuildSidePartitioningImpl.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestHashJoinHelperSizeCalculatorImpl.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestLateralJoinCorrectness.java

(1) First commit just renamed MAX_BATCH_SIZE to MAX_BATCH_ROW_COUNT in order to avoid confusion over "size".
(2) 2nd commit: Addressing two issues: The configuration batch size (default 16M) is taken as is (by the memory manager). And the (outgoing) batch size estimates are created early (when the outgoing is empty), based on 64K rows per batch.
The change: Taking the Hash-Agg memory limit into account, and planning for multiple batches, the configured size (e.g. 16M) may be reduced to allow for the needed number of batches (this new size is given to the memory manager).
Later when the estimates are made, that (possibly reduced) size is used to reduce the estimates, if needed.

DRILL-6566: Reduce Hash Agg Batch size and estimate when low available memory

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/output/OutputWidthCalculators.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/OutputWidthExpression.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/OutputWidthVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectMemoryManager.java

This change separates the metadata-width and data-width of a variable-width column such that the data-width is used in all intermediate calculations and the meta-data width is added finally when the column's width is accumulated into the total width.

DRILL-6688 Data batches for Project operator exceed the maximum specified

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinBatch.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/MockRecordBatch.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestHashJoinOutcome.java

When a running query is cancelled (e.g., when Disk is full while spilling), many next() calls return a STOP outcome. Any Hash-Join that is "sniffing" its incoming batches (by repeatedly calling next()) would proceed to update the memory manager regardless of the outcomes returned.
In some abnormal outcomes (like STOP), the batch's container is **not initialized**. The update call needs the batch's row count, which for *RemovingRecordBatch* is implemented (differently) by invoking the container's getRowCount() -- so in this case the call fails.
The Fix: Move all the checks for the abnormal conditions immediately after the "sniffing", thus returning early and avoiding the update of the memory manager.
Longer term question: How to implement getRowCount() for the record batch consistently.

DRILL-6517: Hash-Join: handling uninitialized vector container

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/SystemTable.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/TestOptions.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/TestOptionsAuthEnabled.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/options/TestConfigLinkage.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/TestPStoreProviders.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/TestSystemTable.java
exec/java-exec/src/test/java/org/apache/drill/exec/work/metadata/TestMetadataProvider.java

(As a follow up to DRILL-5735)
The current sys.options table has a verbose layout, because of which sys.options_internal was introduced. The latter supports `descriptions`, which means it makes sense to have that table as the new `sys.options`. The recommendation is to deprecate the old format, so that any dependencies continue to make use of it as long as required.
Existing tests have been patched to account for the swap.

DRILL-6684: Swap sys.options and sys.options_val tables

---

common/src/main/java/org/apache/drill/exec/metrics/CpuGaugeSet.java

When running Drill on the IBM JDK (J9), the webUI throws an ClassCastException :
Caused by: java.lang.ClassCastException: com.ibm.lang.management.ExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
This PR simply disables that, since Drill should ideally be recompiled with these alternative JDKs.

DRILL-6702: Disable CPU Reporting for non-HotSpot JDKs

---

contrib/native/client/src/protobuf/UserBitShared.pb.cc
contrib/native/client/src/protobuf/UserBitShared.pb.h
exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions1.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions3.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/output/DecimalReturnTypeInference.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/types/decimal/DecimalScalePrecisionAddFunction.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/types/decimal/DecimalScalePrecisionDivideFunction.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/types/decimal/DecimalScalePrecisionModFunction.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/types/decimal/DecimalScalePrecisionMulFunction.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/types/decimal/DrillBaseComputeScalePrecision.java
exec/java-exec/src/test/java/org/apache/drill/TestFunctionsQuery.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestVarDecimalFunctions.java

- Added adjustment to decimal return type inference rules to force setting non-negative scale and max numeric precision even for the cases when the actual resulting value may overflow expected precision.
- Added check at the execution stage for fitting decimal value into the expected precision.
This PR is based on the https://github.com/apache/drill/pull/1451

DRILL-6710: Disallow negative scale for decimal data type

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/unorderedreceiver/UnorderedReceiverBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/RecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/RecordBatchLoader.java

- Fixed IOB in HashJoin for inner and right joins on empty probe side.
- Documentated expected behavior of RecordBatch after returning NONE.
- Made UnorderedReceiver obey contract after returning NONE.

DRILL-6747: Fixed IOB in HashJoin for inner and right joins on empty probe side

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/AsyncPageReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/util/concurrent/ExecutorServiceUtil.java
exec/java-exec/src/test/java/org/apache/drill/exec/util/ExecutorServiceUtilTest.java
exec/jdbc-all/pom.xml

**Problem Description**
- Occasionally, a memory leak is observed within the Parquet reader (flat) when query cancellation is invoked
- I tried to fix this leak in a previous attempt but it seems it is still happening
- Thus far, only QA have been able to observe this issue (and only occasionally)
**Analysis**
- There was a recent breakthrough which gives me hope for addressing this issue
- The leak logged two piece of information: leak size and state of the child allocator
- The state of the child allocator indicated no leak (all allocated bytes were released)
- After code examination, it occurred to me this was happening because the Asynchronous Page Reader task was releasing the Drill buffer while the scan thread was closing the allocator
- The code attempts to cancel asynchronous …

DRILL-6410: Fixed memory leak in flat Parquet reader

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionImplementationRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/registry/FunctionRegistryHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/registry/LocalFunctionRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/FunctionsIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/SystemTable.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/registry/FunctionRegistryHolderTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/TestSystemTable.java
exec/java-exec/src/test/java/org/apache/drill/exec/work/metadata/TestMetadataProvider.java

This commit exposes available SQL functions in Drill and also detects UDFs that have been dynamically loaded into Drill. 
An example is shown below for 2 UDFs dynamically loaded into the cluster, along side the existing built-in functions that come with Drill.
```
0: jdbc:drill:schema=sys> select source, count(*) as functionCount from sys.functions group by source;
+-----------------------------------------+----------------+
|                 source                  | functionCount  |
+-----------------------------------------+----------------+
| built-in                                | 2704           |
| simple-drill-function-1.0-SNAPSHOT.jar  | 12             |
| drill-url-tools-1.0.jar                 | 1              |
+-----------------------------------------+----------------+
3 …
```

DRILL-3988: Expose Drill built-in functions & UDFs  in a system table

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/HashAggTemplate.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/AbstractSpilledPartitionMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/SpilledPartitionMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/SpilledState.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinProbe.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinProbeTemplate.java

Currently the logic for incrementing spill cycles and managing the spilled partition queue is duplicated in HashAgg and HashJoin. This change pulls out the common logic into a shared class.

DRILL-6719: Separate spilling queue logic from HashJoin and HashAgg.

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassTransformer.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/PlannerSettings.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/main/resources/drill-module.conf
exec/java-exec/src/test/java/org/apache/drill/test/QueryTestUtil.java

With introduction of DRILL-5735 , the descriptions for about half the system options still remain missing. This commit collects descriptions review by @bbevens 
1. Update options for HashAgg/Join	(@Ben-Zvi )
2. Update options for Parquet Reader/Writer	(@sachouche )
3. Update options for Planners	(@HanumathRao , @vdiravka , @KazydubB )
4. Update options for BatchSizing	(@bitblender )
5. Update options for Planner Optimizations	(@arina-ielchiieva )
6. Update options for Security & Kafka	(Krystal Nguyen)
7. Update options for Misc entries	(@arina-ielchiieva , @vvysotskyi )
In additional, there is a patch for `org.apache.drill.exec.compile.ClassTransformer.scalar_replacement` , which appears to have replaced `exec.compile.scalar_replacement`. References to the latter have been removed to …

DRILL-6715: Update descriptions for System Options table

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/RuleInstance.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillJoinRelBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillJoin.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillJoinRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillLateralJoinRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillRelFactories.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillSemiJoinRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/HashJoinPrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/HashJoinPrule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/JoinPrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/JoinPruleBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/MergeJoinPrule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/NestedLoopJoinPrule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/PlannerSettings.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SwapHashJoinVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/resources/drill-module.conf
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestSemiJoin.java
logical/src/main/java/org/apache/drill/common/logical/data/LogicalSemiJoin.java

This PR contains the planner changes for semi join optimization. It enables the Calcite's SemiJoinRule to transform the Join -- Agg combination to DrillSemiJoin. 
During the physical planning DrillSemiJoin is transformed to HashJoinPrel which can use SemiJoin information to build hash table efficiently.
For now the planner changes are disabled by default.  DRILL-6735 fixes the hash join changes to use this flag to efficiently build the hash table. The PR for DRILL-6735 will enable the semijoin optimization by default.
@amansinha100  Can you please help review this PR.

DRILL-6798: Planner changes to support semi-join.

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl
exec/java-exec/src/main/resources/rest/query/query.ftl

1. BugFix on parent commit: Ensure query submission is done with user name when impersonation is enabled.
2. Support non-Mac browsers
3. Support keyboard submission for profile pages with Edit Query tab. 
Preview of Hint on Windows (Chrome):

DRILL-6611: Add Ctrl+Enter support for query submission

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl

A PR for DRILL-6084 broke the auto-complete library required for Edit Query page, with the removal of the static javascript library.
https://github.com/apache/drill/pull/1491/files#diff-2bb3c04f1a9eead1faf57212cce5d2a9
The dynamically loaded script is not defined in the Freemarker template page.
The fix is trivial.
This is the console error:

DRILL-6837: Missing reference for dynamically created Javascript library

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl

Currently, a running query can be cancelled by navigating to the Edit Query Tab of the profile page, making it difficult to access. This commit allows the user to cancel from the query page.
In addition, the Duration segment is also made visible by default rather than collapsed.
Screenshot of a running query
Screenshot of a query being cancelled
Screenshot of a query after cancellation

DRILL-5571: Cancel running query from its Web UI

---

exec/java-exec/src/main/resources/rest/profile/list.ftl

Currently Drill UI allows canceling one query at a time.
This commit (on lines of DRILL-5571 /  PR #1531) allows for cancelling multiple `running` queries.
Multi Selection :
Cancel Status Popup:
Auto Refreshed  page:

DRILL-2035: Add ability to cancel multiple queries

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl

DRILL-5571 ( PR #1531 ) accidentally introduced a bug that permanently keeps the "Duration" panel closed instead of opening it. This trivial patch fixes that.

DRILL-6848: Duration panel in a query profile's WebUI does not open

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java

(The DIFF below is excessive due to indentation; but only two "lines" where actually changed).
The original code below handles the spilled partitions by getting the next one (as build+probe "incoming"), and then recursively calling *innerNext()*.  Each recursive call would end by (recursively) processing the next spilled partition.
The DRILL-6755 change (line 556) caused an early exit when the probe side was empty. Thus in special cases when a probe-side of a spilled partition was empty, this change would terminate the recursive chain early, thus not processing the remaining partitions.
The fix: When an empty probe-side spilled partition is seen - skip and process the next partition. A new check was added (line 624), and the code was altered into a "while" loop (line 618) to allow …

DRILL-6861: Hash-Join should not exit after an empty probe-side spilled partition

---

pom.xml

The latest version of the git-commit-id seems to work OK (passed all the Jenkins tests; even though the maven repository shows dependency on jackson.databind version 2.9.6, while we use 2.9.5 ; see https://mvnrepository.com/artifact/pl.project13.maven/git-commit-id-plugin/2.2.5 )
Performance on Jenkins build seems the same, but on my Mac a full clean build is nearly 2 minutes faster. And when adding the new option to skip this plugin ( -Dmaven.gitcommitid.skip=true ) , the clean build is 3-4 minutes faster.

DRILL-6864: Upgrade the git-commit-id plugin to 2.2.5

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl

The Freemarker template missed a check for a query's `Running` state to display the `[Cancel]` button.
The fix is trivial and only needs the check.

DRILL-6886: Cancel button does not show for running Query in WebUI

---

contrib/storage-opentsdb/src/test/java/org/apache/drill/store/openTSDB/TestOpenTSDBPlugin.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryTestUtil.java
exec/java-exec/src/test/java/org/apache/drill/test/TestGracefulShutdown.java

In the fix for DRILL-6912 was used a class from hadoop 2.7.4, but for `mapr` profile hadoop 2.7.1 is used, where this class is absent.
In this PR removed usage of `ServerSocketUtil` class.
For details please see [DRILL-6919](https://issues.apache.org/jira/browse/DRILL-6919).

DRILL-6919: Fix compilation error in TestGracefulShutdown class for mapr profile

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/ChainedHashTable.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/HashTableTemplate.java

When a new key is inserted into the hash-table's, a matching bucket is found (i.e., from its hash value modulo the table's size), but that bucket may contain an old key(s). A generated code method ("isKeyMatchInternalBuild") is used to compare and find if the two keys are identical.
Previously a special check in that method addressed the case where (any pair of matching) columns where both null; returning "no match" if so.  In such a case, the hash-join would have entered the new key as a new entry at that bucket, leading to a growing useless chain that could end up in O(n^2) work (as each new key checks against all old ones).
*The fix*: Generate a new method - "areBothKeysNull" - to perform that special check prior to the actual key match; used only for hash-join during build time.  Then …

DRILL-6880: For Hash-Join hash-table build - treat null keys as an equal match 

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/rowSet/impl/ColumnBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/rowSet/impl/ColumnState.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/rowSet/model/BaseTupleModel.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/rowSet/model/MetadataProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/rowSet/model/single/SingleSchemaInference.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/AbstractColumnMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/ColumnBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/MapBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/MapColumnMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/MetadataUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/PrimitiveColumnMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/RepeatedListBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/RepeatedListColumnMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/SchemaBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/SchemaContainer.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/TupleBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/TupleSchema.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/UnionBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/VariantColumnMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/VariantSchema.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/rowSet/impl/TestResultSetLoaderUnions.java
exec/java-exec/src/test/java/org/apache/drill/exec/record/TestTupleSchema.java
exec/java-exec/src/test/java/org/apache/drill/test/rowSet/test/DummyWriterTest.java
exec/java-exec/src/test/java/org/apache/drill/test/rowSet/test/TestSchemaBuilder.java
exec/java-exec/src/test/java/org/apache/drill/test/rowSet/test/TestVariantAccessors.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/ColumnMetadata.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/TupleMetadata.java

1. ColumnBuilder: setPrecisionAndScale method
2. SchemaContainer: addColumn method parameter AbstractColumnMetadata was changed to ColumnMetadata
3. MapBuilder / RepeatedListBuilder / UnionBuilder: added constructors without parent, made buildColumn method public
4. TupleMetadata: added toMetadataList method
5. Other refactoring
Details in [DRILL-6903](https://issues.apache.org/jira/browse/DRILL-6903).

DRILL-6903: SchemaBuilder code improvements

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/batchsizing/BatchOverflowOptimizer.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/batchsizing/BatchSizingMemoryUtil.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/batchsizing/RecordBatchSizerManager.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/columnreaders/TestBatchSizingMemoryUtil.java
exec/memory/base/src/main/java/org/apache/drill/exec/memory/BaseAllocator.java

**ANALYSIS**
* Code inspection suggest a rare scenario where such an issue could happen; example
* Row Group has a variable length column with the following sizes:
v1 (1k)
v2 (1k)
v3 (1MB)
v4 (1MB)
v5 (1MB)
.
.
v16 (1MB)
v17 (1k)
.. the rest of the values will be 1k
* This scenario can a) make the overall number of rows quite large (few thousands) and b) during a batch, the column precision might be inflated
* The batch sizing logic uses integers to assess the memory requirement; thus it is possible for the product NUM_BATCH_ROWS * COLUMN_PRECISION to overflow
* We use integer as most of the Drill framework uses integers to compute memory limits
* The code handles this use-case but there is one small window where this logic could break (when we are aggregating all column memory usage) …

DRILL-7100: Fixed IllegalArgumentException when reading Parquet data

---

contrib/format-ltsv/pom.xml
distribution/pom.xml
distribution/src/assemble/component.xml

With these changes, I'm now able to successfully add the `ltsv` format in the dfs storage plugin.

DRILL-7126: Contrib format-ltsv is not being included in distribution

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/SetOptionHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/Foreman.java
exec/java-exec/src/main/resources/drill-module.conf

Allows (by default) for `ALTER SESSION SET <option>=<value>` queries to NOT be writen to the profile store. This would avoid the risk of potentially adding up to a lot of profiles being written unnecessarily, since those changes are also reflected on the queries that follow.

DRILL-7110: Skip writing profile when an ALTER SESSION is executed

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/fragment/QueueQueryParallelizer.java
exec/java-exec/src/test/java/org/apache/drill/exec/planner/rm/TestMemoryCalculator.java

This PR fixes the issue to not look for physical operator in memory adjusted operators of the QueueQueryParallelizer when planHasMemory is set to true.
@sohami  can you please review this fix.

DRILL-7146: Query failing with NPE when ZK queue is enabled.

---

pom.xml

- change 'checksum-maven-plugin' 'goal' - 'artifacts' -> 'files'
- specify 'includes' in 'fileSet' for 'checksum-maven-plugin'

DRILL-7165: Redundant Checksum calculating for ASC files

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/decoder/Packet.java

If there is a packet with a length of 96, the PCAP parser crashes.  This small fix corrects that problem.

Drill-7185: Drill Fails to Read Large Packets

---

exec/java-exec/src/main/resources/rest/profile/profile.ftl

This bug arises because of the `toggleWarning()` javascript function that shows the warning if the number of slow major fragments matches the number of major fragments.
For failed queries, the number of major fragments = 0; and that matches the number of tags (which is also zero for a non-running query). Hence the warning shows.

DRILL-7202: Failed query shows warning that fragments made no progress

---

distribution/src/assemble/component.xml

For details please see comment under [DRILL-7213](https://issues.apache.org/jira/browse/DRILL-7213).

DRILL-7213: Use dependencySets tag for including artifacts in assembly to consider dependencies from the distribution module

---

exec/java-exec/src/main/resources/rest/alertModals.ftl

Looks like some unicode characters creeped in, causing the rendering to be messed up ONLY for Windows OS. This PR patches that issue and ensures that the Alert symbol also appears correctly.

DRILL-7201: Strange symbols in error window (Windows)

---

exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SqlConverter.java
exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestImpersonationQueries.java
pom.xml

- Removed `catalogReader.getTable(tempNode.names)` call since it does not resolve table names correctly using provided scope.
- Reworked `catalogReader.isValidSchema()` method to follow logic on how Calcite determines whether the table is present: it uses schemas from `CatalogReader` and resolves specified schema among them.
- Updated Calcite version to use the fix for `CALCITE-3061`.
- Added unit test.
For problem description please see [DRILL-7250](https://issues.apache.org/jira/browse/DRILL-7250).

DRILL-7250: Query with CTE fails when its name matches to the table name without access

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/svremover/AbstractSV2Copier.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/svremover/GenericSV2Copier.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorAccessible.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorContainer.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/selection/SelectionVector2.java
exec/java-exec/src/test/java/org/apache/drill/test/rowSet/test/TestScalarAccessors.java
exec/vector/src/main/codegen/templates/NullableValueVectors.java
exec/vector/src/main/java/org/apache/drill/exec/vector/NullableVector.java
exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/NullableScalarWriter.java

Turns out this is due to a subtle issue with variable-width nullable
vectors. Such vectors have a lastSet attribute in the Mutator class.
When using "transfer pairs" to copy values, the code somehow decides
to zero-fill from the lastSet value to the record count. The row set
framework did not set this value, meaning that the RemovingRecordBatch
zero-filled the dir0 column when it chose to use transfer pairs rather
than copying values. The use of transfer pairs occurs when all rows in
a batch pass the filter prior to the removing record batch.
Modified the nullable vector writer to properly set the lastSet value at
the end of each batch. Added a unit test to verify the value is set
correctly.
Includes a bit of code clean-up.

DRILL-7257: Set nullable var-width vector lastSet value

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionImplementationRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/registry/FunctionRegistryHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/registry/LocalFunctionRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillMergeProjectRule.java

Please see [DRILL-7317](https://issues.apache.org/jira/browse/DRILL-7317) for problem description.

DRILL-7317: Close ClassLoaders used for udf jars uploading when closing FunctionImplementationRegistry

---

contrib/storage-hive/core/src/main/java/org/apache/drill/exec/expr/fn/HiveFuncHolder.java
exec/java-exec/src/main/codegen/templates/CastHigh.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/AbstractFuncHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/DrillAggFuncHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/DrillComplexWriterAggFuncHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/DrillComplexWriterFuncHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/DrillSimpleFuncHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/output/DecimalReturnTypeInference.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestSimpleCastFunctions.java

For problem description please see: [DRILL-7307](https://issues.apache.org/jira/browse/DRILL-7307)
- Fixed code-gen render for nullable constants
- Fixed code-gen issue with nullable holders for simple cast functions
with passed constants as arguments.
- Code-gen now honnoring DataType.Optional type defined by UDF for
NULL-IF-NULL functions.

DRILL-7307: casthigh for decimal type can lead to the issues with VarDecimalHolder

---

contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/MaprDBJsonRecordReader.java
contrib/storage-hive/core/scrMapr/main/java/org/apache/drill/exec/planner/sql/logical/ConvertHiveMapRDBJsonScanToDrillMapRDBJsonScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/JsonReaderUtils.java
exec/vector/src/main/codegen/templates/ComplexCopier.java

- Introduced separate methods for creating writers according to the specified schema and removed it from existing `ensureAtLeastOneField()` method.
- Fixed issue with the wrong name of the `_id` columns for the case when another name is specified in Hive properties.

DRILL-7376: Drill ignores Hive schema for MaprDB tables when group scan has star column

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroRecordReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/FieldIdUtil.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/avro/AvroFormatTest.java
exec/vector/src/main/codegen/templates/AbstractFieldReader.java
exec/vector/src/main/codegen/templates/BaseReader.java
exec/vector/src/main/codegen/templates/NullReader.java
exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/SingleDictReaderImpl.java
logical/src/main/java/org/apache/drill/common/expression/PathSegment.java
logical/src/main/java/org/apache/drill/common/expression/SchemaPath.java

- Fixed `FieldIdUtil` to resolve reading from `DICT` for some complex cases;
- optimized reading from `DICT` given a key by passing an appropriate `Object` type to `DictReader#find(...)` and `DictReader#read(...)` methods when schema is known (e.g. when reading from Hive tables) instead of generating it on fly based on int or String path and key type;
- fixed error when accessing value by not existing key value in Avro table.
Jira - [DRILL-7373](https://issues.apache.org/jira/browse/DRILL-7373).

DRILL-7373: Fix problems involving reading from DICT type

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/HashTableTemplate.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/spill/SpillSet.java

A Hash-Table OOM exception may happen while a vector container was allocated but not yet initialized (with _setRecordCount()_ ). This exception is caught and a detailed error message is generated, which involves calling _getRecordCount()_ on existing vector containers, hence could trigger an **IllegalStateException** on such uninitialized container.
The fix: Ignore such uninitialized vector container (i.e., like record-count == 0) in the code that is used for generating that error message (currently _getActualSize()_ is only used for this purpose).
Another code change: While testing on the Mac, the spilling code for regular file systems failed to delete leftover spilled directories (which were not empty). The code was changed to delete all the spill files first in a spill directory, and …

DRILL-7170: Ignore uninitialized vector containers for OOM error messages

---

_docs/data-sources-and-file-formats/050-json-data-model.md

Fixes copy/paste error stemming from bad JSON formatting.

DRILL-7394: JSON in Documentation Contains Typo

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/BuildFromSchema.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ColumnBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/TupleState.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestResultSetLoaderRepeatedList.java
exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/AbstractTupleWriter.java

The Result Set Loader (part of EVF) allows adding columns up-front
before reading rows (so-called "early schema.") Such schemas allow
nested columns (maps with members, repeated lists with a type, etc.)
The Result Set Loader also allows adding columns dynamically
while loading data (so-called "late schema".) Previously, the code
assumed that columns would be added top-down: first the map, then
the map's contents, etc.
Charles found a need to allow adding a nested column (a repeated
list with a declared list type.)
This patch revises the code to use the same mechanism in both the
early- and late-schema cases, allowing adding nested columns at
any time.
Testing: Added a new unit test case for the repeated list late
schema with content case.

DRILL-7377: Nested schemas for dynamic EVF columns

---

contrib/format-ltsv/src/main/java/org/apache/drill/exec/store/ltsv/LTSVFormatPlugin.java
contrib/format-ltsv/src/main/java/org/apache/drill/exec/store/ltsv/LTSVRecordReader.java
contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogFormatPlugin.java
contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogRecordReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/partition/PruneScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/BasicFormatMatcher.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSelection.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FormatSelection.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/ZipCodec.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/log/LogBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/PcapBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/PcapFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcapng/PcapngFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcapng/PcapngRecordReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcapng/package-info.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestCompressedFiles.java

1. Added ZipCodec implementation which can read / write single file.
2. Revisited Drill plugin formats to ensure 'openPossiblyCompressedStream' method is used in those which support compression.
3. Added unit tests.
4. General refactoring.
Jira - [DRILL-5674](https://issues.apache.org/jira/browse/DRILL-5674).

DRILL-5674: Support ZIP compression

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/ScanBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/validate/BatchValidator.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorContainer.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JSONFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileFormatPlugin.java
exec/java-exec/src/test/java/org/apache/drill/exec/record/vector/TestDateTypes.java
exec/java-exec/src/test/resources/parquet/alltypes_repeated.json

Enables vector validation tests for the ScanBatch and all  EasyFormat plugins. Fixes a bug in scan batch that failed to set the record count in the output container.
Fixes a number of formatting and other issues found while adding the tests.

DRILL-7413: Test and fix scan operator vectors

---

metastore/iceberg-metastore/pom.xml

Jira - [DRILL-7347](https://issues.apache.org/jira/browse/DRILL-7347).

DRILL-7347: Upgrade Apache Iceberg to released version

---

contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoChunkAssignment.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/AbstractSqlPatternMatcher.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctionHelpers.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/validate/BatchValidator.java
exec/java-exec/src/test/java/org/apache/drill/TestCTASPartitionFilter.java
exec/java-exec/src/test/java/org/apache/drill/TestPartitionFilter.java
exec/java-exec/src/test/java/org/apache/drill/TestTpchSingleMode.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/lateraljoin/TestLateralPlans.java

Enabled the "batch validator" for the Project operator. Ran tests.
Exceptions occurred because, in some paths, the Project operator
fails to set the container row count.
Fixes the Project operator. Cleans up formatting issues in files
touched during the investigation. Cleaned up batch-related issues
in Project.

DRILL-7424: Project operator fails to set the container row count

---

exec/java-exec/src/test/java/org/apache/drill/TestExampleQueries.java
pom.xml

Jira: [DRILL-7391](https://issues.apache.org/jira/browse/DRILL-7391).
Actual fixes were done in Calcite ([CALCITE-3390](https://issues.apache.org/jira/browse/CALCITE-3390), [CALCITE-3457](https://issues.apache.org/jira/browse/CALCITE-3457)), this PR just adds unit test and updates Calcite version to include these fixes.

DRILL-7391: Wrong result when doing left outer join on CSV table

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/ImplCreator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java

Adds dummy parameter types to several files to avoid compilation errors
when loading Drill into Eclipse.

DRILL-7446: Fix Eclipse compilation issue in AbstractParquetGroupScan

---

common/pom.xml
exec/java-exec/pom.xml
exec/vector/pom.xml
logical/pom.xml
pom.xml

Jira - [DRILL-7453](https://issues.apache.org/jira/browse/DRILL-7453)

DRILL-7453: Update joda-time to 2.10.5 to have correct time zone info

---

_docs/install/050-starting-drill-in-distributed-mode.md

Update Documentation to use En-dash Code Points in Command Line Examples

---

exec/java-exec/src/main/java/org/apache/drill/exec/metastore/analyze/AnalyzeColumnUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/metastore/analyze/MetadataControllerContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/metadata/MetadataControllerBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/metadata/MetadataHandlerBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/ConvertMetadataAggregateToDirectScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilter.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java
metastore/metastore-api/src/main/java/org/apache/drill/metastore/statistics/ColumnStatisticsKind.java
metastore/metastore-api/src/main/java/org/apache/drill/metastore/statistics/ExactStatisticsConstants.java

Please refer to [DRILL-7471](https://issues.apache.org/jira/browse/DRILL-7471) for details.

DRILL-7471: DESCRIBE TABLE command fails with ClassCastException when Metastore is enabled

---

docs/dev/Environment.md

Updating the instructions for setting up the development environment. Developers are now instructed to skip running tests as part of initial setup.
JIRA: https://issues.apache.org/jira/browse/DRILL-7548

DRILL-7548: Updating Environment.md to Skip Tests

---

docs/dev/Calcite.md

Updated `Calcite.md` to unify the place where docs should be changed after every Calcite update.
Updated documentation.
NA

DRILL-7540: Update Calcite.md doc

---

metastore/iceberg-metastore/README.md
metastore/iceberg-metastore/pom.xml
metastore/iceberg-metastore/src/main/java/org/apache/drill/metastore/iceberg/IcebergMetastore.java
metastore/iceberg-metastore/src/main/java/org/apache/drill/metastore/iceberg/components/tables/IcebergTables.java
metastore/iceberg-metastore/src/main/java/org/apache/drill/metastore/iceberg/config/IcebergConfigConstants.java
metastore/iceberg-metastore/src/main/java/org/apache/drill/metastore/iceberg/operate/ExpirationHandler.java
metastore/iceberg-metastore/src/main/java/org/apache/drill/metastore/iceberg/operate/IcebergModify.java
metastore/iceberg-metastore/src/main/resources/drill-metastore-module.conf
metastore/iceberg-metastore/src/test/java/org/apache/drill/metastore/iceberg/operate/TestExpirationHandler.java

[DRILL-7544](https://issues.apache.org/jira/browse/DRILL-7544): Upgrade Iceberg version to support Parquet 1.11.0
1. Upgraded Iceberg to the commit that supports Parquet 1.11.0.
2. Removed workaround in ExpirationHandler and used built-in logic from Iceberg library.
3. Updated description about expiration logic in README.md.
No documentation updates are required.
Updated some of unit tests and ran all tests.

DRILL-7544: Upgrade Iceberg version to support Parquet 1.11.0

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/FormSecurityHandler.java

[DRILL-7575](https://issues.apache.org/jira/browse/DRILL-7575): FormSecurityHandler class name is spelled incorrectly
Just a little fix to the name of this class.  It isn't referenced anywhere by name, so only the class file itself had to be changed.

DRILL-7575: Fix typo in class name of FormSecurityHandler

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java

I noticed this method name was not spelled correctly, so here's a little fix.

DRILL-7584: Fix method name spelling

---

contrib/format-esri/pom.xml

Removes hard coded version number from `format-esri`.
No user visible changes
Ran unit tests associated with this format plugin.

DRILL-7596: drill-format-esri module Uses Hard Coded Version Number

---

_docs/developer-information/rest-api/010-rest-api-introduction.md

Add documentation for current and near-future REST API authentication / authorization mechanism.  This didn't seem to be clearly documented before - the documentation mostly seemed to assume the drill server did not require and authentication.
Documents features added in https://github.com/apache/drill/pull/1972 so that should be merged first.

DRILL-7561: Document REST API authentication

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/TestPluginRegistry.java

Fixes a misunderstanding in prior PR: `StoragePluginRegistry.`getConfigs()` should return both enabled and disabled configs. This contrasts with other `get` methods which return only enabled plugins.
Added additional unit tests to verify behavior. Ran the full Drill to reproduce the scenario in the Jira ticket. Web UI now works as expected.

DRILL-7617: Disabled plugins not showing in Web UI

---

exec/java-exec/src/main/resources/rest/index.ftl

Fixed link to the metrics endpoint
n/a
Tested manually on the Web UI

DRILL-7619: Fixed link to the metrics endpoint

---

_docs/configure-drill/configuration-options/040-persistent-configuration-storage.md

Try to improve PStore configuration docs to be a bit less confusing (to me at least), and also add an example showing how you could store the query profiles on Amazon S3 (which would have been useful information to me)

Clean up a bit, add example for s3 storage of query profiles

---

contrib/storage-mongo/src/test/resources/core-site.xml

Please see Jira for details.
NA
Ran all tests.

DRILL-7635: Mongo tests fail for profiles with the non-file default file system

---

contrib/storage-jdbc/pom.xml
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStoragePlugin.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestDataSource.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithH2IT.java
pom.xml

This PR replace DBCP2 with HikariCP in RDBMS (JDBC) plugin since HikariCP is much faster and more reliable.
https://beansroasted.wordpress.com/2017/07/29/connection-pool-analysis/
https://github.com/brettwooldridge/HikariCP
NA
Added unit tests, ran all tests, tested manually.

DRILL-7639: Replace DBCP2 with HikariCP in RDBMS (JDBC) plugin

---

distribution/src/main/resources/drill-override-example.conf
exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/header/ResponseHeadersSettingFilter.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestResponseHeaders.java
exec/java-exec/src/test/java/org/apache/drill/test/ConfigBuilder.java
exec/java-exec/src/test/java/org/apache/drill/test/RestClientFixture.java

1. Created ResponseHeadersSettingFilter for adding configured values to each response.
2. Now for when drill.exec.http.ssl_enabled is set to true, users can add following headers
to improve security:
"X-XSS-Protection" : "1; mode=block",
"X-Content-Type-Options" : "nosniff",
"Strict-Transport-Security" : "max-age=31536000;includeSubDomains",
"Content-Security-Policy" : "Content-Security-Policy": "default-src https:; script-src 'unsafe-inline' https:; style-src 'unsafe-inline' https:; font-src data: https:; img-src data: https:"
Adding of new response headers now available in drill-override.conf under key drill.exec.http.jetty.server.response.headers . For example:
```
drill.exec: {
cluster-id: "drillbits1",
zk.connect: "localhost:2181", 
http: {
ssl_enabled: true, …
```

DRILL-7626: Add ability to set HTTP response headers

---

exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/UserServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfigurator.java

Added 2 log messages.
Two new messages will be available in logs when SSL enabled. 

DRILL-7644: Log SSL protocol version at Drill start up

---

distribution/src/main/resources/drill-override-example.conf
exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfigurator.java
exec/java-exec/src/main/resources/drill-module.conf

Jetty server implements a useful tool for dumping the current state of the server, but in Drill, it's not possible to use it without code changes. This ticket aims to add option drill.exec.http.jetty.server.dumpAfterStart in Apache Drill.
Another change is to remove the redundant setProtocol(protocol) method call on sslContextFactory instance.
Set drill.exec.http.jetty.server.dumpAfterStart to true if you want to check server state in logs. 

DRILL-7650: Add option to enable Jetty's dump for troubleshooting

---

contrib/udfs/README.md
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/TimeBucketFunctions.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestTimeBucketFunction.java

This PR adds two UDFs which facilitate time series analysis.  This PR also includes updates to the `README.md` in the `contrib/udf` folder to reflect the new UDF.
These functions are useful for doing time series analysis by grouping the data into arbitrary intervals.  See: https://blog.timescale.com/blog/simplified-time-series-analytics
-using-the-time_bucket-function/ for more examples. 
There are two versions of the function:
* `time_bucket(<timestamp>, <interval>)`
* `time_bucket_ns(<timestamp>,<interval>)`
Both functions accept a `BIGINT` timestamp and an interval in milliseconds as arguments. The `time_bucket_ns()` function accepts timestamps in nanoseconds and `time_bucket
()` accepts timestamps in milliseconds.  Both return timestamps in the original format.
The query below …

DRILL-7652: Add time_bucket() function for time series analysis

---

.github/workflows/ci.yml
pom.xml

Allowed building Drill with JDK 14, updated ASM and javassist to the latest versions, updated GitHub Actions script to build and run tests for Java 14 instead of 13.
NA
Checked that Drill is starting without errors or new warnings on Linux and Windows, made sanity checks to ensure that functionality is preserved.

DRILL-7654: Add support for JDK 14

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/DrillHttpSecurityHandlerProvider.java

1. Added callback for setting headers in DrillHttpSecurityHandlerProvider,
since ResponseHeadersSettingFilter doesn't cover this flow.
No need to document the bugfix.
Tested manually since the security configuration for using form-based authentication is hard to do in unit tests.

DRILL-7648: Scrypt j_security_check works without security headers

---

exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestResultSetLoaderUnions.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/rowSet/TestSchemaBuilder.java
exec/java-exec/src/test/java/org/apache/drill/test/rowSet/RowSetComparison.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantColumnMetadata.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantSchema.java
exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/VariantWriter.java
exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/UnionVectorShim.java

Minor fixes and cleanup for the obscure union and repeated list types in the column accesor framework.
Fixed several minor issues in the row set test utilities: improved error message, proper comparing of floating-point values. Support for `Boolean` values in the `RowSetBuilder`.
Fixes for building a repeated list or union schema using `SchemaBuilder`.
Special handling to treat a `LIST` as an array, even though the mode is not `REPEATED`. (This is a very hacky corner of Drill!)
None
Added unit tests for union and repeated list types. Code comes from the project to improve the JSON reader which is where the issues were discovered and fixes tested in the context of reading JSON.

DRILL-7633: Fixes for union and repeated list accessors

---

exec/java-exec/src/main/java/org/apache/drill/exec/resolver/DefaultFunctionResolver.java

extract common static logic from the for loop
NO
NO

DRILL-7663: Code refactor to DefaultFunctionResolver

---

exec/vector/src/main/antlr4/org/apache/drill/exec/record/metadata/schema/parser/SchemaLexer.g4
exec/vector/src/main/antlr4/org/apache/drill/exec/record/metadata/schema/parser/SchemaParser.g4
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/schema/parser/SchemaVisitor.java
exec/vector/src/test/java/org/apache/drill/exec/record/metadata/schema/parser/TestSchemaParser.java

After DRILL-7633 has defined proper type string for UNION it should be added to schema parser to allow proper column metadata ser / de.
NA

DRILL-7665: Add UNION to schema parser

---

contrib/pom.xml

Several contrib plugins depend on UDFs for testing. However, the UDFs occur after the plugins in build order. This PR reverses the dependencies so that UDFs are built before the plguins that want to use them.
For example, suppose you add a new `Foo` data source that needs some UDFs. You want to test the `Foo` data source. But, you find that your tests cannot find your UDFs. After a bit of frustrating debugging, you find that your UDFs are not on your debug class path. Why? Because the UDFs appear in the build order after the storage plugins.
Since it is more often the case that a plugin (or its tests) depend on a UDF than the other way around, went ahead and reversed the order.
For developers, if you want to test a contributed UDF with a contributed plugin; put the test in the plugin …

DRILL-7680: Place UDFs before plugins in contrib

---

contrib/storage-hive/core/src/test/java/org/apache/drill/exec/hive/complex_types/TestHiveStructs.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectBatchBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/union/UnionAllRecordBatch.java
exec/java-exec/src/test/java/org/apache/drill/TestUntypedNull.java

Column ordering was wrong when the first selected column had type STRUCT and second had a primitive type. 
No need to document it.
Added unit test in TestHiveStructs.

DRILL-7429: Wrong column order when selecting complex data using Hive storage plugin

---

exec/jdbc/pom.xml

This PR fixes a bug by updating the `javax.validation` dependency to the most current version.
No user visible changes.
Ran existing unit tests for `jdbc` package.

DRILL-7699: Update javax.validation Dependency

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryResources.java
exec/java-exec/src/main/resources/rest/query/query.ftl

In v1.18.0, users specify a schema through an input field but this is error prone and doesn't restrict options to enabled storage plugins.
I propose that it be changed to a dropdown that lists enabled storages as options, and automatically defaults if there is only one available storage.
N/A
Manually tested through Web UI both locally and in Shopify's production deployment of Apache Drill.
https://drill.shopifycloud.com/query

DRILL-7692: Add dropdown to select default storage

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/BaseOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/FallbackOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/InMemoryOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/OptionValue.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SessionOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRoot.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryWrapper.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/RestQueryRunner.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
exec/java-exec/src/main/resources/rest/profile/profile.ftl
exec/java-exec/src/main/resources/rest/query/query.ftl
exec/java-exec/src/test/java/org/apache/drill/exec/server/options/OptionValueTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/InteractiveUI.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/RestServerTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestQueryWrapper.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestQueryWrapperImpersonation.java
exec/java-exec/src/test/java/org/apache/drill/test/ClusterFixture.java
exec/java-exec/src/test/java/org/apache/drill/test/ClusterFixtureBuilder.java

Also includes:
* [DRILL-7604](https://issues.apache.org/jira/browse/DRILL-7604): Cannot set session options using REST API / Web UI
* [DRILL-7655](https://issues.apache.org/jira/browse/DRILL-7655): Add Default Schema text box to Edit Query page in query profile
Update and revision of work originally done by @dobesv. All credit to @dobesv for these nice enhancements.
* DRILL-7603: Allow default schema to be set for HTTP queries, #1996
* DRILL-7604: Allow session options to be set in HTTP queries, #1997
Merges the two PRs since they touch the same files. Work stalled when a reviewer requested that the author use existing mechanisms to parse option values. Doing so was a bit tricky, and the author didn't have time. This PR does that work, which turned out to require some changes in the …

DRILL-7603 and DRILL-7604: Add schema, options to REST query

---

common/src/main/java/org/apache/drill/common/concurrent/AbstractCheckedFuture.java
common/src/main/java/org/apache/drill/common/concurrent/CheckedFuture.java
common/src/main/java/org/apache/drill/common/exceptions/DrillIOException.java
contrib/format-maprdb/pom.xml
contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/binary/BinaryTableGroupScan.java
contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/JsonTableGroupScan.java
contrib/storage-hbase/pom.xml
contrib/storage-hive/core/pom.xml
contrib/storage-hive/hive-exec-shade/pom.xml
distribution/src/assemble/component.xml
drill-shaded/drill-shaded-guava/pom.xml
drill-yarn/src/main/java/org/apache/drill/yarn/zk/ZKClusterCoordinator.java
exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/coord/zk/ZKClusterCoordinator.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/UserClient.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/QueryWorkUnit.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/Foreman.java
exec/jdbc-all/pom.xml
exec/rpc/src/main/java/org/apache/drill/exec/rpc/DrillRpcFuture.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/DrillRpcFutureImpl.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcCheckedFuture.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcException.java
pom.xml

This pull request contains 3 commits where different libraries are updated.
- The first commit contains changes for updating `jetty`, `commons-compress`, `httpclient`, `httpdlog-parser`, `libthrift` and `derby` libraries. Such libraries as `log4j-core`, `commons-httpclient` and `tomcat` (`jasper-compiler`, etc.) are banned to avoid adding them occasionally as transitive dependencies to the project.
- The second commit contains changes for updating ZooKeeper and Curator versions. The latest available curator version (4.3.0) doesn't support Zookeeper 3.6.0 yet, so updated Zookeeper to 3.5.7. Updating Curator helped to avoid using the outdated `org.codehaus.jackson` libraries, but they weren't added to banned dependencies since they are transitively used by other non-default supported …

DRILL-7702: Update zookeeper, curator, guava, jetty-server, libthrift, httpclient, commons-compress and httpdlog-parser

---

Dockerfile
docs/dev/Docker.md
docs/dev/Environment.md
docs/dev/InstantiatingComponents.md
exec/java-exec/pom.xml
pom.xml
tools/fmpp/pom.xml

Update Maven dependency to 3.6.3
Need to update https://drill.apache.org/docs/compiling-drill-from-source/ page
Ran all tests.

DRILL-7704: Update Maven to 3.6.3

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderOptions.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/RepeatedListValueListener.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/TupleListener.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/UnknownFieldListener.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/TokenIterator.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestObjects.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestRepeatedList.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestScalarArrays.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestScalars.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestUnknowns.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestVariant.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MetadataUtils.java

As work continues on adding the new JSON reader to Drill, running unit tests reveals that some include list with three (perhaps more) dimensions.
Revises the EVF-based JSON loader to support nested repeated lists.
Took this opportunity to review and clean up the many "create listener for" methods in the JSON loader object listener.
N/A
Added new tests to verify 3D lists. Reran all existing unit tests to verify no regressions after refactoring.

DRILL-7703: Support for 3+D arrays in EVF JSON loader

---

exec/java-exec/src/test/java/org/apache/drill/exec/metastore/TestMetastoreWithEasyFormatPlugin.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchemaWithMetastore.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java

Fixed deleting metadata for the failing test. Fixed `ZK_ROOT` location. Before changes, was passed relative folder location to the config, like `./target/org.apache.drill.exec.sql.TestMetastoreCommands/dfsTestTmp/...`. When drillbit for tests is started, it resolves this folder location in relation to the home directory, so table metadata wasn't dropped between two test runs.
NA
Reran all tests.

DRILL-7710: Fix TestMetastoreCommands#testDefaultSegment test

---

contrib/native/client/CMakeLists.txt
contrib/native/client/readme.linux
contrib/native/client/test/ssl/testClient.cpp
contrib/native/client/test/ssl/testServer.cpp

To support TLS1.2 flag, Boost ASIO 1.54 is required.
Also replace deprecated use of
`ssl::context::context(boost::asio::io_service &, method m)` which has
been removed from recent versions of Boost ASIO (>= 1.66).
Tested against macos and linux

DRILL-7726: Update boost requirement to 1.54

---

contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveStoragePlugin.java
drill-yarn/src/main/java/org/apache/drill/yarn/core/YarnRMClient.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/config/StreamingAggregate.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/HashAggBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/StreamingAggBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/StreamingAggTemplate.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/metadata/MetadataControllerBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/ScanOperatorExec.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/ExternalSortBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/SortImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/AggPrelBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorContainer.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/ArrayParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/DummyValueParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonValueParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/ObjectParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/SimpleMessageParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/rm/DistributedQueryQueue.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestResultSetCopier.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/rowSet/TestRowSet.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/InteractiveUI.java
exec/java-exec/src/test/java/org/apache/drill/test/ClientFixture.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryResultSet.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryRowSetIterator.java

A debugging session revealed opportunities to simplify `MetadataControllerBatch` - replaced a bunch of flags with a state enum, and other cleanup.
N/A
Reran all unit tests.

DRILL-7724: Refactor metadata controller batch

---

exec/java-exec/src/test/resources/drill-udf/pom.xml

Please see the Jira description for details.
NA
Ensured that CI tests pass.

DRILL-7738: Fix TestDynamicUDFSupport failure for GitHub Actions

---

exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SchemaUtilites.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java
exec/java-exec/src/test/java/org/apache/drill/test/ClusterFixture.java

Fixed checking mutability of workspace in `SchemaUtilites.resolveToDrillSchemaInternal()` method. Replaced base class of `RootSchema` to fix exception when root schema is used.
Please note, that for `cp` storage plugin, it is still impossible to do `analyze` since classpath file system cannot list files.
NA
Added tests for cases from Jira ticket.

DRILL-7707: Unable to analyze table metadata is it resides in non-writable workspace

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPushDownListener.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/ConstantHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/ExprNode.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/FilterPushDownListener.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/FilterPushDownStrategy.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/FilterPushDownUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/RelOp.java

This PR moves the filter abstraction code used in the HTTP plugin to Drill core.  This enables other storage plugins to use this code. 
No user visible changes.
Ran tests for HTTP plugin.

DRILL-7744: Move Filters from HTTP Storage Plugin to Drill Core

---

contrib/native/client/CMakeLists.txt
contrib/native/client/src/clientlib/rpcMessage.cpp
contrib/native/client/src/protobuf/CMakeLists.txt

Fix protobuf warning message about the use of ByteSize(), replaced with
ByteSizeLong().
Also add a minimum version requirement to match what is described in the
docs.
build on linux and macos

DRILL-7727 Fix protobuf warning message

---

exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigClient.java
exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLCredentialsProvider.java

Added support for Hadoop CredentialProvider API for keystore and trustore passwords.
Manually tested the fix and ran existing test suits.

DRILL-7750: Drill fails to read KeyStore password from Credential provider

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/FilePushDownFilter.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetFilterPushDown.java

Added threshold for the number of nodes that can be created out of the conversion to avoid OOM.
NA

DRILL-7761: Drill fails with OOM for the case of large filter conditions

---

common/src/main/java/org/apache/drill/common/util/GuavaPatcher.java

Removed unnecessary logging of stack trace (on `WARN` level) when patching Guava fails.
N/A
Ran all existing tests.

DRILL-7764: Cleanup warning messages in GuavaPatcher class

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/conv/TimeEpochBEConvertTo.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestConvertFunctions.java

An error was made when converting to BIG ENGIAN. 
First, the bytes of an integer were reversed, and only then the result was extended to long. 
Because of this, zero bytes at the beginning of long did not participate in the reverse operation

DRILL-7773: Incorrect conversion result to TIME_EPOCH_BE

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/FilterBuilder.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetFilterPushDown.java

Added null check.
NA
Added unit test for the issue.

DRILL-7774: IS NOT NULL predicate fails with NPE for the case of non-existing columns with non-deterministic expression

---

common/src/main/java/org/apache/drill/common/KerberosUtil.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/BootStrapContext.java

Refactor string comparisons to prevent comparing string object references for equality. See [here](https://errorprone.info/bugpattern/ReferenceEquality) for more details.
This instance was found using the Muse analysis platform (of which I am a developer). See other results [here](https://console.muse.dev/result/nescohen/drill/01EG1E4GWANR2JVAJQ9V9ZZ152?tab=results). Analysis of Drill has worked out of the box to deliver errorprone and infer results among other analyses. We should consider [enabling](https://github.com/marketplace/muse-dev) Muse for the project in general. This will cause Muse to leave comments on future pull requests like [this](https://github.com/TomMD/shiro/pull/2).
No user visible changes, just stability improvement
Build with `mvn install`, observe unit tests pass

DRILL-7780: Fix string reference comparisons

---

contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/readers/HiveDefaultRecordReader.java

Moved back the code which sets table / partition properties to job conf when creating readers
NA

DRILL-7785: Some hive tables fail with UndeclaredThrowableException

---

distribution/src/main/resources/drill-config.sh

The drill-config.sh has a syntax error on line 144 with the usage of "let". The command following let should be enclosed in quotes, otherwise the following syntax error occurs:
> /home/someone/proj/apache-drill-1.17.0/bin/drill-config.sh: line 144: let: lineCount=: syntax error: operand expected (error token is "=")

DRILL-7793: Fix syntax error in "drill-config.sh"

---

contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpBatchReader.java
contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpFormatPlugin.java
contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatPlugin.java
contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5BatchReader.java
contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5FormatPlugin.java
contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssBatchReader.java
contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/RowSetLoader.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/RowSetLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasySubScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/CompliantTextBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/log/LogBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/log/LogFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/PcapBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/PcapFormatPlugin.java
exec/java-exec/src/test/java/org/apache/drill/exec/metastore/TestMetastoreWithEasyFormatPlugin.java

As currently implemented, when querying a file, Drill will read the entire file even if a limit is specified in the query.  This PR does a few things:
* Refactors the `EasyGroupScan`, `EasySubScan`, and `EasyFormatConfig` to allow the option of pushing down limits.
* Applies this to all the EVF based format plugins which are: `Avro`, `LogRegex`, `PCAP`, `SPSS`, `Esri`, `Excel` and `Text (CSV)`. 
Due to JSON's fluid schema, it would be unwise to adopt the limit pushdown as it could result in very inconsistent schemata.
This capability is disabled by default, and has to be manually added to each format plugin if appropriate.
No user visible changes.  Queries with limits on large files are considerably faster.
All existing unit tests are run.

DRILL-7763: Add Limit Pushdown to File Based Storage Plugins

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpGroupScan.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpSubScan.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java

This PR fixes a minor bug in the HTTP REST storage plugin where the plugin would attempt to create the cache directory twice, causing queries to fail. This was easily fixed by disabling the cache, but now the caching works properly. 
Additionally this PR addresses [DRILL-7800](https://issues.apache.org/jira/browse/DRILL-7800) which adds a limit pushdown to the storage plugin. 
No user visible changes.
Tested caching manually.  Added unit test for limit pushdown.

DRILL-7799: REST Queries Fail if Caching is Enabled

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java

Need to update scope of drill.exec.memory.operator.output_batch_size from system to session and system
Manual tests

DRILL-7801 Changed the scope of output_batch_size option to system and session

---

dev-support/docker/Dockerfile
dev-support/docker/bashcolors.sh
dev-support/docker/drill_env_checks.sh
dev-support/docker/time.sh
docs/dev/Environment.md
start-build-env.sh

I was asked to review a change in Drill ( https://github.com/apache/drill/pull/2112 ).
When I tried to build the software it turns out that a lot of the build fails over the fact that I have Java 11 installed on my machine by default.
To "fix" this I copied/changed the Docker based build environment I initially created for Hadoop (many years ago) and recently updated for Apache Beam ( https://github.com/apache/beam/pull/13308 | [BEAM-10891](https://issues.apache.org/jira/browse/BEAM-10891) )
Because I think it makes sense to have this helper more easily available I put it in this pull request.
This is just an additional tool to make setting up the build environment for Drill a lot easier.
Only a small addition for developers who want to build the sourcecode locally.
On a "empty" (only git …

[DRILL-7803] Docker based developer build environment

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcRuleBase.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcSort.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java

- Introduced `DrillJdbcSort` to have the cost for limit queries that correspond to Drill's limit cost.
- Provided the ability to apply some JDBC rules after the logical planning phase. All other JDBC rules will be addressed in https://issues.apache.org/jira/browse/CALCITE-4423.
- Added unit tests
NA
Added unit tests for the cases that were broken earlier.

DRILL-7771: Order by and limit transactions in RDBMS cannot be pushdown

---

contrib/storage-jdbc/src/main/resources/bootstrap-storage-plugins.json

Before Drill 1.18, we used DBCP2 to manage JDBC connections, and later we replaced it with "HikariCP". However, the parameter name of HikariCP is partly different from that of DBCP, so we need to modify the bootstrap code.
https://github.com/brettwooldridge/HikariCP/tree/HikariCP-3.4.2
Create storage by the Web UI and it can be successful.

DRILL-7816: bootstrap-storage-plugins.json is an outdated example

---

_docs/install/045-distributed-mode-prerequisites.md

It's not a problem. After many tests, drill 1.18 RC can connect to ZK 3.5 cluster. If you want to connect to the old ZK cluster (< 3.5), you can follow the changed document below.
Start from Drill 1.18, ZK version is upgraded to 3.5.7. So by default, we can't connect to the old ZK cluster (< 3.5). If we need to use the previous ZK, let's do this: first, delete the zookeeper dependency files in ${DRILL_HOME}/jars/ext, then copy zookeeper-3.4.x.jar to the directory, and finally restart the cluster.
1. By default, drill cluster can be started.  (ZK 3.5)
2. After replaced the new client with zookeeper-3.4.x.jar, you can also start the drill cluster.

DRILL-7787: Apache drill failed to start

---

contrib/storage-mongo/pom.xml
exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/store/bson/BsonRecordReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/bson/TestBsonRecordReader.java

DRILL-7094: UnSupported Bson type: DECIMAL128 Mongodb 3.6 onwards
Handling the Decimal128 by converting into Double.
Now Bson Decimal128 type will be handled for the SQL queries and Show the result in double value.
(Created a Document in Mongo DB with field of Decimal128 type and executing a SQL query using Apache Drill and it return the results. Previously there was a error unsupported Bson Type.)

DRILL-7094: UnSupported Bson type: DECIMAL128 Mongodb 3.6 onwards

---

contrib/format-xml/README.md
contrib/format-xml/pom.xml
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatConfig.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatPlugin.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLMap.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
contrib/format-xml/src/main/resources/bootstrap-format-plugins.json
contrib/format-xml/src/main/resources/drill-module.conf
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
contrib/format-xml/src/test/resources/xml/attributes.xml
contrib/format-xml/src/test/resources/xml/deep-nested.xml
contrib/format-xml/src/test/resources/xml/deep-nested2.xml
contrib/format-xml/src/test/resources/xml/nested.xml
contrib/format-xml/src/test/resources/xml/really-simple-nested.xml
contrib/format-xml/src/test/resources/xml/simple.xml
contrib/format-xml/src/test/resources/xml/simple_schema.xsd
contrib/format-xml/src/test/resources/xml/very-nested.xml
contrib/native/client/src/protobuf/UserBitShared.pb.cc
contrib/native/client/src/protobuf/UserBitShared.pb.h
contrib/pom.xml
distribution/pom.xml
distribution/src/assemble/component.xml
protocol/src/main/java/org/apache/drill/exec/proto/UserBitShared.java
protocol/src/main/protobuf/UserBitShared.proto

Adds XML format plugin to Drill.
This plugin enables Drill to read XML files without defining any kind of schema.
Aside from the file extension, there is one configuration option:
* `dataLevel`: XML data often contains a considerable amount of nesting which is not necesarily useful for data analysis. This parameter allows you to set the nesting level 
where the data actually starts.  The levels start at `1`.
The default configuration is shown below:
```json
"xml": {
"type": "xml",
"extensions": [
"xml"
],
"dataLevel": 2
}
```
All fields are read as strings.  Nested fields are read as maps.  Future functionality could include support for lists.
XML is a challenging format to process as the structure does not give any hints about the schema.  For example, a JSON file might have the …

DRILL-7823 - Add XML Format Plugin

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
contrib/storage-http/README.md
contrib/storage-http/pom.xml
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
contrib/storage-http/src/test/resources/data/response.xml

This PR extends the HTTP/REST plugin to accept XML as input. This PR reuses Drill's existing XML reader.
This PR allows the REST plugin to query REST APIs which return XML data.  The REST plugin currently has an option called `inputType`.  The available options are `xml`, `json`, `csv`.   
This PR also adds an additional configuration option of `xmlDataLevel` which sets the starting nesting level for the XML data.  This helps reduce the amount of unhelpful nesting in the data.  You can view the [documentation for the XML plugin here](https://github.com/apache/drill/tree/master/contrib/format-xml).
Added additional unit test.

DRILL-7830: Add XML as Supported Format for HTTP Plugin

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java

We can catch the UserException first and inform users as clearly as possible.
TestPluginRegistry#testBadPlugin()

DRILL-7552: Add Helpful Error Message on Storage Plugin Creation/Update

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/DrillFileSystem.java

The new method `openDecompressedInputStream()` did not close the temp InputStream which caused format plugins to hang. Testing the method by itself did not reveal this, but it became apparent when this method was used in an actual format plugin.
Tested with two format plugins in development.

DRILL-7836: Format Plugins Hang with Compressed Files

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLUtils.java
contrib/format-xml/src/test/resources/xml/very-nested-with-attributes.xml
contrib/format-xml/src/test/resources/xml/weather.xml

This PR addresses two issues with the XML plugin for Drill:
1.  In cases where there were self closing tags, Drill was not reading them correctly.  This PR fixes this.
2. Attribute names were not being parsed correctly in the case of addresses with underscores.  This is reported in [DRILL-7832](https://issues.apache.org/jira/browse/DRILL-7832). 
Several new unit tests added to this PR.

DRILL-7831: Drill Fails To Read XML File with Self Closing Tags

---

docs/dev/Environment.md
pom.xml

This PR adds the OWASP Dependency-Check to the master `pom.xml` file. You can generate a report of Drill's dependencies by running the command:
```
mvn clean site
```
This does not affect the regular build process.
No user facing changes.  Developers can check whether new dependencies introduced vulnerabilities by running the above command. 
Built Drill normally and generated report using the `mvn clean site` command.

DRILL-7840: Add OWASP Dependency Report to Pom.XML

---

_docs/query-data/060-querying-the-information-schema.md

(Please replace `PR Title` with actual PR Title)

Typo Rectified

---

contrib/format-excel/pom.xml

Apache POI 5.0.0 has been released. Used by Drill for Excel support. 
No real user impact.
CI Build.

POI 5.0.0 release

---

_docs/connect-a-data-source/plugins/090-mongodb-storage-plugin.md

https://drill.apache.org/docs/mongodb-storage-plugin/#configuring-mongodb block has invalid formatting

Fix formatting on "MongoDB Storage Plugin" page

---

.github/workflows/ci.yml

Added `apt update` update repo cache before installing dependencies.
NA
NA

DRILL-7848: Github Actions fails due to outdated package repository cache

---

exec/java-exec/src/test/java/org/apache/drill/TestforBaseTestInheritance.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestStackAnalyzer.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/schema/TestDynamicSchemaFilter.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/schema/TestProjectedPath.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/schema/TestSchemaTrackerDefined.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestProjectionFilter.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestProjectedPath.java

Fixed BaseTestInheritance (now called TestforBaseTestInheritance) so that it runs during maven test. Also fixed tests that were not inherited from the BaseTest class:
```
org.apache.drill.exec.physical.impl.scan.v3.schema.TestProjectedPath,
org.apache.drill.exec.physical.impl.TestStackAnalyzer,
org.apache.drill.exec.physical.resultSet.impl.TestProjectionFilter,
org.apache.drill.exec.physical.resultSet.project.TestProjectedPath,
org.apache.drill.exec.physical.impl.scan.v3.schema.TestDynamicSchemaFilter,
org.apache.drill.exec.physical.impl.scan.v3.schema.TestSchemaTrackerDefined
```
I'm fairly certain this is N/A for this issue as it is quite small? 
Ran maven test. Confirmed that it runs and no …

DRILL-7842:Fix BaseTestInheritance test case

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/resources/rest/alertModals.ftl
exec/java-exec/src/main/resources/rest/confirmationModals.ftl
exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
exec/java-exec/src/main/resources/rest/storage/list.ftl
exec/java-exec/src/main/resources/rest/storage/update.ftl

- Added POST method for enabling/disabling storage plugins and marked the existing GET method as deprecated.
- Updated template to display a continuous error message on storage plugin configuration page, here is the screenshot with an example:
- Updated template to display a modal with an error message on plugins page:
NA
NA

DRILL-7849: Display error message when cannot enable storage plugin

---

contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataDirectory.java
contrib/format-image/src/test/java/org/apache/drill/exec/store/image/TestImageRecordReader.java
contrib/format-image/src/test/resources/image/avi.json
contrib/format-image/src/test/resources/image/bmp.json
contrib/format-image/src/test/resources/image/eps.json
contrib/format-image/src/test/resources/image/gif.json
contrib/format-image/src/test/resources/image/ico.json
contrib/format-image/src/test/resources/image/jpeg.json
contrib/format-image/src/test/resources/image/mov.json
contrib/format-image/src/test/resources/image/mp4.json
contrib/format-image/src/test/resources/image/pcx.json
contrib/format-image/src/test/resources/image/png.json
contrib/format-image/src/test/resources/image/psd.json
contrib/format-image/src/test/resources/image/tiff.json
contrib/format-image/src/test/resources/image/wav.json
contrib/format-image/src/test/resources/image/webp.json

Minor Fix: Incorrect Tag Name for Image
It's unbelievable that the tag name had been incorrect since the image plugin committed.
Ran unit tests associated with the Image plugin.

[Minor Fix] Incorrect Tag Name for Image

---

exec/java-exec/src/test/java/org/apache/drill/exec/util/StoragePluginTestUtils.java
exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java
exec/jdbc/src/test/java/org/apache/drill/jdbc/JdbcTestBase.java
exec/jdbc/src/test/java/org/apache/drill/jdbc/impl/DrillConnectionUtils.java
exec/jdbc/src/test/java/org/apache/drill/jdbc/test/TestJdbcQuery.java

Please refer to https://github.com/jpype-project/jpype/issues/913#issuecomment-767789793 for the problem description.
NA

DRILL-7850: Unable to load DrillConnectionImpl class from JDBC driver

---

exec/vector/src/main/java/org/apache/drill/exec/record/MaterializedField.java
exec/vector/src/test/java/org/apache/drill/exec/record/TestMaterializedField.java

MaterializedField had broken hashCode/equals contract:
> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.
In our case, equals are based on 2 parameters, while hashCode on 3. I updated hashCode and now it respond equals function.
`this.name.toLowerCase()` was added, because equals method compares name with ignoreCase.
Manual tests

DRILL-7812: updated hashCode function for MaterializedField

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/convert/StandardConversions.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/log/TestLogReaderIssue.java

We don't need to call the `Converter(ScalarSriter writer)` constructor again in some cases:
1. Throw `IllegalArgumentException` in `org.apache.drill.exec.physical.impl.scan.convert.ConvertXXXToXXX`
2. User get untrue error information when the above problems happen.
1. Ran unit tests associated with the Log plugin.
2. add the `TestLogReaderIssue`

DRILL-7853: NoSuchMethodException when DateTime format is not valid

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/schema/MongoSchemaFactory.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestConstants.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoDrillIssue.java

Mongo database name in capital letters is now supported.
Used a map to support both schema lookup and `MongoScanSpec` definition.
1. Schemas in Drill are case insensitive and stored in lower case, See also `SchemaUtilites#searchSchemaTree()`.
2. Must be using origin database name(non-toLowerCase) to create `MongoScanSpec`.
1. Ran unit tests associated with the Mongo plugin.
2. Add the `TestMongoDrillIssue`.
3. Manual test in real world(Done).

DRILL-7820: Not Supporting Mongo DB Name Capital Letters

---

contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java

Since the use of `@Ignore` does not prevent the test failure(unless all are ignored), so increase the time to ready more Splunk events.
1. Ran unit tests associated with the Splunk plugin.
2. Ran CI more than 6 times without failure(Done).

DRILL-7859: Junit test random failure when the numbers of splunk event was insufficient

---

contrib/format-excel/pom.xml

excel-streaming-reader v3.0.3 adds support for Strict OOXML format and some bug fixes
No changes expected
CI build

DRILL-7862: upgrade excel-streaming-reader

---

contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java

Due to the 3 seconds was no guarantee that Splunk's Junit test will 100% pass, So increase to 10 sec.
N/A
N/A

Minor Fix: Increase the Splunk ready time to 10 sec

---

contrib/udfs/README.md
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaFunctions.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaUtils.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestComplexSchemaFunctions.java
contrib/udfs/src/test/resources/json/nestedSchema.json

This function allows you to drill down into the schema of maps.  The REST API and JDBC interfaces will only return `MAP`, `LIST` for the MAP, however, it is not possible to get 
the schema of the inner map. The function `getMapSchema(<MAP>)` will return a `MAP` of the fields and datatypes.
Using the data below, the query below will return the schema as shown below.
```bash
apache drill> SELECT getMapSchema(record) AS schema FROM dfs.test.`schema_test.json`;
+----------------------------------------------------------------------------------+
|                                      schema                                      |
+----------------------------------------------------------------- …
```

DRILL-7861: Add Function to Obtain Inner Map Schemata

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushLimitToScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java

Fixed NPE when applying DrillPushLimitToScanRule rule.
NA
Checked manually. No test is added, since NPE is logged only and limit is pushed down at another stage.

DRILL-7865: Unable to apply DrillPushLimitToScanRule due to NPE

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java

This is not helpful message on Web UI when failure to decode plugin json :
```
"Invalid JSON"
```
The PR provide a  user-friendly message in some case :
Case 1 : Missing the required property
```
Please retry: Invalid JSON: missing type id property 'type' at [Source: (String)"{ "driver": "xxx.Driver", "url": "jdbc:xxx:xxx", "enabled": false }"; line: 7, column: 1]
```
Case 2: Not supported the plugin name
```
Please retry: Invalid JSON: known type ids = [InfoSchemaConfig, MockBreakageStorage$MockBreakageStorageEngineConfig, SystemTablePluginConfig, file, mock] at [Source: (String)"{ "type": "ozone", "enabled": false }"; line: 2, column: 11]
```
Case 3: Unknow the parameters
```
Please retry: Invalid JSON: Unrecognized field "test"
```
N/A
1. Manual test on Web UI

DRILL-7866: Provide a helpful message when failure to decode plugin json

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/resolver/TypeCastRules.java

Please see the ticket for details
Yes
Removed implementation of function with required arguments and nullable one was used.

DRILL-7867: Allow using required arguments for functions with nullable parameters

---

exec/jdbc-all/pom.xml

Exclude io.netty:netty-transport-native-epoll:* and io.netty:netty-transport-native-unix-common:* from shade plugin in drill-jdbc-all to avoid some build warnings
N/A
Relevant errors not present in build, change does not cause additional Maven tests to fail

DRILL-7841: Need to exclude or shade netty lib to avoid [WARNING]

---

exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/JsonReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/vector/complex/writer/TestJsonReader.java

Added try-catch to handleString() in JsonReader to allow empty string "" to be parsed as empty object {} when object type is inferred from earlier keys, as discussed with @cgivre 
Drill can now handle the scenario described without the use of `exec.enable.union.type=true`, perhaps user documentation should be updated to mention the limitation occurring when "" appears before {}, either a dummy entry must be added to the start of the JSON (so that the correct types are inferred) or the union type must be used
Queried sample JSON files to verify new behavior, Maven tests
Edit: Added additional JUnit tests that trigger the new behavior

DRILL-7821: Treat Empty String as NULL in JSON Reader

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/DrillFSDataInputStream.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/DrillFileSystem.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/decoder/Packet.java

Documentation for the `InputStream.read(byte b[], int off, int len)` method doesn't guarantee that all requested (if available) bytes will be stored in the byte array, so some implementations indeed populate byte array only with partial data.
It causes issues for storage plugins that manipulate with byte arrays obtained from the stream by this way, for example, the PCAP plugin when files are stored at s3.
This PR updates the `DrillFSDataInputStream.read` method to ensure that all requested bytes were stored in the byte array to have the same behavior regardless of the `InputStream` implementation.
NA
Checked manually, no unit tests provided because currently it is reproduced with s3 only.

DRILL-7874: Ensure DrillFSDataInputStream.read populates byte array of the requested length

---

contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpBatchReader.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java

This PR addresses:
* https://issues.apache.org/jira/browse/DRILL-7875
DRILL-7875 adds a `null` check in the Splunk reader.  In the event that there is a Splunk index with no timestamp field, this will cause Drill to receive several `null` columns.  This rectifies that problem.
Manual testing and existing unit tests.

DRILL-7875: Drill Fails to Splunk Indexes with no Timestamp

---

exec/java-exec/src/test/java/org/apache/drill/exec/coord/zk/TestEphemeralStore.java
pom.xml

Updated unit test so that it utilizes MappingListenerManager instead of ListenerContainer from Apache Curator which was deprecated in version 5.1.0. Curator v5.1.0 fixes NPE errors in testing phase (also described in DRILL-7843(https://issues.apache.org/jira/browse/DRILL-7843).
In order for users to use previous versions of apache zookeeper, they would need to replace the jars of zookeeper and curator.
Checked mvn test and the errors that were described are no longer there. 
`[INFO] Running org.apache.drill.exec.coord.zk.TestZookeeperClient
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.224 s - in org.apache.drill.exec.coord.zk.TestZookeeperClient
[INFO] Running org.apache.drill.exec.coord.zk.TestEphemeralStore
[INFO] Tests run: 2, Failures: 0, Errors: 0, …

DRILL-7712: Fix issues after ZK upgrade

---

common/src/main/java/org/apache/drill/common/collections/MapWithOrdinal.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/DeadBuf.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/UserClientConnection.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/UserServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/BaseWebUserConnection.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRestServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebSessionResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebUserConnection.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/Foreman.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/prepare/PreparedStatementProvider.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/RestServerTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/WebSessionResourcesTest.java
exec/jdbc-all/pom.xml
exec/memory/base/src/main/java/io/netty/buffer/DrillBuf.java
exec/memory/base/src/main/java/io/netty/buffer/MutableWrappedByteBuf.java
exec/memory/base/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java
exec/memory/base/src/main/java/io/netty/buffer/UnsafeDirectLittleEndian.java
exec/memory/base/src/main/java/org/apache/drill/exec/memory/DrillByteBufAllocator.java
pom.xml

`Netty` of version `4.0.48.Final` has vulnerabilities as CVE-2019-16869, CVE-2014-3488 and other. I want to update to the last available, stable version of `Netty` `4.1.59.Final`.
`ChannelPromise` and `ChannelFuture` were replaced with `DefaultPromise` and `Future` according. It was done in response to changes in https://github.com/netty/netty/commit/1740f366eb728ea5a0a63d18e9042161673414cd . `ChannelPromise` and `ChannelFuture` are wrong used and netty's changes are predict it.
Other one breaking `Netty` change is https://github.com/netty/netty/commit/39cc7a673939dec96258ff27f5b1874671838af0 . In Drill we have `ByteBuffAlocater` which doesn't support heap buffers. But in the netty's commit was changed internal behavior in `SslHandler`. Previously, regardless to chosen ssl engine, were …

DRILL-7790 : Build Drill with Netty version 4.1.59.Final

---

contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5BatchReader.java
contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5DrillMetadata.java
contrib/format-hdf5/src/test/java/org/apache/drill/exec/store/hdf5/TestHDF5Format.java

This minor PR fixes a few minor issues with the HDF5 reader.   The reader was not following links properly.  Additionally, if the preview was a 2D array (or greater) the preview was using the incorrect dimensions and throwing NPEs. 
Manually Tested with client provided large test files.

DRILL-7885: HDF5 Plugin not resolving links

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcRecordReader.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java
contrib/storage-jdbc/src/test/resources/mysql-test-data.sql

Made changes to return DRILL_REL_DATATYPE_SYSTEM.getMaxNumericScale() and DRILL_REL_DATATYPE_SYSTEM.getMaxNumericPrecision() for the case when JDBC calculated presision is greater to avoid errors in Drill.
Also, added a check for actual value scale and precision to avoid returning incorrect values. 
NA
Added unit test to check the desired behavior.

DRILL-7887: JDBC plugin returns incorrect precision for SUM(DECIMAL) queries

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/stream/StreamingHttpConnection.java
exec/java-exec/src/main/resources/drill-module.conf
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestRestJson.java
exec/java-exec/src/test/resources/rest/exception.json
exec/java-exec/src/test/resources/rest/verboseExc.json

Updated StreamingHttpConnection.java to return query id and failed state instead of the incorrect message as stated in the Jira ticket.
Examples of the requests and responses:
Request:
```
{
"query": "SELECT * FROM cp.`employee123321123321.json` LIMIT 20",
"queryType": "SQL"
}
```
Response:
```
{
"queryId": "1fa0acc2-e507-6688-69fe-02fc627c8c47",
"queryState": "FAILED"
}
```
Please note, to preserve backward compatibility, default response has such a form, so now it is possible to obtain additional error info from the query profile.
To provide error details right in the response, the `exec.errors.verbose` option should be set in the following way:
```
{
"query": "SELECT * FROM cp.`employee123321123321.json` LIMIT 20",
"queryType": "SQL",
"options": {
"drill.exec.http.rest.errors.verbose": …
```

DRILL-7888: query.json returns an incorrect error message when the query fails

---

contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidPushDownFilterForScan.java
contrib/storage-mongo/pom.xml
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoPushDownFilterForScan.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePlugin.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoSubScan.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestConstants.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoLimitPushDown.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillScanRelBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/ScanPrel.java

This PR adds a limit pushdown capability to the MongoDB storage plugin. 
No user visible changes
Added new class of unit tests for the pushdown.

DRILL-7814: Add Limit Pushdown to MongoDB Storage Plugin

---

contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5BatchReader.java

This PR fixes a minor issue with Drill's HDF5 reader.  The jhdf5 reader does not support large b-trees in attributes.  This PR adds a try/catch block around the `getAttributes()` function.
Tested with client supplied file.

DRILL-7894: Large Attributes Crash HDF5 Reader

---

_docs/developer-information/contribute-to-drill/020-apache-drill-contribution-ideas.md

This is a doc update for apache-drill-contribution-ideas.md, No JIRA issue filed here
All the idea which has been resolved or the idea which is out-of-date, has been removed from apache-drill-contribution-ideas.md
- Sequence: resolved, reference to (<https://drill.apache.org/docs/sequence-files>)  
- RC: out-of-date, this data type is rarely used, could remove from future plan.
- Protobuf: resolved, reference to (<https://drill.apache.org/apidocs/org/apache/drill/exec/proto/UserProtos.GetServerMetaResp.html>)  
- XML: resolved in v1.19, but not release yet, so still keep in here, reference to   
(<https://issues.apache.org/jira/browse/DRILL-7823>)
- Thrift: resolved, reference to (<https://issues.apache.org/jira/browse/DRILL-1>)
- Enhancements to REST APIs: resolved, reference to …

[DOC-UPDATE] apache-drill-contribution-ideas.md update

---

pom.xml

Resolves an issue here (https://github.com/advisories/GHSA-763g-fqq7-48wg). 
Ran all unit tests locally.  Got random failure.  Re ran tests without changes, and all passed.

DRILL-7899: Bump checkstyle from 8.16 to 8.29 

---

pom.xml

Bumps [libthrift](https://github.com/apache/thrift) from 0.13.0 to 0.14.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/apache/thrift/releases">libthrift's releases</a>.</em></p>
<blockquote>
<h2>Version 0.14.0</h2>
<p>For release 0.14.0 head over to the official release download source:
<a href="http://thrift.apache.org/download">http://thrift.apache.org/download</a></p>
<p>The assets below are added by Github based on the release tag and they may therefore not match the checkums.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/apache/thrift/blob/master/CHANGES.md">libthrift's changelog</a>.</em></p>
<blockquote>
<h2>0.14.0</h2>
<h3>Deprecated Languages</h3>
<ul>
<li><a …

DRILL-7900: Bump libthrift from 0.13.0 to 0.14.0

---

.github/workflows/ci.yml

Update GitHub actions to V2, change `zulu` jdk with `adopt`. Change memory properties to: `-DdirectMemoryMb=4500` `-DmemoryMb=1500`.
NA
Build was performed several times. The reviewer can perform the build again to check the build pass successfully.

DRILL-7908: Fix GitHub Actions CI

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/UserClientConnection.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/FilterPushDownStrategy.java
pom.xml
tools/drill-patch-review.py
tools/fmpp/pom.xml

This fix addresses CVE-2021-29425.
In Apache Commons IO before 2.7, When invoking the method FileNameUtils.normalize with an improper input string, like `"//../foo"`, or `"\..\foo"`, the result would be the same value, thus possibly providing access to files in the parent directory, but not further above (thus "limited" path traversal), if the calling code would use the result to construct a path value.
Simple solution is to update the library.
N/A

DRILL-7910: Bumps commons-io from 2.4 to 2.7

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/ComplexToJsonPrelVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/ExcessiveExchangeIdentifier.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/FinalColumnReorderer.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/InsertLocalExchangeVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/LateralUnnestRowIDVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/RewriteProjectToFlatten.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/RuntimeFilterVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SelectionVectorPrelVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SplitUpComplexExpressions.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DefaultSqlHandler.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetFilterPushDown.java

Updated visitors applied after optimizations to prevent creating unnecessary copies that will lose actual row type.
Added a call to create a top project after all optimizations to ensure that column names will match the name from row type.
NA

DRILL-7893: Column alias is not working for a parquet file

---

contrib/format-excel/README.md
contrib/format-excel/pom.xml
contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java

Currently, there was no way to determine what sheets are available in a given Excel file.  This minor PR adds a new implicit metadata field called `_sheets` which a user can use to determine what sheets are available.  By definition, Excel files must have at least one sheet.
Additionally, I updated the streaming reader to the latest version.
Updated `README` to reflect the additional field, but to determine the available sheets, a user could execute the query below:
```sql
SELECT FLATTEN(_sheets) AS sheetNames 
FROM <Excel File>
```
Added additional unit test.

 DRILL-7912: Add Sheet Names to Excel Reader

---

contrib/storage-kudu/pom.xml
contrib/storage-kudu/src/main/java/org/apache/drill/exec/store/kudu/KuduRecordReader.java
pom.xml

This PR updates several dependencies to address outstanding CVEs.
The updates are:
* Kudu from version 1.3 to 1.7
* Avatica from version 1.15 to 1.17
* HBase from 2.2.2 to 2.4.2
N/A

DRILL-7918: Dependency Updates for CVE

---

exec/java-exec/src/main/resources/rest/query/query.ftl
exec/java-exec/src/main/resources/rest/runningQuery.ftl
exec/java-exec/src/main/resources/rest/static/js/querySubmission.js

1. Reduce the text of `Loading dialog` (optimize the layout).
2. Add `Reset` button for quickly reset the Long-SQL-Text.
N/A

[Minor Update] Add reset button and reduce the dialog text

---

pom.xml

It seems 2500Mb is not enough on Linux ARM64
Fixes errors like:
```
[ERROR] Tests run: 19, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.039 s <<< FAILURE! - in org.apache.drill.exec.record.vector.TestValueVector
[ERROR] org.apache.drill.exec.record.vector.TestValueVector.testFixedVectorReallocation  Time elapsed: 0.037 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<org.apache.drill.exec.exception.OversizedAllocationException> but was<org.apache.drill.exec.exception.OutOfMemoryException>
at org.apache.drill.exec.record.vector.TestValueVector.testFixedVectorReallocation(TestValueVector.java:107)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2147483644 byte(s) of direct memory (used: 872415232, max: 2621440000)
at …
```

DRILL-7911 Increase the max direct memory

---

contrib/storage-splunk/pom.xml

Disable running the unit tests for Contrib Storage Splunk for Linux ARM64 because there is no Docker image for splunk/splunk
No user visible changes. Only the unit tests are disabled for Contrib Storage Splunk module because there is no Docker image for `splunk/splunk` for Linux/arm64
`mvn test` now passes for Contrib Storage Splunk module because the tests are skipped.

DRILL-7911 Disable maven-surefire-plugin for Splunk for ARM Build

---

_docs/developer-information/contribute-to-drill/010-apache-drill-contribution-guidelines.md

Update Oracle links with their newer paths

[DOCUMENTATION] Use HTTPS for all external links in Contribution Guidelines page

---

.github/workflows/ci.yml

For example : 
```
Downloading from jhdf5-repo: https://maven.scijava.org/content/repositories/public/org/apache/hbase/hbase-annotations/2.2.2/hbase-annotations-2.2.2.jar
Downloading from jhdf5-repo: https://maven.scijava.org/content/repositories/public/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar
Downloading from jhdf5-repo: https://maven.scijava.org/content/repositories/public/org/jruby/jcodings/jcodings/1.0.8/jcodings-1.0.8.jar
Downloading from jhdf5-repo: https://maven.scijava.org/content/repositories/public/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar
Progress (1): 4.1/187 kB
Progress (1): 7.7/187 kB
Progress (2): 7.7/187 kB | 0/1.3 MB
Progress (3): 7.7/187 kB | 0/1.3 MB | 4.1/6.8 kB
Progress (3): 7.7/187 kB | 0/1.3 MB | 6.8 kB    
Progress (4): 7.7/187 …
```

DRILL-7860: Suppress the transfer progress when downloading in CI maven build

---

_docs/developer-information/contribute-to-drill/010-apache-drill-contribution-guidelines.md

Extend https://drill.apache.org/docs/apache-drill-contribution-guidelines/ with a paragraph about CI at Github Actions and TravisCI
Extend https://drill.apache.org/docs/apache-drill-contribution-guidelines/ with a paragraph about CI at Github Actions and TravisCI
N/A
Depends on https://github.com/apache/drill/pull/2220

DRILL-7923 Add a paragraph to Contribution Guidelines page about CI

---

.asf.yaml
_config.yml

As requested by Apache Infra team with https://lists.apache.org/thread.html/r8d023c0f5afefca7f6ce4e26d02404762bd6234fbe328011e1564249%40%3Cusers.infra.apache.org%3E
N/A
N/A

DRILL-7925 Use .asf.yaml for the website

---

contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaFilterPushdownTest.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaTestBase.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java

Replaced deprecated `PlanTestBase` with `ClusterTest` and updated tests
NA
Checked that tests pass.

DRILL-7929: Update Kafka unit tests to use ClusterTest

---

.travis.yml
pom.xml

As discussed at https://lists.apache.org/thread.html/r6af8d66c10e36c9610fb28db2f29aba650e66b9bae5eafc7d7183000%40%3Cdev.drill.apache.org%3E TravisCI could be re-introduced for building and testing Drill on Linux ARM64.
The content of .travis.yml is copied from tag drill-1.17.0 and modified slightly to build on Linux ARM64 at AWS Graviton2 build nodes.
This PR depends on https://github.com/apache/drill/pull/2217, https://github.com/apache/drill/pull/2218 and https://github.com/apache/drill/pull/2219. The build will fail before those are merged. 
The documentation at the website could be updated to mention that all PRs are automatically tested on Linux ARM64 at TravisCI.
This PR introduces additional testing on Linux ARM64 hardware at TravisCI.

DRILL-7923 Use TravisCI for building and testing on Linux ARM64

---

contrib/storage-cassandra/pom.xml
contrib/storage-jdbc/pom.xml
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java
contrib/storage-jdbc/src/test/resources/mysql_config_override/mysql_override.cnf
contrib/storage-mongo/pom.xml
contrib/storage-splunk/pom.xml
exec/java-exec/pom.xml
pom.xml

Apache Drill build fails on Linux ARM64 because Wix Embedded MySQL does not support ARM64 and this library is no more maintained.
This PR replaces Wix Embedded MySQL with TestContainers-MySQL. In addition the PR sets Maven dependency management for JNA and Netty which support Linux ARM64.
There are no user visible changes. The changes are only in the tests.
org.apache.drill.exec.store.jdbc.TestJdbcPluginWithMySQLIT has been updated to use TestContainers to run MySQL/MariaDB.

DRILL-7911 Use TestContainers-MySQL instead of wix-embedded-mysql

---

contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaFunctions.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaUtils.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/UserAgentFunctions.java
exec/java-exec/src/main/codegen/templates/CastIntervalVarChar.java
exec/java-exec/src/main/codegen/templates/Decimal/CastDecimalVarDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/CastDecimalVarchar.java
exec/java-exec/src/main/codegen/templates/Decimal/CastFloatDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/CastIntDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/CastVarCharDecimal.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions1.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions2.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions3.java
exec/java-exec/src/main/codegen/templates/Decimal/DecimalFunctions.java
exec/java-exec/src/main/codegen/templates/NewValueFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/ParseQueryFunction.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/ParseUrlFunction.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StatisticsAggrFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/TDigestFunctions.java
exec/java-exec/src/test/java/org/apache/drill/TestBugFixes.java

Certain overloads of the **concat** function do not override the current working buffer when calling **reallocIfNeeded**. Because of this, repeated calls to **reallocIfNeeded** on this buffer could lead to an error **Tried to remove unmanaged buffer**
TestBugFixes#testDRILL6547 has been added

DRILL-6547: IllegalStateException: Tried to remove unmanaged buffer in concat function

---

.github/workflows/ci.yml

Fix Github memory issues
It should be draft PR until the build will be contentiously green
This draft PR is aimed to run GitHub actions and fix the issues

DRILL-7930: Fix GitHub actions

---

contrib/storage-http/pom.xml

Update OkHTTP to version 4.9.1.
Existing unit tests pass.

DRILL-7933: Update OkHTTP to Version 4.9.1

---

docs/dev/UpgradeGuava.md
exec/jdbc-all/pom.xml
pom.xml

* Update guava version to the newest one (30.1.1-jre)
* Drop <shaded.guava.version> at all
NA
@vvysotskyi Since the original Guava shade was performed by you please advice what is needed to be tested before merging?

DRILL-7904: Update to 30-jre Guava version

---

drill-yarn/src/main/java/org/apache/drill/yarn/appMaster/http/WebServer.java
exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/DrillUserPrincipal.java
pom.xml

Jetty 9.3 is not a supported version anymore and doesn't get any
security fixes.
Update Jetty version used by Drill to the latest 9.4 version (9.4.41). This also requires updating to Hadoop 3.2.2, which is also based on Jetty 9.4.x.
N/A
N/A

DRILL-7135: Update to Jetty 9.4

---

common/src/main/java/org/apache/drill/common/util/DrillFileUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionImplementationRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/CreateFunctionHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/StorageStrategyTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/util/FileSystemUtilTestBase.java
exec/java-exec/src/test/java/org/apache/drill/test/BaseFixture.java

Guava's `Files#createTempDir()` method has some security issues, and since better alternatives exist (including Java 7 `Files#createTempDirectory(String)` method), the function has been deprecated in Guava 30.0 (but the security issues haven't been addressed).
Introduce a drop-in replacement for this method in `DrillFileUtils` based on the Java7 Files API and replace usage of the Guava method with the new method in the codebase.
N/A
Unit tests run locally

DRILL-7936: Remove usage of Guava Files#createTempDir method

---

contrib/storage-kafka/pom.xml
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaRecordReader.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaScanBatchCreator.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/MetaDataField.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/AvroMessageReader.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/JsonMessageReader.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/KafkaJsonLoader.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/MessageReader.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaMessageGenerator.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaTestBase.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestKafkaSuit.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureOptions.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureParser.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/TokenIterator.java
exec/jdbc-all/pom.xml
pom.xml

- Refactored `KafkaRecordReader` to use EVF.
- Updated `JsonMessageReader` to use V2 JSON reader
- Added `AvroMessageReader` for processing messages serialized as Avro records and added schema registry support.
To be able to deserialize Kafka messages of Avro type, schema registry URL should be specified in the Kafka storage plugin `kafkaConsumerProps` (and other schema registry options if required):
``` 
"schema.registry.url": "http://localhost:8081"
```
After that, `store.kafka.record.reader` session option should be set to `org.apache.drill.exec.store.kafka.decoders.AvroMessageReader`.
NA
Added UT that reads Avro messages.

DRILL-5940: Add support for Avro messages with schema registry for Kafka

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java

Add the fourth parameter in split_part udf as end index: suport split_part('a,b,c,d', ',' , 1, 2) = 'a,b'
Return all remaining string if end indx is greater then splitted string length
string split_part(string input, string delimiter, bigint start, bigint end)
user doc updated in [PR](https://github.com/apache/drill/pull/2229)
New test added in org.apache.drill.exec.expr.fn.impl.TestStringFunctions.testSplitPartStartEnd

DRILL-7928: Add fourth parameter for split_part udf

---

contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/AvroMessageReader.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaMessageGenerator.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java

When using drill 1.19.0-snapshot to query kafka avro message, if kafka key data is avro, drill can not return key data right.
Now add a new method `AvroMessageReader.getKeyValue` to identify the actual type and data of key. It now cast avro key to string with json type.
No.
set `key.deserializer` in `KafkaQueriesTest.testAvroResultCount` test case class

DRILL-7940: Fix Kafka key with avro schema can not displayed correctly

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java

Fixed number of records to read for the case of dictionary encoding to avoid IOBE error when reaching the end of the buffer.
NA
Checked manually, no unit test is provided since it is reproduced on large data files only.

DRILL-7937: INTERNAL_ERROR when querying Parquet File with decimals

---

tools/release-scripts/release.sh

Small fixes for the release tool:
- fix path used to invoke the checksum verification script
- Allow gpg command to be configurable and default to gpg instead ofgpg2 (same as what is mentioned in release documentation).
N/A
Local testing

Release tools fix

---

common/src/main/java/org/apache/drill/common/util/GuavaPatcher.java
common/src/test/java/org/apache/drill/common/util/TestGuavaPatcher.java
src/main/resources/checkstyle-config.xml

In order to support Apache Iceberg, GuavaPatcher adds several methods to
com.google.common.base.Preconditions required by Apache Iceberg runtime
but not available in Guava 18.
When Guava version was updated to 30.1.1, Guava Patcher tries to update
existing methods with some code referencing package protected methods
which do no exist anymore. Patching fails but as the methods do now
exists, there's no compatibility issue. That said, GuavaPatcher emits
some logging which might confuse end user.
Remove the unnecessary patching of the Preconditions class and also add
some unit test designed to fail if patching fails for any reason.
N/A
Unit tests

DRILL-7945: Stop patching newly added Guava methods

---

pom.xml

CVE-2020-13956
Vulnerable versions: < 4.5.13
Patched version: 4.5.13
Apache HttpClient versions prior to version 4.5.13 and 5.0.3 can misinterpret malformed authority component in request URIs passed to the library as java.net.URI object and pick the wrong target host for request execution.
N/A
Waiting for the unit tests passed.

DRILL-7946: Bump HttpClient from 4.5.12 to 4.5.13 for CVE-2020-13956

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroColumnConverterFactory.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetTableMetadataUtils.java
exec/vector/src/main/java/org/apache/drill/exec/util/DecimalUtility.java

Enforced returning `BigInteger.ZERO` for the case when empty byte array is used to create `BigInteger`.
NA

DRILL-7947: Unable to aggregate or filter nullable decimals in large record sets

---

pom.xml

Update Mockito to 3.11.0 (latest version at the moment).
This will make it easier to build Drill with newer JDKs.
No need of documentation changes.
The test suite has been executed.

DRILL-7942 Update Mockito to latest 3.x

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java

Fixes a typo.
When opening an XML file fails, the error message now says "Failed to open input file" instead of "Failed to open open input file".
Untested.

Fix typo in XMLBatchReader: "Failed to open ~open~ input file"

---

contrib/storage-cassandra/pom.xml
contrib/storage-elasticsearch/pom.xml

```
mvn dependency:tree -Dincludes=org.apache.calcite.avatica:avatica* -pl contrib/storage-cassandra,contrib/storage-elasticsearch
[INFO] ----------< org.apache.drill.contrib:drill-storage-cassandra >----------
[INFO] Building Drill : Contrib : Storage : Cassandra 1.19.0              [1/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ drill-storage-cassandra ---
[INFO] org.apache.drill.contrib:drill-storage-cassandra:jar:1.19.0
[INFO] +- org.apache.drill.exec:drill-java-exec:jar:1.19.0:compile
[INFO] |  \- org.apache.calcite.avatica:avatica:jar:1.17.0:compile
[INFO] \- com.github.vvysotskyi.drill-calcite:calcite-cassandra:jar:1.21.0-drill-r2:compile
[INFO]    \- …
```

DRILL-7950: Drill classpath includes both avatica-core:jar:1.15.0 and avatica:jar:1.17.0

---

_docs/connect-a-data-source/036-configuring-storage-plugins.md

Update two dead links to live links:  
`/docs/starting-the-web-console/` to `/docs/starting-the-web-ui/`;  
`/docs/configuring-web-console-and-rest-api-security` to `/docs/configuring-web-ui-and-rest-api-security/`
This is a doc update, no doc related
This is a doc update, no test related

[DOC UPDATE] Update dead links

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java

Mongo provides a much cheaper method for getting an estimated row count, the current implementation issues an expensive aggregate query that gets an accurate row count, but mongo DB is very slow to execute this on large collections.
No doc change, just an internal perf improvement.
So far just a manual test.

DRILL-5177: Use much cheaper estimated record count when determining stats for a mongo scan

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java

Updates ScanStats in Mongo Group Scan to reflect the estimated row count instead of the exact count.
Ran existing unit tests

DRILL-7952: Fix Scan Stats for Mongo Plugin

---

_docs/query-data/query-a-file-system/040-querying-directories.md

Documented Wildcard Matching function with example.
Documented in:  
https://drill.apache.org/docs/querying-directories/
UT reference to:
https://github.com/apache/drill/blob/4aefcef2b665c5737471664912a26ef6ed9a6cfc/exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestGlob.java

[DOC UPDATE] Wildcard Matching Documentation

---

_docs/en/getting-started/010-drill-introduction.md
_docs/zh/010-getting-started.md
_docs/zh/getting-started/010-drill-introduction.md
_docs/zh/getting-started/020-why-drill.md

1. The website docs is here [Getting Started](http://drill.apache.org/docs/drill-introduction/)
2. The reference docs on the `gh-pages` branch [getting-started](https://github.com/apache/drill/tree/gh-pages/_docs/en/getting-started)
3. The `Multilingual Support` is powered by @dzamo (James Turton), thanks.
1. The outline of translate are :
2. No need to translate the old information before the 1.19 in the release log.
N/A

[DOC UPDATE] Getting Started support the zh-CN

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/storage-http/README.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ImplicitColumnUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java

In many http calls, the response code can contain meaningful information, however these fields are not available unless the call results in an error.
This PR adds four implicit metadata fields to the HTTP storage plugin which are:
* `_response_code`: The HTTP response code. This field is returned as an INT.
* `_response_message`: The response message.
* `_response_protocol`: The response protocol.
* `_response_url`: The actual URL that is sent to the API.
As these are implicit fields, they will not appear in star queries.
See above.
Added three additional unit tests.

DRILL-7951: Add Response Metadata Fields to HTTP Storage Plugin

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillReduceAggregatesRule.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java

With stddev and sum for the same column c, stddev will be convert to sum(c) as $1, sum(c*c)  as $2, count() as $3, sum will be convert to $sum0(c) as $4 with return type "bigint not null". In the next iteration, $1 will be converted to $sum0(c) with return type "nullable bigint". In the equals method of AggregateCall.java, the return type is not included, so $4 will be considered already exist in aggCallMapping and return $sum0(c) with return type "nullable bigint" which causes the exception.
NA
org.apache.drill.exec.fn.impl.TestAggregateFunctions.testRowTypeMissMatch

DRILL-7931: Rowtype mismatch in DrillReduceAggregatesRule

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/pojo/PojoWriters.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java

This commit adds support for java.lang.Float to PojoWriters.java and a
test for the problem described in DRILL-7968 to TestMetastoreCommands.java.
For tables with fewer than ~200 rows and a FLOAT4 column there is no bug: the ANALYZE command succeeds and, indeed, this case is exercised by tests in TestMetastoreCommands.java and alltypes_{required,optional}.parquet which both contain a FLOAT4 column.
But for tables with more than ~200 rows and a FLOAT4 column the ANALYZE command fails with
```
SQL Error: EXECUTION_ERROR ERROR: PojoRecordReader doesn't yet support conversions from the type [class java.lang.Float].
Failed to setup reader: DynamicPojoRecordReader
```
E.g. you can reproduce the above with
```sql
create table dfs.tmp.test_analyze as
select cast(1 as float) from …
```

DRILL-7968: ANALYZE TABLE ... REFRESH METADATA fails with FLOAT4 column.

---

pom.xml

Cherry-picked required commits for adding support of Elasticsearch authentication and updated version of the fork in Drill (https://issues.apache.org/jira/browse/CALCITE-4180)
NA

DRILL-7971: Support Elasticsearch authentication

---

_docs/en/tutorials/010-tutorials-introduction.md
_docs/zh/030-tutorials.md
_docs/zh/tutorials/010-tutorials-introduction.md
_docs/zh/tutorials/020-drill-in-10-minutes.md
_docs/zh/tutorials/030-analyzing-the-yelp-academic-dataset.md
_docs/zh/tutorials/040-learn-drill-with-the-mapr-sandbox.md
_docs/zh/tutorials/050-analyzing-highly-dynamic-datasets.md
_docs/zh/tutorials/060-analyzing-social-media.md
_docs/zh/tutorials/070-analyzing-data-using-window-functions.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/005-about-the-mapr-sandbox.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/010-installing-the-apache-drill-sandbox.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/020-getting-to-know-the-drill-sandbox.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/030-lesson-1-learn-about-the-data-set.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/040-lesson-2-run-queries-with-ansi-sql.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/050-lesson-3-run-queries-on-complex-data-types.md
_docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/060-summary.md

* 010-tutorials-introduction.md
* 020-drill-in-10-minutes.md
Overall 14 tutorials, other 12 tutorials just changed zh title for local build process and doesn't translate yet.
Please refer to Chinese version 010-tutorials-introduction.md and 020-drill-in-10-minutes.md
This is a doc update, no test here.

[DOC UPDATE]  Translate Tutorial to Chinese 2/14

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
exec/java-exec/src/main/resources/rest/profile/list.ftl

Usage scenario:
Analysis the profile json exported from other clusters(ex. user's cluster). The original profile json is not readable (time type is epoch time), so it will be better to view it in the detailed profile web console.
To upload the profile json file(need to be the same format as the json profile exported from the detailed profile web console) and view it on the web console:
- click import button on the Profiles tab of Web-UI
- select the profile file you want to view
- the profile will be displayed as nomal query profile
NA

DRILL-7922: Add feature of viewing external profile in web UI

---

contrib/storage-cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CalciteUtils.java
contrib/storage-elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/CalciteUtils.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcIntermediatePrelConverterRule.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithH2IT.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/EnumerableIntermediatePrelConverterRule.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/EnumPluginTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockPlugin.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockRel.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockSchema.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockTable.java
exec/java-exec/src/test/resources/drill-module.conf

Updated `JdbcIntermediatePrelConverterRule` and `EnumerableIntermediatePrelConverterRule` to consider the convention of the input rel node when applying the rule, so now `EnumerableIntermediatePrelConverterRule` cannot be applied to `VertexDrel` rel node that has input with JDBC convention and vise versa.
Improved `FragmentContextImpl` to allow returning full root schema for both root and non-root fragments, since schema may be used when reading "enumerable" plugins.
NA
Checked manually, no unit test added since the issue may be reproduced only with two different storage plugins.

DRILL-7972: ClassCastException when joining RDBMS and Elasticsearch tables

---

.editorconfig

Non-code change.
EditorConfig (https://editorconfig.org/) is an editor-neutral file format
that holds code style settings.  This particular config has been defined
to reflect the style convetions in the Drill codebase (most significantly,
indentation is with 2 spaces).  Many mainstream editors and IDEs will
recognise this file and set themselves up accordingly, making it easier to
contribute code following the project's conventions.  Editors that do not
understand EditorConfig are unaffected.
Note that .editorconfig only contains global conventions for the codebase, not
individual users' editor preferences, which must be masked by .gitignore.
Other Apache projects with a .editorconfig file in their code repo are
Superset, Subversion, Thrift, Submarine and presumably some more.

[MINOR UPDATE]: Add an .editorconfig file providing style hints to editors and IDEs

---

exec/jdbc-all/pom.xml
pom.xml

When reading a specially crafted ZIP archive, Compress can be made to allocate large amounts of memory that finally leads to an out of memory error even for very small inputs. This could be used to mount a denial of service attack against services that use Compress' zip package.
N/A
N/A

DRILL-7981: Bump commons-compress from 1.20 to 1.21 for CVE-2021-36090

---

contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuit.java

If the default 60s timeout is not sufficient, it can be altered with the `withStartupTimeout()` method.
See also [Waiting for containers to start or be ready](https://www.testcontainers.org/features/startup_and_waits/)
Then, the `testcontainers` has merged new feature about the `For faster startup`.
See also [Tune Cassandra options for faster startup](https://github.com/testcontainers/testcontainers-java/pull/4309)
N/A
Need the unit tests can run 3 times without the `Timed out waiting for XXX`.

DRILL-7982: Timed out waiting for container port to open

---

_docs/zh/tutorials/070-analyzing-data-using-window-functions.md

Translate a tutorial to Chinese:
070-analyzing-data-using-window-functions.md
Overall 8 tutorials have been translated, 6 tutorials to go.
Please refer to Chinese tutorial.
This is a doc update, no test here.

[DOC UPDATE] Translate Tutorial to Chinese 8/14

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
lombok.config
pom.xml

See Jira ticket for details.
Yes.
Updated one of the existing test configs to use credential provider.

DRILL-7988: Add credentials provider support for API connections in HTTP plugin

---

tools/drill-patch-review.py

This minor fix fixed an LGTM alert where credentials are logged in a debug statement in a python script.   Functionality is not affected except to remove the password from the log output.

[MINOR-UPDATE] Removed password from debug logging in Python script

---

distribution/pom.xml
distribution/src/main/resources/core-site-example.xml
exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/ops/ViewExpansionContext.java
exec/java-exec/src/main/resources/bootstrap-storage-plugins.json
exec/jdbc-all/pom.xml
exec/jdbc/pom.xml
pom.xml

- add OCI OS dependency with exclusions
- update GlassFish Jersey dependencies version
- add `jersey-hk2` dependency (this injection framework was excluded from Jersey in latest versions)
- slightly decrease jdbc-all
- update default plugins in `bootstrap-storage-plugins.json`
- udpate `core-site-example.xml`
It adds ability to query Oracle Cloud Infrastructure Object Storage
https://github.com/apache/drill-site/pull/8
the older PR: https://github.com/apache/drill/pull/2309
It is manually tested with a TSV file from the private OCI OS bucket.

DRILL-7995: Add Oracle HDFS lib to query OCI Object Storage

---

contrib/storage-kafka/README.md

The [link to JSON data model on apache drill website](https://drill.apache.org/docs/json-data-model/) was incorrectly linked in the README.md file. I fixed it.
The link works and it is visible in my fork

Fixed Broken Link for Kafka Plugin Documentation

---

.dockerignore
Dockerfile
hooks/README
hooks/build
hooks/push

Our Docker container builds on OpenJDK 8u232 (released late in 2019), while the current LTS series of OpenJDK is 11.  Update our Dockerfile to OpenJDK 11.
Unchanged except that I do address the following docs issues pointed out by a user, not related to this JDK version change.
> 1. Drill documentation referrs to $DRILL_HOME environment variable which is not set in the Docker Image. Additionally in the doucmenation says it can be found in /etc/drill/conf while in the Docker image Drill has been installed into /opt/drill/conf
> 2. Add information how to add (mount) custom configuration files into the Docker image or even better, just make sure there is a Docker section in Drill's documentation whereever appropriate
- Test Drill built from master branch (1.20-SNAPSHOT) with OpenJDK 11 …

DRILL-7999 Base Docker image on maven:3.8.2-jdk-11 and openjdk-11

---

hooks/build

Drill requires the Java compiler from the full JDK at runtime so we need to change the base OpenJDK images used accordingly.
N/A
I rented a VM for testing this time and tested each image from building from a clean clone through to running a SQL query in Drill.
```
podman build \
--build-arg BUILD_BASE_IMAGE=maven:3.8.2-openjdk-8 \
--build-arg BASE_IMAGE=openjdk:8 \
-t apache/drill-openjdk-8 .
podman run --rm -it localhost/apache/drill-openjdk-8
select * from cp.`employee.json`;
podman build \
--build-arg BUILD_BASE_IMAGE=maven:3.8.2-openjdk-11 \
--build-arg BASE_IMAGE=openjdk:11 \
-t apache/drill-openjdk-11 .
podman run --rm -it localhost/apache/drill-openjdk-11
select * from cp.`employee.json`;
podman build \
--build-arg BUILD_BASE_IMAGE=maven:3.8.2-openjdk-11 \
--build-arg …
```

DRILL-8001: Replace JRE docker images with JDK counterparts.

---

contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java

Splunk occasionally sends extra white space in `INT` fields.  This was discovered by a user, and when Drill tries to parse the response, it causes `NumberFormatExceptions`.  This PR removes white space in known `INT` fields.  If an exception is thrown, it replaces the value with `-1`.   
Note that all the known `INT` fields are fields derived from time stamps, so in theory they should never be negative.
N/A
Manually tested.

DRILL-8004: Splunk Sends Newlines in INT Fields, Causing Exceptions

---

contrib/storage-mongo/pom.xml
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
pom.xml

In the MongoDB, upgrade the client from 4.3.1 to 4.3.3 and mongo container from 4.4.5 to 4.4.10.
In the Testcontainers, the 1.16 release brings many small fixes and improvements :
1. Better M1 Mac compatibility.
2. Startup performance and reliability improvements.
3. See also [What's Changed](https://github.com/testcontainers/testcontainers-java/releases/tag/1.16.0)
N/A
N/A

DRILL-8024: Bump Mongo client and Testcontainers version to latest

---

.lgtm.yml
pom.xml

Adds an exclusion to LGTM code audit.  Specifically all the minified `js` files from D3.
This minor update creates an `lgtm.yml` file and excludes the D3 files from code audit.  Since these files are not maintained by the Drill team and are mimified, they create some alerts that are not relevant to Drill. 
N/A
N/A

Exclude .js Files From LGTM

---

contrib/format-excel/pom.xml

Latest POI support for Excel
No changes
Using existing tests

DRILL-8033: uptake POI 5.1.0

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
exec/java-exec/src/main/resources/rest/storage/list.ftl
exec/java-exec/src/main/resources/rest/storage/update.ftl

Multiple REST API operations, notably affecting storage config operations, return an error message with an HTTP status code of 200 when an operation fails.  The web UI depends on this behaviour in some places.  REST clients should receive an HTTP error code instead.
There are some subtleties.  Submitting a new query than later goes on to fail in execution still sees a 200 returned for the query submission.  The storage plugin store does not raise an error if you try to delete something that it does not contain, so deleting something nonexistent is still a 200.  
Add a note indicating that failed operations will generally result in an HTTP error code.
- Existing test coverage.
- Send invalid requests to the REST API and check HTTP response code
- Use all pages of the web UI to test that …

DRILL-8040: Add HTTP status codes for API errors

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/RexToMongoTranslator.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoLimitPushDown.java

Updated code to prevent creating aggregates project for empty pipeline and updated mongo plugin implementor to prevent project pushdown for the case of star queries.
NA
closes #2367

DRILL-8042: Select star from MongoDB with aggregated pipeline fails with empty $project error

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/BaseMongoSubScanSpec.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoScanSpec.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoSubScan.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoQueries.java

Fixed deserialization of mongo scan spec classes.
NA
Added UT
closes #2355

DRILL-8041: Fix mongo scan spec deserialization

---

pom.xml

Bump HBase client version to 2.4.8
user will not really notice that change.
Just ran build and tests... at least the hbase part was successfull.... splunk had a problem but i dont think this has something to do with that change.
Regards,
Christian

DRILL-8025: Bump HBase client version to 2.4.8

---

contrib/format-excel/pom.xml

DRILL-8033 (https://github.com/apache/drill/pull/2363) caused a regression with reading excel files.  See (https://github.com/pjfanning/excel-streaming-reader/issues/76)  This PR reverts back to the previous version of POI.
The issue seems to be related to the change in logging in POI to log4j 2.x.  I attempted to exclude the logger in POI as well as include `org.apache.logging.log4j:log4j-to-slf4j:2.14.1` in the Excel module.  Neither solved the issue.  For the time being I would propose we revert back to the original dependencies which work. 
As a bit of an aside, I found it curious that the unit tests all successfully completed, but when you tried to query Excel normally, the queries all failed. It might be worth looking into why that is the case.
Ran all unit …

DRILL-8043: Excel Reader Regression Fix

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/resources/rest/static/js/serverMessage.js

Since DRILL-8040, attempts to export an individual storage config from the REST API fail with the following.
```
ERROR o.g.j.m.i.WriterInterceptorExecutor - MessageBodyWriter not found for media type=application/json, type=class org.apache.hbase.thirdparty.org.glassfish.jersey.message.internal.OutboundJaxrsResponse, genericType=class org.apache.hbase.thirdparty.org.glassfish.jersey.message.internal.OutboundJaxrsResponse.
16:56:04.187 [qtp558821862-372] ERROR o.g.j.m.i.WriterInterceptorExecutor - MessageBodyWriter not found for media type=application/json, type=class org.apache.hbase.thirdparty.org.glassfish.jersey.message.internal.OutboundJaxrsResponse, genericType=class org.apache.hbase.thirdparty.org.glassfish.jersey.message.internal.OutboundJaxrsResponse.
```
N/A
Test individual …

DRILL-8045: Fix storage export regression introduced by DRILL-8040

---

contrib/format-excel/pom.xml
contrib/storage-hive/core/src/main/java/org/apache/logging/log4j/util/Strings.java

Relates to pjfanning/excel-streaming-reader#76. This is an alternate to https://github.com/apache/drill/pull/2374.
https://github.com/apache/drill/blob/master/contrib/storage-hive/core/src/main/java/org/apache/logging/log4j/util/Strings.java is a copy of the real Log4j class but causes issues for Apache POI Excel code that relies on the latest Log4j code.)
Shouldn't require doc change
unit tests

DRILL-8044: Update contrib/storage-hive copy of log4j Strings.java

---

exec/java-exec/src/main/java/org/apache/drill/exec/client/DrillSqlLineApplication.java
exec/java-exec/src/test/java/org/apache/drill/exec/client/DrillSqlLineApplicationTest.java
pom.xml

Updated Sqlline version to fix running drill in embedded mode on Apple M1.
NA
NA

DRILL-8026: Update Sqlline to 1.12

---

contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatPlugin.java
contrib/format-iceberg/src/test/java/org/apache/drill/exec/store/iceberg/IcebergQueriesTest.java

Added generator for format id values. Formats with the same name may be defined in multiple storage plugins, so using the unique id within the convention name to ensure the rule names will be unique for different plugin instances.
NA
Updated tests to check this scenario.

DRILL-8049: Make rule names for Iceberg plugin instances unique

---

Dockerfile
contrib/storage-splunk/pom.xml
distribution/src/assemble/component.xml

Excluded dependencies that shouldn't be included in target distribution.
Copy target distribution after the user is created to reduce layers size.
NA
NA

DRILL-8053: Reduce Docker image size

---

exec/java-exec/src/main/java/org/apache/drill/exec/client/DrillClient.java
exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java
exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillHandler.java
exec/jdbc/src/test/java/org/apache/drill/jdbc/test/Drill2489CallsAfterCloseThrowExceptionsTest.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/BasicClient.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcBus.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcConstants.java

I've add ping function which send message with [RpcMode.PING](http://drill.apache.org/apidocs/org/apache/drill/exec/proto/GeneralRPCProtos.RpcMode.html#PING) to drillbit and after that waits for a response message with [RpcMode.PONG](drill.apache.org/apidocs/org/apache/drill/exec/proto/GeneralRPCProtos.RpcMode.html#PONG). This method is used to validate connection. I add this verification to [DrillConnectionImpl#isValid(int timeout)](https://github.com/apache/drill/blob/5f5ae89392471d237605c0b5e1a337e5bc0e10ff/exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java#L522) as it is required by JDBC API [documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#isValid(int)) and gives opportunity accurately validate connection:
> …

DRILL-8009: DrillConnectionImpl#isValid() doesn't correspond JDBC API

---

drill-yarn/src/main/resources/drill-am/generic.ftl

Update the JQuery version from 3.4.1 to 3.6.0 for vulnerability issue which reported by @fromrymail https://github.com/apache/drill/issues/2380
This is a package version update for security, no doc update needs
Manually tested Drill Web UI basic functions:
Query, Profiles, Storage, Metrics, Threads, Logs

DRILL-8051: Update the JQuery for Vulnerability issue

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSelection.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestGlob.java

Unescapes the root path set by FileSelection so that it is processed in a way that is consistent with the glob processor used to collect a list of files for querying.  This fixes a bug preventing queries like  ``select * from dfs.tmp.`test\\1.csv` `` from running.
None.
New unit test: TestGlob#testGlobEscapeCharRootTextFile.
Manually run ``select * from dfs.tmp.`test\\1.csv` ``

DRILL-8064: Cannot query text files with names that contain a backslash

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillConstExecutor.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestMathFunctionsWithNanInf.java

When we encounter floating point literals in a query we attempt to convert them to BigDecimal which can only handle finite floats making queries like this fail: `select cast('-Infinity' as float);`.  This change sends non-finite floats to string-based RexLiterals.
None.
New unit test: TestMathFunctionsWithNanInf#testNanInfLiteralConversion
Manually run `select cast('-Infinity' as float);`

DRILL-8066: Convert non-finite floating point literals to string RexLiterals

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java

In the REST plugin, if the `postBody` parameter is `null`, the reader will throw a NPE.  This PR adds a null check to prevent this.  
Manually tested.

DRILL-8072: Fix NPE in HTTP Post Requests

---

contrib/format-excel/pom.xml
contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java

It is not guaranteed that getLastRowNum will return the right data - it depends on dimension data that excel saves in the sheet XML but it seems increasingly common for this to be omitted
None
Unit tests

DRILL-8069: remove use of excel sheet getLastRowNum

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestQueryProfiles.java

Drill have a REST API to get the profiles of running and completed queries. this goal of ticket is extended from the `/profiles.json` to support get the running or completed profiles (not all of them). the client does not need to filter with the state.
old URI
```
/profiles.json
```
new URI
```
/profiles.json
/profiles/running
/profiles/completed
```
NA
Manual tested (use Postman).

DRILL-7983: Add a REST API to support the get running or completed profiles

---

exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/security/VaultUserAuthenticator.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/DrillRestLoginService.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/vault/VaultCredentialsProvider.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestHtpasswdFileUserAuthenticator.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestVaultUserAuthenticator.java

Vault is a popular credentials store and authentication provider license under the Mozilla Public License 2.0.  A small addition to Drill should be sufficient to allow it to authenticate users against Vault, giving users another authn option.  Note that Drill already packages vault-java-driver from BetterCloud to support storage config credentials in Vault.
A new Configuring Vault Security page underneath Securing Drill.
New unit test class TestVaultUserAuthenticator.

DRILL-8047: Add a custom authn provider for HashiCorp Vault

---

contrib/format-excel/pom.xml

Both format-excel and poi referred to Log4j 2.14.1
Due to Log4j 2.14.1 has a severe vulnerability, upgrade version to 2.15.0 for permanent mitigation.
poi also referred to log4j-api 2.14.1.
A commit of poi upgraded the dependency to 2.15.0, but still not release.
So override log4j-api dependency to 2.15.0
Please refer to https://www.lunasec.io/docs/blog/log4j-zero-day/
tested dependency by maven tree.
Before changed dependency of log4j-api to 2.15.0:
after changed dependency of log4j-api to 2.15.0:

DRILL-8074: Upgrade log4j because of CVE-2021-44228

---

exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/security/VaultUserAuthenticator.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestVaultUserAuthenticator.java

The Vault token config option for the Vault user authenticator is pointless since none of the auth operations require Drill to have its own Vault token.  Functionality is unaffected but a pointless option confuses users and adds cruft.  This PR removes the BOOT opt.
Description of the BOOT opt to be removed from the doc page.
Existing Vault unit tests

DRILL-8076: Remove unneeded Vault token BOOT opt

---

contrib/format-excel/pom.xml

Refer to DRILL-8074, #2403 and CVE 2021-45046.  This PR updates log4j-api and log4j-to-slf4j again, this time to 2.16.  Note that we do not  believe these components are actually vulnerable, this is just overzealous caution.
None
Full set of unit tests

DRILL-8074: Second upgrade of log4j (2.16 now) because of CVE-2021-44228

---

contrib/format-excel/pom.xml

Drill's format-excel has only gained log4j dependencies recently (and this is not in any Drill release yet).
Log4J have released 2.17.0 with another CVE fix. These CVEs don't affect Drill because it does not yet use log4j-core but for optics, it is better to update all log4j jars.
https://logging.apache.org/log4j/2.x/security.html
No changes
Unit tests

DRILL-8071: upgrade log4j to 2.17.0

---

pom.xml

Due to the CVE-2021-42550, Upgraded logback from 1.2.3 to 1.2.9.
Logback 1.2.9 fixed the vulnerability, please refer to: http://logback.qos.ch/news.html
Tested by  mvn dependency:tree, all dependency of logback upgraded to 1.2.9 already.

DRILL-8079: Upgrade logback to 1.2.9 because of CVE-2021-42550

---

exec/java-exec/src/main/codegen/data/ExtractTypes.tdd
exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/Extract.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
exec/vector/src/main/java/org/apache/drill/exec/vector/DateUtilities.java

This PR adds the possibility of extracting the `WEEK` from a date `EXTRACT` function. 
See above.  `WEEK` is now an option for date extract. 
Manually tested and added UT.

DRILL-8078: Add WEEK to Date Extract

---

contrib/storage-phoenix/pom.xml
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixSchemaFactory.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixCommandTest.java

Rewrite the `areTableNamesCaseSensitive()` method to support this feature.
N/A
Added two unit tests.
<pre>
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.drill.exec.store.phoenix.PhoenixTestSuite
[INFO] Running org.apache.drill.exec.store.phoenix.PhoenixDataTypeTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.575 s - in org.apache.drill.exec.store.phoenix.PhoenixDataTypeTest
[INFO] Running org.apache.drill.exec.store.phoenix.PhoenixSQLTest
[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4.101 s - in org.apache.drill.exec.store.phoenix.PhoenixSQLTest
[INFO] Running …

DRILL-8080: Enable the describe Case-Insensitive for Phoenix

---

.github/workflows/ci.yml

<pre>
Error:  Failed to execute goal on project drill-format-excel: Could not resolve dependencies for project 
org.apache.drill.contrib:drill-format-excel:jar:1.20.0-SNAPSHOT: Failed to collect dependencies at 
com.github.pjfanning:excel-streaming-reader:jar:3.2.6: Failed to read artifact descriptor for com.github.pjfanning:excel-streaming-reader:jar:3.2.6: 
Could not transfer artifact com.github.pjfanning:excel-streaming-reader:pom:3.2.6 from/to central 
(https://repo.maven.apache.org/maven2): transfer failed for 
https://repo.maven.apache.org/maven2/com/github/pjfanning/excel-streaming-reader/3.2.6/excel-streaming-reader-3.2.6.pom: 
Connection timed out (Read failed) -> [Help 1] 
</pre>
We can learn from this note [Maven Connection timed …

DRILL-8081: Maven Connection timed out

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java

Remove unnessesery map copy each time when enter new scope.
No need
Will be tested in many existed UT which query with "case when", e.g. ifExpression in TestLimit0VsRegularQueriesMetadata

DRILL-8088: Improve expression evaluation performance

---

contrib/format-excel/pom.xml

[DRILL-8071](https://issues.apache.org/jira/browse/DRILL-8071): upgrade log4j to 2.17.1
Drill's format-excel has only gained log4j dependencies recently (and this is not in any Drill release yet).
Log4J have released 2.17.1 with another CVE fix. These CVEs don't affect Drill because it does not yet use log4j-core but for optics, it is better to update all log4j jars.
https://logging.apache.org/log4j/2.x/security.html
No changes
Unit tests

DRILL-8071: upgrade log4j to 2.17.1

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/rules/JdbcLimitRule.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/rules/JdbcSortRule.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixConvention.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixIntermediatePrelConverterRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcRuleBase.java
pom.xml

- Updated Calcite fork version to include https://github.com/apache/calcite/commit/cc40a48cb8ca16f91bfdc66eaed6151805355d4b, so now regular limit can be pushed down to MS SQL as `TOP N` instead of `FETCH`.
- Updated `JdbcLimitRule` and `JdbcSortRule` to prevent pushing down `FETCH` with `OFFSET` and without `ORDER BY`. 
For such a case, some rules at the physical stage will generate a limit on top of the scan that includes `FETCH` only and another limit with `FETCH` and `OFFSET` above, so the limit will be pushed down.
- Allowed matching JDBC rules for physical rel nodes.
- Fixed issue with ClassCastException for Phoenix plugin (issue similar to [DRILL-7972](https://github.com/apache/drill/pull/2275)).
NA

DRILL-8090: LIMIT clause is pushed down to an invalid OFFSET-FETCH clause for MS SQL Server

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/mergereceiver/MergingRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/partitionsender/PartitionSenderRootExec.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java

Calculate setup time separately for some operators
No need
By existed ut

DRILL-8089: Separate the setup time for some operators

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java

Suport split_part('a,b,c,d', ',' , -2, -1) = 'c,d' and split_part('a,b,c,d', ',' , -3) = 'b'
See https://github.com/apache/drill-site/pull/22
UT added

DRILL-8094: Support reverse truncation for split_part udf

---

exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicSchema.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/DrillSchemaFactory.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/SchemaTreeProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/FilterEvaluator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilter.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaRecordGenerator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/mock/MockBreakageStorage.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/metadata/MetadataProvider.java
exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestSchema.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchema.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/ischema/TestInfoSchemaFilterPushDown.java

WHERE clauses in queries against INFORMATION_SCHEMA do not stop Drill from fetching a schema hierarchy from all enabled storage configs.  This results in abysmal performance when unresponsive data sources are enabled, as reported by users in the Apache Drill Slack channels.  This PR teaches info schema to prune irrelevant schema subtrees from the search tree and removes eager subschema registration by DrillSchemaFactory.
No user-visible change
Existing info schema unit tests + one addition for IN operator
TestInfoSchemFilterPushDown#testLazySchemaRegistration to test that eager schema registration is not taking place.

DRILL-8057: INFORMATION_SCHEMA filter push down is inefficient

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/OffsetPaginator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/PagePaginator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/Paginator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPaginator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoader.java

This PR is a follow-up to #2414 and refactors the Paginator classes in that PR.  No functionality is changed.  The main goal is to base the Paginators on java.util.Iterator but some extra simplification was also possible. 
See #2414.
See #2414.

DRILL-8092: Add Auto Pagination to HTTP Storage Plugin

---

contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java

Drill was ignoring the `headerRow` parameter in the Excel reader, which allowed Drill to skip to the first row of actual data.  This PR fixes that.
N/A
Ran unit tests, and tested manually.

DRILL-8112: Excel Reader Ignores HeaderRow Config Param

---

drill-yarn/src/test/java/org/apache/drill/yarn/scripts/TestScripts.java

The removed test is a copy pasta of [the log dir test directly above it](https://github.com/apache/drill/blob/4aefcef2b665c5737471664912a26ef6ed9a6cfc/drill-yarn/src/test/java/org/apache/drill/yarn/scripts/TestScripts.java#L253) so does not test
the native lib dir variables it claims to at all.  There is a legitimate test of the native lib 
dir env vars present in the same test class.
N/A
N/A

[MINOR UPDATE] Remove bogus copy paste test of log dir env var.

---

contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/plan/IcebergPluginImplementor.java
contrib/format-iceberg/src/test/java/org/apache/drill/exec/store/iceberg/IcebergQueriesTest.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/AbstractPluginImplementor.java

Added checks to ensure that table has iceberg group scan when matching iceberg rules (the same for mongo).
NA

DRILL-8114: Prevent applying Iceberg project on non-Iceberg tables

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
contrib/storage-mongo/src/main/resources/bootstrap-storage-plugins.json
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestBase.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoStoragePluginUsesCredentialsStore.java

MongoDB has a strange feature  whereby queries which use more than 100MB of memory will by default fail.  Mongo allows the user to specify whether they want the query to spill to disk which allows larger queries but at a performance cost.
This minor PR adds the ability for a user to specify whether they want this option included in Mongo queries.  This only affects aggregate queries in Mongo. 
This adds a new config option to the mongo config: `allowDiskUse` which, when set to `true`, will pass that parameter down to MongoDB during aggregate queries.  
Ran unit tests

DRILL-8118: Add Option to Allow Disk Use on Mongo Queries

---

pom.xml

Upgrade Apache Xerces because of CVE-2022-23437
please refer to https://github.com/advisories/GHSA-h65f-jvqw-m9fj
Check dependency by "mvn dependency:tree" and all dependencies which related to Xerces have been upgraded to 2.12.2

DRILL-8116: Upgrade Apache Xerces because of CVE-2022-23437

---

contrib/storage-jdbc/pom.xml

Postgresql: 42.3.1 -> 42.3.2
N/A

DRILL-7994: Dependency version updates for severe vulnerabilities

---

contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReader.java
contrib/format-sas/src/test/java/org/apache/drill/exec/store/sas/TestSasReader.java
contrib/format-syslog/src/test/java/org/apache/drill/exec/store/syslog/TestSyslogFormat.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasySubScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetWriterBatchCreator.java
exec/java-exec/src/test/java/org/apache/drill/exec/metastore/TestMetastoreWithEasyFormatPlugin.java

Recent work added a push down of the limit into a scan. The work had a few holes, one of which was plugged by the recent update of EVF to manage the limit. Another hole is that the physical plan uses a value of 0 to indicate no limit, but 0 is a perfectly valid limit, it means "no data, only schema." The field name is "maxRecords", but should be "limit" to indicate the purpose.
N/A
Reran unit tests.

DRILL-8123: Revise scan limit pushdown

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java

This PR fixes a minor bug with the storage plugin configuration by marking the `oauth` parameter as ignorable. This parameter is actually derived by the config and used to hide the `authorize` button when not needed.
Ran unit tests & manually tested

DRILL-8126: Ignore OAuth Parameter in Storage Plugin

---

contrib/storage-phoenix/pom.xml
exec/jdbc-all/pom.xml

Because this dependency is of type "bundle", the module requires the maven-bundle-plugin in order to resolve it, and for the module to build.  This dependency only arises under the Hadoop 2 profile, or when building with `-Phadoop-2`.
N/A
Build Drill under the default profile and under -Phadoop-2

DRILL-8129: Storage-phoenix cannot resolve OSGi bundle apache-ds.jdbm1

---

exec/jdbc-all/pom.xml
pom.xml

In Apache Hadoop 3.2.0 to 3.2.1, 3.0.0-alpha1 to 3.1.3, and 2.0.0-alpha to 2.10.0, WebHDFS client might send SPNEGO authorization header to remote URL without proper verification.
N/A

DRILL-8130: Upgrade Hadoop 2 to 2.10.1 because of CVE-2020-9492

---

contrib/storage-jdbc/pom.xml
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/rules/JdbcLimitRule.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixConvention.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillLimitRelBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillLimitRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/LimitPrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcRuleBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/PluginLimitRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginLimitRule.java

Prevented applying JDBC and Phoenix rules for DRILL_PHYSICAL rel nodes.
Updated JDBC limit rule to be applied only for limits that weren't pushed down, and split limit into several ones for the case of MSSql database instead of relying on splitting it later during physical optimizations.
NA
Added unit test, checked more complex cases manually.

DRILL-8131: Infinite planning when JDBC or Phoenix plugin is enabled

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/union/UnionAllRecordBatch.java
exec/java-exec/src/test/java/org/apache/drill/TestUnionAll.java

Please see the Jira ticket for detailed RCA.
NA
Added UT

DRILL-8137: Prevent reading union inputs after cancellation request

---

contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaGroupScan.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/MessageIterator.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java

[`Consumer#poll(long)`](https://javadoc.io/static/org.apache.kafka/kafka-clients/3.1.0/org/apache/kafka/clients/consumer/Consumer.html#poll-long-) is deprecated starting from kafka 2.0. In Drill, `Consumer#poll` is used in 2 places:
1. [By its direct purpose
](https://github.com/apache/drill/blob/15b2f52260e4f0026f2dfafa23c5d32e0fb66502/contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/MessageIterator.java#L82)
2. As an only one way to make a Kafka consumer [update metadata
](https://github.com/apache/drill/blob/15b2f52260e4f0026f2dfafa23c5d32e0fb66502/contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaGroupScan.java#L185)
Kafka [hasn't implemented](https://cwiki.apache.org/confluence/display/KAFKA/KIP-505%3A+Add+new+public+method+to+only+update+ …

DRILL-8122: Change kafka metadata obtaining due to KAFKA-5697

---

contrib/storage-jdbc/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/BatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/FixedByteAlignedReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableColumnReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/PageReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetFixedWidthDictionaryReaders.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java

As of Drill 1.19 some Parquet readers column contained code to position the value vector write buffer index after a read pass, while some did not.  The Parquet v2 PR added write buffer positioning to the cases that were missing it, but failed to cater for the fact that INT96 timestamps are downcast to 64 bit timestamps.  This PR removes all of this write buffer positioning (and mispositioning) since testing indicates that Drill's value vector write paths advance the write buffer index to correct place already.
N/A
ParquetTestWriter#testSparkParquetBinaryAsTimeStamp_DictChange

DRILL-8134: Cannot query Parquet INT96 columns as timestamps

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/compression/AirliftBytesInputCompressor.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/compression/DrillCompressionCodecFactory.java
pom.xml

This PR implementes a workaround for [PARQUET-2126](https://issues.apache.org/jira/browse/PARQUET-2126).  Once PARQUET-2126 is fixed, this change can be reversed.  Until then it is needed to read gzip and brotli compressed parquet under the async column reader without data corruption or query failures.
The gzip and rdblue/brotli-codec decompressor objects returned by the Parquet lib's codec factory are not thread safe.  Here we work around the problem by creating, and later releasing, single-use codec factories for codecs other than snappy which is immune due to its internal thread safety.  Many codec factories can be created during the reading of a Parquet file containing gzip compressed column data which is unnatural and unfortunate but [the added overhead does appear to be …

DRILL-8139: Data corruption and occasional segfaults querying Parquet/gzip under the async column reader and sync page reader

---

contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
contrib/format-sas/src/test/java/org/apache/drill/exec/store/sas/TestSasReader.java

The idea to infer schema by analyzing the type of first row is not the best idea in this case because either the value of field in the first row can be null or the entire row can be missing (0 rows). Moreover, I think that there is no point of using MinorType.BIGINT (Long) at all since SAS stores all numbers as Double anyway. Actually, as it turned out, SAS stores any data either in VARCHAR or DOUBLE format.
My proposal is to analyze SAS column type (VARCHAR/DOUBLE) together with column format to define MinorType. In this case we don't need to use the first row at all. 
As you can see below, we can take advantage of dictionaries with all possible Date/Time formats that are already defined in parso lib to distinguish between TIME, DATE and TIMESTAMP. 
```
if …
```

DRILL-8146: SAS reader fails to read the majority of sas files

---

exec/java-exec/pom.xml
exec/jdbc/pom.xml
pom.xml

Drill has several Jackson dependencies which were added to override transitive dependencies. What do you think if we add [jackson-bom](https://github.com/FasterXML/jackson-bom) to `drill-root` to be sure, that all libraries are compatible and are exactly the version that we want?
Unit tests

Add jackson-bom

---

contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/OAuthTokenContainer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java

This PR converts the OAuth REST APIs to accept JSON.  
The following API calls are now available for updating an HTTP Storage Plugin's OAuth tokens if OAuth is used. These three new endpoints are POST requests and accept the tokens as part of the form body.
* `/storage/{plugin name}/update_access_token`
* `/storage/{plugin name}/update_refresh_token`
* `/storage/{plugin name}/update_oauth_tokens`
These endpoints take as arguments: `accessToken`, `refreshToken` or both.
Updated unit tests.

DRILL-8153: Convert OAuth REST APIs to JSON

---

contrib/storage-cassandra/pom.xml
contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraColumnConverterFactory.java
contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraColumnConverterFactoryProvider.java
contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/plan/CassandraEnumerablePrelContext.java
contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/BaseCassandraTest.java
contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraQueryTest.java
contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuite.java
contrib/storage-cassandra/src/test/resources/queries.cql
contrib/storage-elasticsearch/pom.xml
contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchColumnConverterFactory.java
contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchColumnConverterFactoryProvider.java
contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/plan/ElasticSearchEnumerablePrelContext.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticComplexTypesTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticInfoSchemaTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchPlanTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/TestElasticsearchSuit.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/TestElasticsearchSuite.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/ColumnConverter.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/ColumnConverterFactoryProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/DefaultColumnConverterFactoryProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableBatchCreator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableRecordReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableSubScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/EnumerablePrel.java

Add some absent data types support for Cassandra and elasticsearch.
Migrate tests to testcontainers.
NA
Updated unit tests.

DRILL-8151: Add support for more ElasticSearch and Cassandra data types

---

contrib/storage-http/README.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java

This PR allows the user to control where parameters are pushed down during `POST` requests.  The choices are:
* `query_string`:  `POST` parameters (both filters and static) are pushed to the query string. 
* `post_body`: `POST` parameters (both filters and static) are pushed to the post body as key/value pairs
* `json_body`: `POST` parameters (both filters and static) are pushed to the post body as JSON.
The user can set this by adding the `postParameterLocation` parameter to an API configuration.  The default is `query_string`. 
The user can set the destination and format of POST parameters by adding the `postParameterLocation` parameter to an API configuration.  The default is `query_string`. 
The choices are:
* `query_string`:  `POST` parameters (filters only) are pushed to the query …

DRILL-8140: Add JSON Post Body to HTTP Rest Storage Plugin

---

.travis.yml
exec/java-exec/pom.xml
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/TestDrillbitResilience.java
pom.xml

- changing timeout for TestDrillbitResilience tests
- timing tuning for memoryLeaksWhenCancelled
- update TestContainers version
- -DforkCount=1 for Travis Maven build
- directMemoryMb: 2500 -> 4500 leads to less occasinal test failures
Please check the description from [DRILL-8145](https://issues.apache.org/jira/browse/DRILL-8145)
N/A
This PR fully about tests

DRILL-8145: Fix flaky TestDrillbitResilience#memoryLeaksWhenCancelled test case

---

.github/stale.yml

Add stalebot to Drill.  Per the discussion on the email list, issues over 120 days old with zero activity will be closed.  
First there is a warning and if there is no activity, the issue will be closed after an additional 14 days.

[MINOR UPDATE] Add Stalebot Config

---

contrib/storage-http/README.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/CredentialProviderUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/UsernamePasswordWithProxyCredentials.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/oauth/OAuthTokenCredentials.java

Currently, Drill forces to you set username and passwords individually for every API endpoint in a http storage plugin.  This PR allows you to set global credentials which will be used for all endpoints in a given HTTP storage plugin instance.
Users can now add a credential provider to an HTTP Storage Plugin configuration and these credentials will be applied to every endpoint in that instance.  However, if credentials are supplied in an endpoint, those credentials override the global credentials. 
Added assertions to existing unit tests to make sure that the correct credentials are going to the connection.

DRILL-8161: Add Global Credentials to HTTP Storage Plugin

---

exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRestServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRoot.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StatusResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/jdbc-all/pom.xml
pom.xml

Used Swagger Core to produce an OpenAPI specification for Drill's REST API. One can access it in JSON format by going to `localhost:8047/openapi.json` after starting Drill. 
Also, added an HTML script to produce the Swagger UI when one visits `localhost:8047/static/swagger-ui.html`.
Used Swagger annotations to populate the Swagger UI with the relevant information, including links to documentation on [https://drill.apache.org/docs/](https://drill.apache.org/docs/). More information can be added via additional annotations.
One can visit `localhost:8047/openapi.json` after starting Drill to find an OpenAPI specification for Drill's REST API. One can also visit `localhost:8047/static/swagger-ui.html` after starting Drill to find the Swagger UI, which clearly displays the endpoints for the …

DRILL-8162: Add OpenAPI Specification documentation for Drill's REST API

---

Dockerfile

Some users of embedded Drill in Docker want to use a Docker volume with Drill, particularly for Drill's persistent local storage so that Drill configuration can persist across container launches.  Because Drill no longer runs as root in the Docker container as of 1.20, these users now need a mountpoint inside that container that has been chowned to drilluser.
Also remove unneeded permissions to Drill installation dir that were held by drilluser.
Document the existence of the volume mountpoint at /data in the container.
1. Build an image using Drill master and the Dockerfile in this branch.
2. Launch the image with default args (no volume mounted) and run test queries.  Confirm that an option set with ALTER SYSTEM is lost across container launches.
3. Launch the image with a host volume …

DRILL-8156: Declare and chown a /data VOLUME in the Drill Dockerfile

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JSONFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JSONRecordReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/DropboxFileSystemTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonModes.java
exec/java-exec/src/test/java/org/apache/drill/test/PhysicalOpUnitTestBase.java
exec/java-exec/src/test/resources/jsoninput/nan_test.json

Most all Drill format plugins allow the user to configure various options for that plugin as part of the format config.  The one glaring exception is the JSON reader which has several configuration options which can only be set globally.  This PR moves these to the format config so that users can set these options when they configure a storage plugin.  
This PR does not eliminate the global settings for JSON.  It simply adds another place where a user can update the settings.  If the settings in the config file are not defined (`null`) Drill will use the global settings.
The config is set to only include these values when they are not `null`, so there are no breaking changes.
Drill's JSON reader can be configured with various global configuration variables.  However these variables can …

DRILL-8167: Add JSON Config Options to Format Config

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/BaseQueryRunner.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRestServer.java

When authentication is enabled, the Drill UserSession is persistent and it is only appropriate to modify it for impersonation once.  This adds a check for whether the UserSession needs modifying and avoids any uneeded attempt to do so, thereby fixing the broken scenario
Request 1: UserSession user alice modified to impersonated user bob
Request 2: UserSession user bob fails to be modified to bob because bob is not authorised to impersonate bob.
N/A
New test for this scenario?

DRILL-8168: Do not duplicate attempts to impersonate a user in the REST API

---

.travis.yml
exec/java-exec/pom.xml
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java

Unlike GitHub CI, Travis CI may have more memory. If so, we can run unit tests using various policies to prevent failure.
* This patch also fixes an brotli dependency test failure.
N/A
Done.

DRILL-8172: Use the specified memory usage for Travis CI

---

metastore/rdbms-metastore/pom.xml
metastore/rdbms-metastore/src/main/java/org/apache/drill/metastore/rdbms/RdbmsMetastore.java

Split from the #2493 
Please note that we should replace the `DatabaseFactory.getInstance()` with `Scope.getCurrentScope().getSingleton(DatabaseFactory.class)` once the following issue is resolved.
N/A
Use the CI.

DRILL-8165: Upgrade liquibase because of CVE-2022-0839

---

contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogBatchReader.java
contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogFormatPlugin.java
contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdParser.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JsonRecordWriter.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/CompliantTextBatchReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/ConstrainedFieldOutput.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/FieldVarCharOutput.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/TextParsingSettings.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/TextReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestTextWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestRestJson.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/DropboxFileSystemTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/TestPluginRegistry.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/BaseCsvTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/TestCsvWithHeaders.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/TestCsvWithSchema.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/TestTextReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/mock/TestMockRowReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/util/StoragePluginTestUtils.java

This PR is the remaining bits of the original DRILL-8085 PR: the Text and HTTPD log plugins.
The text plugin is surprisingly complex. Upgrading it is helpful technically, but it does not serve as a very good example. So, this PR also upgraded the far simpler HTTPD log plugin to act as an example for other conversions.
Note that, when doing conversions, you can rip out the prior do-it-yourself limit code: EVF now handles this work.
Also includes:
* DRILL-8159: Convert the HTTPD reader to use EVF V2
No changes: this is purely an internal change.
GitHub will helpfully run the unit tests. (Last time I tried, they didn't run on my machine.)

DRILL-8086: Convert the CSV (AKA "compliant text") reader to EVF V2

---

contrib/format-image/pom.xml
contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataReader.java
contrib/format-image/src/test/resources/image/eps.json
contrib/format-image/src/test/resources/image/jpeg.json
contrib/format-image/src/test/resources/image/mov.json
contrib/format-image/src/test/resources/image/tiff.json
pom.xml

Also included the DRILL-8165 (Upgrade liquibase because of CVE-2022-0839).
Please note that we should replace the `DatabaseFactory.getInstance()` with `Scope.getCurrentScope().getSingleton(DatabaseFactory.class)` once the following issue is resolved.
https://github.com/liquibase/liquibase/issues/2349
N/A
Use the CI.

DRILL-8164: Upgrade metadata-extractor because of CVE-2022-24613

---

distribution/pom.xml

Updated AWS libraries to latest version.  The version which shipped with Drill was 4 years old. 
N/A

DRILL-8178: Bump AWS Libraries to Latest Version

---

distribution/src/main/resources/drill-override-example.conf
exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfigurator.java
exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfig.java
exec/java-exec/src/main/resources/drill-module.conf
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitSSL.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitSSLServer.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfiguratorTest.java

Change default TLS version to 1.3 for Web Server and client-drillbit connection as it is more efficient and secure protocol.
Default TLS version for RPC layer, Web Server and JDBC driver is changed from 1.2 to 1.3:
https://github.com/apache/drill-site/pull/27
Manual verification with commands:
```
openssl s_client -tls1_3 localnode.com:8047
openssl s_client -tls1_3 localnode.com:31010
openssl s_client -tls1_2 localnode.com:8047
openssl s_client -tls1_2 localnode.com:31010
```
Manual test with Sqlline direct connection to drillbit:
* Positive test with default TLS:
```sh
apache drill> !connect jdbc:drill:drillbit=localnode.com:31010;enableTLS=true;disableCertificateVerification=true
apache drill> select version from sys.version;
+----------------+
|    version     |
+----------------+
| …
```

DRILL-8177: Bump default TLS version to 1.3

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigServer.java

Accept nullable parameter types in the UDFs in the HTTP storage plugin returning an empty MAP when a null argument is present.
When default HikariCP pool parameters are set in the JDBC storage plugin, the parameter names are incorrectly prefixed with "dataSource.".  Remove this.
None
TestDataSource#testInitWithSourceParameters()
TestHttpUDFFunctions#testNullParam()

DRILL-8181: Accept nullable args in HTTP plugin UDFs, fix HikariCP default parm names

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/OutputBatchBuilder.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/TestOutputBatchBuilder.java
exec/vector/src/main/java/org/apache/drill/exec/vector/BitVector.java
exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/AbstractArrayWriter.java

Fixes the rather complex area in EVF2 that handles projection of nested maps and map arrays to properly pass along the offset vector for map arrays, and set the value count for nested maps.
N/A
Added unit tests for this case. Verified against @luocooong,'s DRILL-8174 (upgrade Avro to EVF-2) branch.

Fix projection of map arrays and nested maps in EVF2

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java

The `http_request` function was ignoring the `inputType` parameter and throwing an exception.  This fixes that. 
Manually tested and ran unit tests.

DRILL-8191: HTTP Request Function Not Detecting JSON Config

---

contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/plan/IcebergPluginImplementor.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/AbstractPluginImplementor.java

Some storage plugin instances like Cassandra don't support obtaining group scan using the `StoragePlugin.getPhysicalScan()` method. Added extra check to ensure that plugin implementor can obtain group scan safely.
NA

DRILL-8192: Cassandra queries fail when enabled Mongo plugin

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpJsonOptions.java

The `jsonOptions` in the HTTP storage plugin was missing a Jackson annotation which prevented users from setting the options, although the unit tests passed.
N/A
Ran unit tests and tested manually

DRILL-8193: Incorrect Annotation used for HttpJsonOptions

---

contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithPostgres.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillReduceAggregatesRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillCalciteSqlSumEmptyIsZeroAggFunctionWrapper.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillOperatorTable.java

Added `DrillCalciteSqlSumEmptyIsZeroAggFunctionWrapper` that extends `SqlSumEmptyIsZeroAggFunction` and wraps `SqlSumEmptyIsZeroAggFunction` only in order to enable functionality added in CALCITE-1174 (`When generating SQL, translate SUM0(x) to COALESCE(SUM(x), 0)`)
NA

DRILL-8013: Drill attempts to push "$SUM0" to JDBC storage plugin for AVG

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java

(Please replace `PR Title` with actual PR Title)
Add code to check buffer's capacity with text's length.
We realloc buffer, if actual length is more than previously applied.
NA
Add test case: org.apache.drill.exec.expr.fn.impl.TestStringFunctions#testReplaceOutBuffer

DRILL-8194: Fix the function of REPLACE throws IndexOutOfBoundsException, if text's length is more than previously applied

---

exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassTransformer.java
exec/java-exec/src/main/java/org/apache/drill/exec/compile/JaninoClassCompiler.java
exec/java-exec/src/main/java/org/apache/drill/exec/compile/bytecode/ReplacingBasicValue.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionInitializer.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/ImportGrabber.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/MethodGrabbingVisitor.java
exec/jdbc-all/pom.xml
pom.xml

This update is required for the Calcite update.
NA
NA

DRILL-8035: Update Janino to 3.1.7 version

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestDataSource.java
logical/src/main/java/org/apache/drill/common/logical/StoragePluginConfig.java

... and test the case of JDBC.
A utility method for parsing the auth mode enum incorrectly defaults to `DRILL_PROCESS`, even when called by storage plugins that desire a different default.
New user and dev docs for auth modes pending.
TestDataSource#testInitWithoutUserAndPassword now checks the default authMode applied when it is missing from the storage config for the case of the JDBC plugin.

[MINOR UPDATE] Fix default auth mode in AuthMode.parseOrDefault

---

distribution/pom.xml

Bump AWS Java SDK to latest version.
N/A
Manually tested with S3 bucket.

[MINOR UPDATE] Update AWS Java SDK to 1.12.211

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java

Fixes a Serialization/Deserialization bug in the JDBC plugin
Ran unit tests

DRILL-8207: Fix typo in JDBC config

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/CredentialProviderUtils.java

This second PR reverts three regressions.
1. Remove the @JsonIgnore annotation from `JsonIgnore::getPassword()`, solving a Jackson deserialisation error affecting that class.
2. Revert the type change of the `writable` property to Boolean in JdbcStorageConfig.
3. Revert null handling logic in `CredentialProviderUtils::getCredentialsProvider`.
N/A
Unit tests, manually start Drill with template storage configs. Edit `rdbms` so that it holds a valid pg database config, run a query against pg, individually add and remove the username and password direct credentials from the storage config. Test info schema queries when the `writable` property is both absent and present from an enabled JDBC config.

DRILL-8207: Fix Username Typo and password @JsonIgnore in JDBC SerDe

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SqlSelectBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/AnalyzeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DescribeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/MetastoreAnalyzeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowSchemasHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowTablesHandler.java

The newer Calcite version adds more fields to the constructor of SqlSelect. In most cases, nulls are passed for these new arguments. Using builder will reduce the number of places where it should be added.
NA

DRILL-8208: Create builder for SqlSelect

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/CredentialResources.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/resources/rest/credentials/list.ftl

DRILL-8155 introduced a small regression in the `PluginConfigWrapper` which caused some serialization/deserialization errors.  This fix removes the `SecurityContext` from that class and as a result, fixes the issue.
This PR also addresses [DRILL-8217](https://issues.apache.org/jira/browse/DRILL-8217) which the page to enter user credentials throws an exception if no plugins are eligible. 
N/A
Manually tested.

DRILL-8215: Remove SecurityContext from PluginConfigWrapper

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdSelectivity.java

With the newer Calcite version, some join queries fail with StackOverflowError. In the new version, Calcite uses selectivity code for computing cost for some conditions.
NA
Unit tests that were failing pass

DRILL-8212: Join queries fail with StackOverflowError

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdRowCount.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/index/generators/IndexIntersectPlanGenerator.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/RangePartitionExchangePrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/RowKeyJoinPrel.java

In the newer Calcite version RelNode.getRows was removed, so replacing its usage with RelNode.estimateRowCount
NA

DRILL-8213: Replace deprecated RelNode.getRows with RelNode.estimateRowCount

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcCatalogSchema.java

DB2 is another DBMS in which clients must connect to a named database, not just to the DBMS. A JDBC connection that does the same will receive a single record containing a null string from a call to Connection::getMetaData::getCatalogs. We need to ignore such a record in order to query DB2 correctly.
N/A
Install DB2 using the Docker container ibmcom/db2. Create a test schema and table in the existing `testdb`. Configure a new Drill JDBC storage config to connect to the DB2 `testdb` database. Test info schema queries and direct querying of the test table.

DRILL-8219: Handle null catalog names returned by DB2 in storage-jdbc

---

exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestVarArgFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/testing/VarCharConcatFunctions.java

Current function implementation of `concat_delim` is wrong.
`select concat_delim(',', 'a', null, 'b') as c `
The result of this query should be `'a,b'`, but current result is `'a,,b'
`
org.apache.drill.exec.fn.impl.TestVarArgFunctions#testConcatDelimVarArgsWithNullValue

DRILL-8222: Fix wrong func impl of concat_delim, when null-value exist in middle args

---

exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/StatusResourcesTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/StorageResourcesTest.java
exec/java-exec/src/test/java/org/apache/drill/test/RestClientFixture.java

Use the RestClientFixture to test the function of API endpoints in StorageResources
N/A
N/A

DRILL-8218: Add unit tests for StorageResource REST endpoints

---

contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveUtilities.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithH2.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithMySQL.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithPostgres.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/config/Values.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/SchemaUtils.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/values/ValuesBatchCreator.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillValuesRelBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillValuesRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/ValuesPrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/MetastoreAnalyzeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JsonStreamBatchReader.java
exec/java-exec/src/test/java/org/apache/drill/TestProjectWithFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestValues.java
logical/src/main/java/org/apache/drill/common/logical/data/Values.java

The newer Calcite version simplifies and removes casts for literals. It causes wrong results for `drillTypeOf` and `sqlTypeOf` functions since the Values operator uses an old JSON reader which reads integers with bigInt type.
This PR uses EVF-based JSON reader for the Values operator and passes actual data types discovered during planning as the provided schema.
NA

DRILL-8216: Use EVF-based JSON reader for Values operator

---

contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBPushProjectIntoScan.java
contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/plan/ElasticsearchProjectRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillFilterItemStarReWriterRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillMergeProjectRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillProjectPushIntoLateralJoinRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushProjectIntoScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushRowKeyJoinToScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/PreProcessLogicalRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/explain/NumberingRelWriter.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/RewriteProjectToFlatten.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SplitUpComplexExpressions.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ComplexUnnestVisitor.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcRuleBase.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginProjectRule.java

In the newer Calcite version `RelNode.getChildExps` was removed, so replacing it with `Project.getProjects`
NA
Unit tests pass.

DRILL-8211: Replace deprecated RelNode.getChildExps with Project.getProjects

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/FileSystemPartitionDescriptor.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DirPrunedTableScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushProjectIntoScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillTable.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/partition/PruneScanRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DrillTableInfo.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/table/function/WithOptionsTableMacro.java

The newer Calcite version returns LogicalTableScan instead of EnumerableTableScan in RelOptTableImpl, so Drill shouldn't rely on this class also and LogicalTableScan where possible to avoid planning issues.
NA
Unit tests passing

DRILL-8214: Replace EnumerableTableScan usage with LogicalTableScan

---

.travis.yml
contrib/storage-http/pom.xml
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
exec/memory/base/src/main/java/org/apache/drill/exec/memory/AllocationManager.java
exec/memory/base/src/main/java/org/apache/drill/exec/memory/BaseAllocator.java

Fix testSlowResponse and increase heap memory for Travis build (change to default value, 2048 -> 2500 Mb)
NA
This change about fixing tests

DRILL-8224: Fix TestHttpPlugin#testSlowResponse

---

pom.xml

The previous PR for this update did everything except set hadoop.version = 3.2.3.
N/A
Existing test coverage.

DRILL-8200: Update Hadoop libs to ≥ 3.2.3 for CVE-2022-26612 (set hadoop.version)

---

contrib/format-excel/pom.xml
contrib/format-httpd/pom.xml
contrib/udfs/README.md
contrib/udfs/pom.xml
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/UserAgentAnalyzerProvider.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/UserAgentFunctions.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestUserAgentFunctions.java
pom.xml

In order to support logging, parsing and analyzing the User-Agent Client Hints it was needed to update the LogParser to fix a parsing bug and to update Yauaa to support actually analyzing them.
See https://yauaa.basjes.nl/using/clienthints/
The change includes the updated Readme for the UDFs.
The change includes the original tests and additional tests for the new functionality.
For some of the existing tests the readability of the test has been improved.
For specific edge cases (like passing a null value and empty string) the parse results have changed.

DRILL-8225: Update LogParser and Yauaa to support User-Agent Client Hints

---

contrib/storage-jdbc/pom.xml
contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcCatalogSchema.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
contrib/storage-jdbc/src/test/resources/mssql-test-data.ms.sql

Swallow and log the AbstractMethodError thrown when we call this method in the mentioned drivers. The default schema for the plugin will default to the first one in the list of schemas returned by the connection in this instance.
N/A
A new MSSQL testcontainer that is unit tested through the jTDS driver is added.

DRILL-8227: JConnect and jTDS JDBC drivers do not implement Connection::getSchema

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/RuleInstance.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillDistinctJoinToSemiJoinRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillSemiJoinRel.java

Newer Calcite changed the order of applying rules. AggregateRemoveRule is applied before SemiJoinRule, so SemiJoinRule cannot be applied later, since aggregate is pruned from planning.
Adding rule that converts join to semi-join if the right side has distinct columns.
Fixed cost and row count computation for semi-join.
NA

DRILL-8209: Introduce rule for converting join with distinct input to semi-join

---

exec/jdbc/src/test/java/org/apache/drill/jdbc/test/Drill2288GetColumnsMetadataWhenNoRowsTest.java

The order of initializing static context is broken while using static `#getDefaultProperties` method and `dirTestWatcher` `@ClassRule` from `JdbcTestBase` without extending `JdbcTestBase`.
NA
It fixes tests

DRILL-8228: GetColumnsMetadataWhenNoRowsTest regression

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java

The `http_get` and `http_request` UDFs were not using the JSON parameter to skip malformed records.  This PR fixes that.
N/A
Manually tested.

DRILL-8229: Add Parameter to Skip Malformed Records to HTTP UDF

---

contrib/format-excel/pom.xml

Upgrade POI libs used for excel support
n/a
unit tests - CI build

[DRILL-8230] upgrade to POI 5.2.2

---

contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java

[MINOR UPDATE] Disable TestJdbcPluginWithMSSQL when not on amd64.

---

hooks/build

The change is made in order to remain consistent with the OS in Drill's base images for JDK 8 and 11 since users may have derived from the Drill Dockerfile or written other scripts that assume a Debian-like OS inside the Docker image.
No changes.
Build a Docker image using the new base image in this PR, then start it and run some queries.

DRILL-8223: Change JDK 17 Docker base image from Oracle Linux to Debian.

---

contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcSort.java

Adjusted the cost of `DrillJdbcSort` to handle the case when the original limit was split
NA
All unit tests passed, enabled disabled test which is fixed with these changes.

DRILL-8237: Limit is not pushed down to scan for MSSQL

---

contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java
docs/dev/PluginCredentialsProvider.md
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/EnvCredentialsProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/UsernamePasswordCredentials.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/UsernamePasswordWithProxyCredentials.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/oauth/OAuthTokenCredentials.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/security/vault/VaultCredentialsProvider.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestVaultUserAuthenticator.java
exec/java-exec/src/test/java/org/apache/drill/storage/CredentialsProviderImplementationsTest.java
exec/java-exec/src/test/java/org/apache/drill/storage/CredentialsProviderSerDeTest.java
exec/java-exec/src/test/resources/vault/read-vault-secrets.hcl
logical/src/main/java/org/apache/drill/common/logical/security/CredentialsProvider.java
logical/src/main/java/org/apache/drill/common/logical/security/PlainCredentialsProvider.java

The VaultCredentialsProvider can join the PlainCredentialsProvider in supporting user credentials, credentials that stored for each each Drill query user and which are needed for the user_translation auth mode, by constructing a Vault secret path dynamically based on the name of the query user. A variable named `$user` in the VaultCredentialsProvider's `secretPath` is replaced with the query user's name at query time.
To be added once the new auth mode implementation has stabilised.
CredentialsProviderImplementationsTest::testVaultUserCredentialsPresent
CredentialsProviderImplementationsTest::testVaultUserCredentialsAbsent

DRILL-8232: Add support for user credentials to VaultCredentialsProvider

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/BufferManagerImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/UdfUtilities.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/ReaderState.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
exec/java-exec/src/test/java/org/apache/drill/test/OperatorFixture.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryBatchIterator.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryResultSet.java
exec/memory/base/src/main/java/org/apache/drill/exec/memory/BaseAllocator.java
exec/memory/base/src/main/java/org/apache/drill/exec/ops/BufferManager.java

* It updates HttpHelperFunctions to leverage JSON v2.
* Fixed possibility of memory leak for tests in `org.apache.drill.test.QueryBatchIterator`.
NA
TestHttpUDFFunctions still pass

DRILL-8236: Move HttpHelperFunctions to use JSON2 reader

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/SpnegoConfig.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberosEncryption.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoAuthentication.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoConfig.java
pom.xml

- Add the `maven.compiler.release` property to the jdk9+ profile, solving API errors like the missing `ByteBuffer` methods which are not covered by `maven.compiler.source` and `maven.compiler.target`.
- Remove calls to unsupported internal sun.security.* APIs that were blocking the use of `maven.compiler.release` for JDK 9+.
- Enable some Kerberos tests that were disabled but do work (partially resolves [DRILL-8036](https://issues.apache.org/jira/browse/DRILL-8036)).
N/A
Test building in JDK 8 and running in 8.
Test building in JDK 8 and running in 11.
Test building in JDK 11 and running in 8.
Test building in JDK 11 and running in 11.

DRILL-8113: Support building with a JDK 8 target using newer JDKs

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/DrillComplexWriterFuncHolder.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/BufferManagerImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectBatchBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectMemoryManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectionMaterializer.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/Projector.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectorTemplate.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ColumnBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/AbstractRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/record/BatchSchema.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/impl/VectorContainerWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/ComplexWriterImpl.java

- add test to check the http_get function output
- replacing List<ComplexWriter> with ResultSetLoader
[DRILL-8236](https://issues.apache.org/jira/browse/DRILL-8236) changed `HttpHelperFunctions` to use EVF based JSON v2 reader. But function output left old
NA
`TestHttpUDFFunctions#testHttpGetWithNoParams` test updated to check the function output

DRILL-8242: Fix output for HttpHelperFunctions

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpUdfUtils.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java

The `http_request` UDF was not passing down the provided schema and other config parameters down to the `jsonLoader`.
This bug fix corrects that.  
I created a new util class and moved some of the UDF logic there to allow for easier debugging.
Ran unit tests and added an additional unit test.

DRILL-8244: HTTP_Request Not Passing Down Config Variables

---

exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/ControlClient.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/ControlServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataClient.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/BootStrapContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
exec/java-exec/src/main/resources/drill-module.conf

As all the connection pairs between drillbits will share the same thread pool of netty, so I propose to at least sepatate data server from control client/server. Also changed the default threads number to power of two to benefit from PowerOfTwoEventExecutorChooser of Netty.
NA
Start two or more drillbits, see the query which uses two or more drillbits to scan can perform correctly.

DRILL-8132: Improvement of RPC

---

contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdParser.java
contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReader.java
contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReaderUserAgent.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushFilterPastProjectRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRel.java

Fixed `DrillScanRel` cost to prefer scan with the pushed project columns and removed a hack of adding a dynamic star to columns for the case of creating `DrillScanRel` using scan rule, so dependency on rules order is removed.
This change exposed another bug in httpd plugin, for some cases, it was dependent on the presence of a dynamic star, though a specific column was selected, fixed this issue here also.
NA
All unit tests pass.

DRILL-8245: Project pushdown depends on rules order and might not happen

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpUdfUtils.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
contrib/storage-http/src/test/resources/data/p4.json
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/JsonMessageReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/SingleElementIterator.java

Fixes the limiting of the `http_request` to 1 row. The main issue is in creating `jsonLoader` for every row.
NA
Unit test added. And tested manually with Drill Remote debug tool.

DRILL-8248: Fix http_request for several rows

---

contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatConfig.java
contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatPlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/DynamicSchemaFilter.java

The Excel format plugin is upgraded to use the EVF 2 framework.
N/A
Existing unit tests, manual testing.

DRILL-8199: Convert Excel EVF1 to EVF2

---

common/src/main/java/org/apache/drill/common/util/DrillFileUtils.java
contrib/native/client/src/include/drill/recordBatch.hpp
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestProvidedSchema.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java

Many build failures recently due to inability to start http servers - port already in use. 2 tests are using the same port.

[MINOR UPDATE] Fix Port Clash Issue in HTTP Plugin Tests

---

pom.xml

Relates to https://github.com/apache/drill/security/dependabot/21
Unknown
CI build

DRILL-8251: Upgrade Hadoop 2 Due to CVE

---

contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaGroupScan.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaRecordReader.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaScanBatchCreator.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaStoragePlugin.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaSubScan.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestQueryConstants.java

In the current implementation of the kafka storage, although we use the limit detection method in the result loader, but the actual `maxRecords` is always -1.
The mechanism for this revision is to get limit (SQL parsing from the execution plan stage) from the group scan, then pass it to the sub-scan, and finally process it in the result loader.
N/A
Added the unit test. KafkaQueriesTest#testResultLimit()

DRILL-8253: Support Limit Results in Kafka Scan

---

contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdParser.java
contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReader.java
contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReaderUserAgent.java
contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushFilterPastProjectRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/SpnegoConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcSort.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberosEncryption.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoAuthentication.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoConfig.java
pom.xml

Merged several backport-to-stable commits for new bugfix release 1.20.2, which includes:
* https://github.com/apache/drill/pull/2577
* https://github.com/apache/drill/pull/2572
* https://github.com/apache/drill/pull/2565
* https://github.com/apache/drill/pull/2564
Commit with backport-to-stable tag https://github.com/apache/drill/pull/2575, bases on commit https://github.com/apache/drill/pull/2516, which is a new feature after release 1.20. So excluded from this PR.
None.
UT

[BACKPORT-TO-STABLE] Bugfix Release 1.20.2 

---

contrib/storage-jdbc/pom.xml

Upgrade mysql-connectors-java to 8.0.28 due to CVE-2022-21363
Please refer to https://github.com/advisories/GHSA-g76j-4cxx-23h9
UT test

DRILL-8254: upgrade mysql-connectors-java to 8.0.28 due to CVE-2022-21363

---

.github/workflows/ci.yml
.travis.yml
common/src/test/java/org/apache/drill/categories/EasyOutOfMemory.java
common/src/test/java/org/apache/drill/categories/package-info.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/TestDrillbitResilience.java
pom.xml

1. ~~Increase the timeout of CI. Because of the number of fork is decreases from 2 to 1.~~  Be merged into other pull request.
2. ~~Set the `forkCount` to 1. Reduce the vm crash on fork start.~~
3. Remove the Junit 5 Annotation. No effect on the Junit 4.
4. Use "Info" as the default log level. Reduce log release time.
5. ~~Ignore the **TestSpnegoAuthentication**. After upgrading the surefire version and reducing the number of forks, the DRILL-5387 reproduces on the CI-JDK 8.~~
6. Split the unit test for `EasyOutOfMemory` categories. Use a clean JVM to test tricky unit.
7. Launch `drop_caches` to to recover memory (buffer/cache) before start-up test.
8. Remove `MySQL Cache` phase. Because JDBC used testcontainer, it is no longer needed, and can free up more memory.
N/A
All passed.

[Minor Update] Split category unit tests due to memory issues

---

exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReader.java

Thank you to @ArtTrush for finding and partially debugging this regression. The Parquet test file attached to the Jira issue cannot be queried with Drill 1.20.1 because it decides from column chunk metadata that a chunk does not use dictionary encoding and ignores new information found by the Parquet page reader that indicates that dictionary encoding is used. This fix restores the consideration of the `usingDictionary` flag which is updated by the page reader.
N/A
The Drill Test Framework contains a test query and file nation.dict.parquet that reveals this bug.

DRILL-8249: Parquet decoding error reading nation.dict.parquet from test framework

---

contrib/format-maprdb/pom.xml
contrib/storage-hbase/pom.xml
contrib/storage-hive/core/pom.xml
distribution/pom.xml
exec/java-exec/pom.xml
exec/rpc/pom.xml
logical/pom.xml
metastore/iceberg-metastore/pom.xml
metastore/metastore-api/pom.xml
pom.xml

The following transitive dependencies in Drill 1.20.* conflict with Drill's own, newer Netty dependencies and need to be excluded.
- jars/3rdparty/netty-transport-native-epoll-4.1.45.Final.jar
- jars/3rdparty/netty-all-4.1.59.Final.jar
- jars/3rdparty/netty-codec-http-4.1.59.Final.jar
This PR introduces a Netty BOM. Note that Drill in the past picked up a dependency on every Netty component (netty-all) through the OCI HDFS connector:
```
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ distribution ---
[INFO] org.apache.drill:distribution:pom:2.0.0-SNAPSHOT
[INFO] \- com.oracle.oci.sdk:oci-hdfs-connector:jar:3.3.0.7.0.1:compile
[INFO]    \- io.netty:netty-all:jar:4.1.73.Final:compile
```
N/A
Check versions of netty-* artifiacts in jars/3rdparty after building.
Manually run …

DRILL-8257: Resolve Netty lib conflicts

---

distribution/src/assemble/component.xml
docs/dev/Release.md
exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/VersionIterator.java
pom.xml

For context see [1] and [2]. The git-commit-id plugin includes information like build host, email and time which is not compatible with a reproducible build. Drill's built in sys.version table will return the build email and time if they are present in the build's git.properties file so these columns must be deprecated. Other useful Git-related information is retained.
In accompanying commits, ~~some Kerberos unit test fixes are applied, and the tests reenabled,~~ and some updates to Release.md are included.
[1] https://maven.apache.org/guides/mini/guide-reproducible-builds.html
[2] https://github.com/jvm-repo-rebuild/reproducible-central#org.apache.drill:drill-root
Update the Query System Tables doc page.
Run `select * from sys.version`. Manually inspect git.properties file.

DRILL-8158: Remove non-reproducible build outputs

---

exec/java-exec/src/main/java/org/apache/drill/exec/rpc/security/AuthenticatorProviderImpl.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberosEncryption.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoAuthentication.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoConfig.java
exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java

Minor bugs in some unit tests in org.apache.drill.exec.rpc.user.security have meant that they have been disabled historically to prevent causing CI failures.
N/A.
Fixed unit tests will run in CI.

DRILL-8256: Fix unit tests of Kerberos auth in RPC

---

exec/java-exec/pom.xml

DRILL-8263: upgrade libpam4j due to CVE

---

exec/java-exec/pom.xml
exec/jdbc/pom.xml
pom.xml

https://issues.apache.org/jira/browse/DRILL-8262
The mapr contrib component still pulls xalan transitively via https://mvnrepository.com/artifact/com.mapr.hadoop/maprfs/6.1.0-mapr

DRILL-8262: Remove Xalan Dependency

---

common/src/main/java/org/apache/drill/common/types/Types.java
exec/java-exec/src/test/java/org/apache/drill/TestUnionAll.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestVarlenDecimal.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MetadataUtils.java

The calculation of the decimal precision needed to encompass two input decimal precisions and scales can produce precisions greater than the maximums supported by Drill. While this does not affect the output vector itself, it does cause the error reported in the associated Jira if column metadata to be included with the result data is built using org.apache.drill.exec.record.metadata.MetadataUtils, as is done for queries sent over the REST interface. This PR limits the calculated precision to the maximum supported value when this happens and log a precision loss warning.
N/A
Manually run the repro query provided in the Jira.
New unit test TestTupleSchema:testDecimalWidening()

DRILL-7960: Column metadata DECIMAL precision can exceed max supported value

---

exec/java-exec/src/main/codegen/templates/AbstractRecordWriter.java
exec/java-exec/src/main/codegen/templates/EventBasedRecordWriter.java
exec/java-exec/src/main/codegen/templates/ParquetOutputRecordWriter.java
exec/java-exec/src/main/codegen/templates/RecordWriter.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java

DRILL-8272: Skip MAP column without children when creating parquet tables

---

common/src/main/java/org/apache/drill/exec/metrics/DrillMetrics.java
common/src/main/java/org/apache/drill/exec/metrics/MetricsCategory.java
exec/java-exec/src/main/resources/rest/index.ftl
exec/java-exec/src/main/resources/rest/metrics/metrics.ftl
exec/java-exec/src/main/resources/rest/static/css/drillStyle.css
pom.xml

1. Add classified prefix for metrics indicators like thread, heap, jvm and etc, so that user can easily make sense of each indicators.
2. Change the key reference of usage summary on Drill Web UI Main Page and Metrics page due to the key of each indicators has been changed. The usage can be shown correctly.
3. Drill Web UI Metrics page usage part cannot fully show the numbers if the bar isn't long enough.
After Optimized UI,
I will also update the corresponding Drill Doc later.
https://drill.apache.org/docs/monitoring-metrics/
Manually test and UT.

DRILL-8269: Classified metrics for easier maintenance

---

.github/workflows/ci.yml
contrib/format-maprdb/pom.xml
contrib/storage-hbase/pom.xml
contrib/storage-hive/core/pom.xml
contrib/storage-phoenix/pom.xml
distribution/pom.xml
docs/dev/Release.md
exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileBatchReader.java
exec/java-exec/src/main/resources/drill-module.conf
exec/jdbc-all/pom.xml
pom.xml
tools/release-scripts/release.sh

1. New exclusions of reload4j, slf4j-reload4j are required in the Hadoop 2 profile, probably due to the upgrade of Hadoop from 2.10.1 to 2.10.2.
2. We remove the netty-all metapackage which entered the dependency tree with the change introducing the Netty bom bringing many uneeded libs with it.
3. The heap memory usage limiting logic in the REST server becomes disabled by default since REST query results are streamed these days. This change aims to let the Java GC now do its job without interference and if that results in OOM under a constant load then there is good evidence for a heap leak which must be tracked and completely resolved anyway, not mitigated or "swept under a rug".
N/A
Lib exclusions: successful build and launch under the Hadoop 2 profile, check for the presence of Netty …

DRILL-8268: Fix Hadoop 2 and Netty lib exclusions, REST mem limiter disabled by default

---

contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestTupleProjection.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/DictColumnMetadata.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MapColumnMetadata.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/RepeatedListColumnMetadata.java
exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantColumnMetadata.java

A number of column metadata implementations drop column properties, including the wildcard exclusion property, when cloned with cloneEmpty. This PR makes those cloneEmpty methods copy the column properties too.
N/A
New additions in TestTupleProjection.

DRILL-8273: Complex typed columns cannot be made implicit

---

exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestTupleProjection.java

The first PR (#2615) did not cover all of the affected column types with unit testing. This PR extends the unit tests to dict, repeated list and variant column types.
N/A
This PR consists only of test code.

DRILL-8273: Complex typed columns cannot be made implicit (extend unit tests)

---

.github/workflows/ci.yml
.github/workflows/publish-snapshot.yml

It is possible to publish snapshot artifiacts from the current, unrelased version of Drill by using the mvn deploy goal. This publishes the aritifacts to https://repository.apache.org/content/repositories/snapshots/org/apache/drill. Developers who would like to program against these artifacts in anticipation of the upcoming release, say 2.0.0, can do so by adding the Apache snapshots repository to their project and dependency entries like
```
<dependency>
<groupId>org.apache.drill.exec</groupId>
<artifactId>drill-java-exec</artifactId>
<version>2.0.0-SNAPSHOT</version>
</dependency> 
```
New plugin authoring documentation once the question of feasability of developing plugins away from the Drill source tree is totally settled.
I've been testing the `mvn deploy` command from my dev …

DRILL-8277: Publish SNAPSHOT artifacts to the Apache snapshots repo from CI

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/RegexpUtil.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestSqlPatterns.java

The '.' character is added to the JAVA_REGEX_SPECIALS string in RegexpUtil (as has subsequently happened in the Calcite code that was originally copied to create this class).
It will now be possible to use '.' correctly in queries like `show databases where table_schema like 'dfs.%'`
No change.
TestSqlPatterns#testSqlRegexLike

DRILL-8278: The period character '.' is broken in SQL LIKE patterns

---

contrib/storage-splunk/pom.xml
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkGroupScan.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkScanSpec.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkSchemaFactory.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkStoragePlugin.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkSubScan.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/TestSplunkUserTranslation.java
pom.xml

Adds support for user translation in the Splunk plugin.
Not really much to add here.  Splunk plugin now supports user translation in a similar manner as the JDBC plugin. 
Added unit tests, tested manually.

DRILL-8276: Add Support for User Translation for Splunk Plugin

---

.github/workflows/ci.yml
contrib/storage-hive/core/pom.xml
contrib/storage-phoenix/README.md
contrib/storage-phoenix/pom.xml
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixDataSource.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixReader.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixStoragePlugin.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixStoragePluginConfig.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixImplementor.java
contrib/storage-phoenix/src/main/resources/bootstrap-storage-plugins.json
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixBaseTest.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixBasicsIT.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixSQLTest.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixTestSuite.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/ImpersonationPhoenixIT.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/PhoenixEnvironment.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixBaseTest.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixCommandTest.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixDataTypeTest.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixSQLTest.java
contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixTestSuite.java
contrib/storage-phoenix/src/test/resources/hbase-site.xml

`phoenix-queryserver-client` shades Avatica classes, so it causes issues when starting Drill and shaded class from phoenix jars is loaded before official Avatica, so Drill wouldn't be able to start correctly.
- Fixed Phoenix unit tests to run with general tests suite without any extra checks
- Added support for Phoenix thick client
- Removed usage of custom dependencies
To use fat client, storage plugin configs should be updated as described in https://github.com/apache/drill/compare/master...vvysotskyi:DRILL-8279?expand=1#diff-81178bb7d4498bc22f7c54e71462b460f95b80f40f85e74ff8f1cc7f69d34351
All unit tests pass, queried Phoenix using Drill.

DRILL-8279: Use thick Phoenix driver

---

contrib/storage-phoenix/pom.xml

Renamed property to skip tests to since they were also running with -DskipTests flag.
NA
Now check style job also skips phoenix tests.

DRILL-8279: Rename skip tests property to match maven-surefire property name

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/SchemaFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java

The merge_schema function in SchemaFunctions is modified to use UTF-8 string parsing so that a column with a name like "Käse" will no longer crash ANALYZE TABLE REFRESH METADATA.
N/A
TestMetastoreCommands#testNonAsciiColumnName

DRILL-8280: Cannot ANALYZE files containing non-ASCII column names

---

contrib/storage-hbase/pom.xml
contrib/storage-hive/core/pom.xml
distribution/pom.xml
drill-yarn/pom.xml
exec/java-exec/pom.xml
exec/rpc/pom.xml
exec/vector/pom.xml
logical/pom.xml
metastore/iceberg-metastore/pom.xml
metastore/metastore-api/pom.xml
pom.xml

There is a CVE fix in hadoop 3.2.4

DRILL-8282: Bump Hadoop-Common Version to 3.2.4 (CVE)

---

exec/java-exec/src/main/java/org/apache/drill/exec/coord/zk/ZKClusterCoordinator.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
exec/java-exec/src/test/java/org/apache/drill/exec/client/DrillClientStateTest.java

Use the ZK style on the connection string and the zkRoot does not match the actual path of the cluster, then the client always creates a spurious path (as a permanent) in the Zookeeper.
The reason is that after `CuratorFramework` creates the builder, if `zkRoot` is already specified (called `namespace` in curator), it will force to create the root path (even if the path is inconsistent with the real cluster).
As the result, many useless roots may be created in Zookeeper.
N/A
Added the tests.

DRILL-8275: Prevent the JDBC Client from creating spurious paths in Zookeeper

---

contrib/storage-http/README.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPushDownListener.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java

Some APIs will reject filter pushdowns if they are not in the correct case.  This PR adds a config option `caseSensitiveFilters` to the API config and when set to `true`, preserves the case of the filters pushed down. 
Updated docs.
Manually tested

DRILL-8291: Allow Case Sensitive Filters in HTTP Plugin

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/http/oauth/OAuthUtils.java

Adds close() calls in a number of places where HTTP requests are made in the HTTP storage plugin.
N/A

DRILL-8295: Probable resource leak in the HTTP storage plugin

---

distribution/docker-cluster-mode/Dockerfile
distribution/docker-cluster-mode/README
distribution/docker-cluster-mode/docker-compose.yml
distribution/docker-cluster-mode/drill-override.conf
distribution/docker-cluster-mode/logback.xml

This directory contains source code artifacts to launch Drill in cluster mode
along with a ZooKeeper. The Drill image is based on a minor customisation of
the official Drill image that switches it from an embedded to a cluster mode
launch. Logging is redirected to stdout.
In the docker-cluster-mode directory:
1. docker build -t apache/drill-cluster-mode
2. docker-compose up
Then access the web UI at http://localhost:8047 or connect a JDBC client to
jdbc:drill:drillbit=localhost or jdbc:drill:zk=localhost but note that you
will need to make the drillbit container hostnames resolvable from the host to 
use a ZooKeeper JDBC URL.
To launch a cluster of 3 Drillbits
3. docker-compose up --scale drillbit=3
but first note that to use docker-compose's "scale" feature to run multiple
Drillbit …

DRILL-8293: Add a docker-compose file to run Drill in cluster mode

---

contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpBatchReader.java
contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergWork.java
contrib/format-maprdb/src/main/java/org/apache/drill/exec/planner/index/MapRDBStatistics.java
contrib/format-maprdb/src/test/java/com/mapr/drill/maprdb/tests/index/TableIndexCmd.java
contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/rest/DruidQueryClientTest.java
contrib/storage-kudu/src/main/codegen/templates/KuduRecordWriter.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CharSequenceWrapper.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestSqlPatterns.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestCastFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/record/vector/TestValueVector.java
exec/vector/src/main/codegen/templates/VariableLengthVectors.java
exec/vector/src/main/java/org/apache/drill/exec/util/Text.java
exec/vector/src/test/java/org/apache/drill/exec/record/TestMaterializedField.java

Code tidy-up. Basically a subset of #2637 but with none of the changes that affect the char encoding used in existing conversions.
* uses of a pattern like `new String("aaaa")` - IntelliJ and other tools highlight this as unnecessary
* uses of `new String(bytes, StandardCharsets.UTF_8.name())` - better to use `new String(bytes, StandardCharsets.UTF_8)`
* use Base64 encodeToString instead of case where we encode to bytes and then do our own encoding of those bytes to a String
* Change existing code with `Charset.forName("UTF-8")` to use `StandardCharsets.UTF_8`

DRILL-8302: Tidy up some char conversions

---

contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsColumn.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsRangeBuilder.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsUtils.java
contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java

See below.
Adds the following implicit fields to GoogleSheets:
* `_sheets`:  Returns a list of available tabs within a GoogleSheets document.

DRILL-8305: Add Implicit Fields to Google Sheets Reader

---

logical/src/main/java/org/apache/drill/common/logical/FormatPluginConfig.java
logical/src/main/java/org/apache/drill/common/logical/StoragePluginConfig.java

Allows format and storage configs to be case insensitive.
N/A

DRILL-8271: Make Storage and Format Config Case Insensitive

---

contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasFormatPlugin.java

Converts SAS Format Plugin to EVF V2.   This is part of https://issues.apache.org/jira/browse/DRILL-8312. 
Ran existing unit tests

DRILL-8315: Convert SAS Format Plugin to EVF V2

---

contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcIntermediatePrelConverterRule.java
contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoProjectPushDown.java
contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixIntermediatePrelConverterRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdDistinctRowCount.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdMaxRowCount.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdRowCount.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdSelectivity.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/ColumnConverterFactoryProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/DynamicTypeResolverBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableBatchCreator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableSubScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/EnumerableIntermediatePrelConverterRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/VertexDrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/PluginAggregateRel.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/StoragePluginTableScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginIntermediatePrelConverterRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/util/Utilities.java

Improved costs calculation for vertex drel to consider resulting columns number in its cost to make plans with the pushed project more preferable.
Added `SINGLETON` to rel nodes for which execution cannot be distributed to several drillbits.
Fixed deserialization of `EnumerableSubScan`.
NA
Added unit test, existing tests pass.

DRILL-8190: Fix mongo project pushdown for queries with joins

---

contrib/storage-http/.gitignore
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPaginatorConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/IndexPaginator.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
contrib/storage-http/src/test/resources/data/nested_pagination_fields.json
contrib/storage-http/src/test/resources/data/nested_pagination_fields2.json
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureParser.java

In some cases that use keyset/index pagination, if the API does not have a boolean column that indicates when to stop, Drill will send requests until the API stops returning data.  This PR fixes this by making the boolean parameter optional.  
If that parameter is not present, if the index result is blank or the same as the previous request, pagination will end.
Note, if the pagination parameters are buried in nested objects, this cannot be configured with a `dataPath`.  If the user uses a `dataPath`, pagination will stop at the first page.
Added unit test and tested manually with Hubspot API.

DRILL-8320: Prevent Infinite Pagination for Index Paginator

---

contrib/format-excel/pom.xml
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestStringDistanceFunctions.java
pom.xml

(and excel-streaming-reader that has a transitive dependency on it)
Some important bugs fixed in latest version
Fixes include https://issues.apache.org/jira/browse/TEXT-191 and this affects one of the Drill tests - I fixed the test to match the new correct result from commons-text 1.10.0

DRILL-8323: upgrade commons-text to 1.10.0 

---

contrib/storage-kafka/pom.xml
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/MessageIterator.java

Move `org.apache.kafka.kafka_2.13` to test dependency scope. It prevents conflict between Scala versions of `org.apache.kafka.kafka_2.13` (Scala 2.13) and `com.madhukaraphatak.java-sizeof_2.11` (Scala 2.11). Solves such exceptions that could appear during Drill-On-Yarn startup:
```
Caused by: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.scala.DefaultScalaModule could not be instantiated
...
Caused by: java.lang.NoSuchMethodError: 'scala.collection.immutable.Seq$ scala.package$.Seq()'
```
Also, it cleans Drill's classpath from unnecessary dependencies.
Probably `org.apache.kafka.kafka_2.13` was added to compile scope by mistake. 
No changes.
Unit tests pass successfully. Tried to connect to Kafka and read a topic - …

DRILL-8321: Change kafka_2.13 dependency scope to test

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java

The HTTP plugin has the ability to cache API responses.  However, the storage plugin was not closing the connection to the file cache.  This minor PR fixes that. 

DRILL-8329: Close HTTP Caching Resources

---

contrib/format-esri/pom.xml
contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpBatchReader.java
contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpFormatPlugin.java

Converts the ESRI Shape File Reader to EVF V2.  

DRILL-8330:  Convert ESRI Shape File Reader to EVF2

---

contrib/native/client/src/protobuf/UserBitShared.pb.cc
contrib/native/client/src/protobuf/UserBitShared.pb.h
exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/AnalyzeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/CreateTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DefaultSqlHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ExplainHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/MetastoreAnalyzeTableHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/SqlHandlerConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/Foreman.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/foreman/QueryManager.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestQueryProfiles.java
logical/src/main/java/org/apache/drill/common/logical/PlanProperties.java
protocol/src/main/java/org/apache/drill/exec/proto/SchemaUserBitShared.java
protocol/src/main/java/org/apache/drill/exec/proto/UserBitShared.java
protocol/src/main/protobuf/UserBitShared.proto

A useful piece of information about a query is the set of plugins that it attempted to scan. While some such information is present in the physical plan text in the query profile, an easy to parse, sorted and deduplicated list of plugin names is not. This PR adds such a list.
Query profile fragment including the new scannedPlugins array
```
"user": "alice",
"optionsJson": "[ {\n  \"kind\" : \"BOOLEAN\",\n  \"accessibleScopes\" : \"ALL\",\n  \"name\" : \"metastore.enabled\",\n  \"bool_val\" : false,\n  \"scope\" : \"QUERY\"\n} ]",
"planEnd": 1664464547555,
"queueWaitEnd": 1664464547555,
"totalCost": 260,
"queueName": "Unknown",
"queryId": "1cca495d-6dcd-4620-8027-0cf056e3b5bc",
"scannedPlugins": [
"cp",
"dfs",
"sys"
]
```
~~Add an entry to …

DRILL-8322: Add a list of scanned plugin names to the query profile

---

contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfFormatPlugin.java
contrib/format-pdf/src/test/java/org/apache/drill/exec/store/pdf/TestPdfFormat.java

Converts the PDF Format reader to use EVF V2. 
Ran existing unit tests.  For star queries, it seemed that EVF2 doesn't always return columns in the same order, so I had to refactor one unit test.

DRILL-8325: Convert PDF Format Plugin to EVF V2

---

contrib/storage-googlesheets/.gitignore
contrib/storage-googlesheets/README.md
contrib/storage-googlesheets/pom.xml
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/DrillDataStore.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePlugin.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsRootSchema.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsSchemaFactory.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsUtils.java
contrib/storage-googlesheets/src/main/resources/bootstrap-storage-plugins.json
contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java

GoogleSheets (GS) was not reporting available documents to the information schema.  This PR fixes that so that users are now able to query the information_schema to find a list of available documents.  
Note that it is not possible to populate the tabs into the information schema due to Google's rate limits.  If this was populated, it would be very easy for a user with a few dozen files to exceed the rate limit.   Users can obtain the list of available sheets by using the `_sheets` implicit column.
This PR also fixes a major bug in the `DrillDataStore` for OAuth2.0 tokens which was preventing access and refresh tokens from being stored properly.   Instead of storing the actual values, Drill was storing a text version of the `byte[]`.  
Updated README.
Ran existing unit tests and added two …

DRILL-8327: GoogleSheets not Reporting Schemata to Info_Schema

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFWithAliases.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/PlannerSettings.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/metadata/ServerMetaProvider.java
exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java

This PR fixes a bug with the `http_request` UDF.    Previously, the UDF was not resolving aliases.  This PR fixes that and allows the UDF to resolve aliases if enabled.  It maintains the priority of user alias over public alias. 
No user facing documentation needed.

DRILL-8328: HTTP UDF Not Resolving Storage Aliases

---

pom.xml

There are 1 security vulnerabilities found in org.freemarker:freemarker 2.3.28
- [MPS-2022-12438](https://www.oscs1024.com/hd/MPS-2022-12438)
Upgrade org.freemarker:freemarker from 2.3.28 to 2.3.30 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

[MINOR UPDATE]: Upgrade org.freemarker:freemarker to 2.3.30

---

contrib/storage-kafka/pom.xml

There are 1 security vulnerabilities found in org.apache.kafka:kafka_2.13 2.8.0
- [CVE-2022-34917](https://nvd.nist.gov/vuln/detail/CVE-2022-34917)
Upgrade org.apache.kafka:kafka_2.13 from 2.8.0 to 2.8.2 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

[MINOR UPDATE]: Upgrade org.apache.kafka:kafka_2.13 to 2.8.2

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpUdfUtils.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/JsonMessageReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/ClosingStreamIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java

The JsonLoader can be built to parse from a stream, as it is by the HTTP storage plugin. Given the lifecycles of the objects involved, it is the loader that should be responsible for closing any streams that it is constructed from once JSON parsing is complete and the loader itself is closed.
N/A
Monitor fd leakage using the lsof program on Linux while querying an HTTP plugin directly or through HTTP UDFs.

DRILL-8333: Resource leak when JsonLoader is built from a stream

---

contrib/format-image/pom.xml

There are 1 security vulnerabilities found in com.drewnoakes:metadata-extractor 2.17.0
- [CVE-2022-24614](https://www.oscs1024.com/hd/CVE-2022-24614)
Upgrade com.drewnoakes:metadata-extractor from 2.17.0 to 2.18.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade com.drewnoakes:metadata-extractor to 2.18.0

---

contrib/storage-opentsdb/pom.xml
contrib/storage-opentsdb/src/main/java/org/apache/drill/exec/store/openTSDB/OpenTSDBGroupScan.java
contrib/storage-opentsdb/src/main/java/org/apache/drill/exec/store/openTSDB/SizeEstimator.java
contrib/storage-opentsdb/src/test/java/org/apache/drill/exec/store/openTSDB/TestDataHolder.java
contrib/storage-opentsdb/src/test/java/org/apache/drill/exec/store/openTSDB/TestOpenTSDBPlugin.java
contrib/storage-opentsdb/src/test/java/org/apache/drill/exec/store/openTSDB/TestSizeEstimator.java

Remove use of java-sizeof jar. It is an old copy of Spark code. I have ported the latest Spark code to Java and inlined it.

DRILL-8324: sizeof refactor

---

contrib/storage-hive/core/pom.xml
pom.xml

https://ds-3p.sonatype.com/assets/index.html#/vulnerabilities/sonatype-2019-0400
N/A
Hive plugin unit tests.

DRILL-8337: Upgrade Hive libs to 3.1.3 due to sonatype-2019-0400

---

contrib/storage-googlesheets/README.md
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/DrillDataStore.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java

This PR adds the ability to query Google Sheets tabs by index rather than by name.   
Updated docs.
If you don't know the names of the available tabs in your GoogleSheets document, you can query the sheets by index using the `tab[n]` format.  Indexing starts at zero and every Sheets document must have at least one sheet.  Note that this must be enclosed in backticks.
```sql
SELECT * 
FROM googlesheets.<sheet id>.`tab[0]`
```
Added additional unit tests.

DRILL-8335: Add Ability to Query GoogleSheets Tabs by Index

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ProfileInfoIterator.java
exec/java-exec/src/test/java/org/apache/drill/exec/work/metadata/TestMetadataProvider.java

In [DRILL-8322](https://issues.apache.org/jira/browse/DRILL-8322), @jnturton added the list of scanned plugins to the query profiles.  This information is extremely useful in query analysis.  This minor PR adds this same information to the sys.profiles table.
Adds two fields to the `sys.profiles` table: 
*  `pluginCount`: Returns the number of plugins scanned in the query
* `pluginList`: Returns the actual plugins.  Note this is a JSON String, not an actual list. 
```
apache drill> select pluginCount, pluginList, query from sys.profiles limit 2;
+-------------+------------+------------------------------------+
| pluginCount | pluginList |               query                |
+-------------+------------+------------------------------------+
| 1           | [sys]      | …
```

DRILL-8341: Add Scanned Plugin List to Sys Profiles Table

---

contrib/storage-http/Pagination.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFWithAliases.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestProvidedSchema.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java

Many APIs have a burst limit for number of requests.  This PR adds a retry capability to the HTTP Storage Plugin, whereby if a 429 response code is received, Drill will wait a configurable amount of time, and retry the request once. 
To prevent runaway pagination, this retry will only happen once per request. 
This PR adds a new configuration option called retryDelay which is the number of milliseconds that Drill should wait between retrys.
When using automatic pagination, you may encounter APIs that have burst limits or other limits as to the maximum number of requests in a minute or other amount of time.  Drill allows you to set a `retryDelay` parameter which is the number of milliseconds that Drill should wait before resending the request.  This defaults to 1 second.  This option is …

DRILL-8342: Add Automatic Retry for Rate Limited APIs

---

contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePlugin.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/oauth/OAuthTokenProvider.java
exec/java-exec/src/main/java/org/apache/drill/exec/oauth/PersistentTokenRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/oauth/TokenRegistry.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/OAuthRequests.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
exec/java-exec/src/main/resources/rest/storage/update.ftl

Attempting to delete a disabled storage plugin fails due to code that tries to clean up its OAuth token registries in the process.
N/A
Manually delete a disabled storage plugin in the web UI.

DRILL-8348: Cannot delete disabled storage plugins

---

contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsSchemaFactory.java

GoogleSheets plugin fails to register plugin instances with names other than `GoogleSheets`. 
Tested manually and ran existing unit tests.

DRILL-8349: GoogleSheets Not Registering Schemas with Non Default Name

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/MetadataContext.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/metadata/Metadata.java

The Map dirModifCheckMap is keyed using a HDFS Path instance, not a string. This updates accessing code accordingly.
N/A

DRILL-8299: HashMap key type mismatch in MetadataContext

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/RexToMongoTranslator.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestConstants.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoFilterPushDown.java
contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoProjectPushDown.java

Add translations of IS NULL and IS NOT NULL to $eq( , null) and $ne( , null) respectively. Note that $eq(x, null) matches records where x is missing _or_ x is null  while $ne(x, null) matches records where x is present _and_ x is not null making the second condition the logical negation of the first and preserving the SQL operator identity IS NOT NULL = NOT IS NULL.
N/A
TestMongoProjectPushdown#testOperatorsProject

DRILL-8238: Translation of IS NOT NULL($1) is not supported by MongoProject

---

contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkQueryBuilder.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkUtils.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSplunkUtils.java

```
if (path.nameEquals("**")) {
return true;
} else {
return specialFields.contains(path.getAsNamePart());
}
```
LGTM and IntelliJ both say that NamePart type does not match the type stored in specialFields collection. This change refactors the code handling special fields.
N/A
Splunk plugin unit tests.

DRILL-8296: Possible type mismatch bug in SplunkBatchReader

---

exec/java-exec/src/main/codegen/templates/IsEmptyDataFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/IsEmptyScalarFunctions.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/IsEmptyUtils.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestIsEmptyFunctions.java
exec/java-exec/src/test/resources/jsoninput/is_empty_tests.json

When analyzing data, there is currently no single function to evaluate whether a given field is empty.  With scalar fields, this can be accomplished with the `IS NOT NULL` operator, but with complex fields, this is more challenging as complex fields are never null. 
This PR adds a UDF called `IS_EMPTY()` which accepts any type of field and returns true if the field does not contain data.  
In the case of scalar fields, if the field is `null` this returns true.  In the case of complex fields, which can never be `null`, in the case of lists, the function returns true if the list is empty.  In the case of maps, it returns true if all of the map's fields are unpopulated. 
I will update the documentation once this is merged.

DRILL-8354: Add IS_EMPTY Function

---

contrib/storage-googlesheets/README.md
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsScanSpec.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsRootSchema.java
contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java

GoogleSheets uses tokens to identify the individual files.  These tokens are not human readable and will make it difficult for a user to know which file they are accessing.  
This PR adds a metadata field called `_title` which identifies the document they are working with.
Updated README.

DRILL-8356: Add File Name to GoogleSheets Plugin

---

contrib/storage-splunk/pom.xml
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkIndexesTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
exec/java-exec/src/main/resources/drill-module.conf

The Splunk SDK and testcontainer are upgraded to 1.9.1 and 9 respectively. New config options supported by the Splunk SDK are added. None are required and none are present in the Splunk config template.
| Name                 | Description                                                     |
| -------------------- | --------------------------------------------------------------- |
| scheme             | The scheme with which to access the Splunk host.          |
| app                  | The application context of the service.                         |
| owner                | The owner context of the service.                               |
| token                | A Splunk authentication token to use for the session.           |
| cookie               | A valid login cookie. …

DRILL-8357: Add new config options to the Splunk storage plugin

---

contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateConversionUtils.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateFunctions.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateUtilFunctions.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDateFunctions.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDateUtils.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestNearestDateFunctions.java
exec/java-exec/src/main/codegen/data/ExtractTypes.tdd
exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/Extract.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
exec/vector/src/main/java/org/apache/drill/exec/vector/DateUtilities.java

See below.
This PR adds several utility functions to facilitate working with dates and times.  These are modeled after the date/time functionality in MySQL.  Due to the new casting updates, these functions will work with strings, dates or timestamps without the need to explicitly cast the input to a temporal type.
Specifically this adds:
* `DAYOFWEEK(<date>)`: Returns the day of the week 1-7 per SQL standard.
* `DAYOFYEAR(<date>)`: Returns the day of the year. 
* `TO_TIMESTAMP(<date string>)`:  Converts most anything that looks like a date string into a timestamp.
* `QUARTER(<date>)`:  Returns the quarter of the date/time.
Additionally, `DAYOFWEEK`, `DAYOFYEAR`, `QUARTER`, and `EPOCH`  are now available in the `EXTRACT` function.  

DRILL-8340: Add Additional Date Manipulation Functions

---

contrib/storage-jdbc/pom.xml

* https://issues.apache.org/jira/browse/DRILL-8363
* https://github.com/advisories/GHSA-562r-vg33-8x8h

DRILL-8363: upgrade postgresql to 42.4.3 due to security issue

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java

This PR fixes a bug when a user configures a HTTP plugin with the `requireTail` option.  The plugin was putting the URL parameters in the wrong place when pagination is used.  This fixes that.
N/A
Added unit test and ran existing unit tests.

DRILL-8365: HTTP Plugin Places Parameters in Wrong Place

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java

The Parquet writer waits until the end of the entire write before releasing its compression codec factory. The factory in turn releases compressors which release direct memory buffers used during compression. This deferred release leads a build up of direct memory use and can cause large write jobs to fail. The Parquet writer can instead release the abovementioned each time that a file/row group is flushed.
N/A
Manually confirm the release of allocated compression buffers after each flush in the debug log output.
Manually monitor memory usage during a big Parquet write job.

DRILL-8366: Late release of compressor memory in the Parquet writer

---

pom.xml

Updating dependency because of https://github.com/nielsbasjes/yauaa/security/advisories/GHSA-c4pm-63cg-9j7h

DRILL-8368: Update Yauaa to 7.9.0

---

contrib/format-deltalake/README.md
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/DeltaGroupScan.java
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/format/DeltaFormatPluginConfig.java
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/snapshot/DeltaLatestSnapshot.java
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/snapshot/DeltaSnapshot.java
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/snapshot/DeltaSnapshotByTimestamp.java
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/snapshot/DeltaSnapshotByVersion.java
contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/snapshot/DeltaSnapshotFactory.java
contrib/format-deltalake/src/test/java/org/apache/drill/exec/store/delta/DeltaQueriesTest.java

Added functionality for querying specific Delta Lake data versions.
See README.md
Added UT.

DRILL-8369: Add support for querying DeltaLake snapshots by version

---

exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/AbstractStoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ClassicConnectorLocator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePlugin.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemConfig.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemPlugin.java
exec/java-exec/src/main/resources/drill-module.conf
exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
exec/java-exec/src/test/java/org/apache/drill/exec/store/BoxFileSystemTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestMountCommand.java

Optional mount and unmount commands are added to the filesystem plugin with the goal of enabling the dynamic definition of filesystem mounts in the storage configuration. It is mainly anticpiated that network and cloud filesystems that have FUSE drivers (sshfs, davfs, rclone, ...) will be used in this way but local device mounts and image/loop device mounts (ISO, IMG, squashfs, etc.) might also be of interest. Filesystems that can be mounted in this way become queryable by Drill without the burden of dedicated storage plugin development.
The provided commands are executed in their own processes by the host OS and run under the OS user that is running the Drill JVM. The mount command will be executed when an enabled plugin is initialised (something that is done lazily) and when it …

DRILL-8359: Add mount and unmount command support to the filesystem plugin

---

contrib/format-image/pom.xml
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-kafka/pom.xml
contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/JsonMessageReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/ClosingStreamIterator.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
pom.xml

Merges the following backport-to-stable commits into the 1.20 branch:
* https://github.com/apache/drill/pull/2666
* https://github.com/apache/drill/pull/2669
* https://github.com/apache/drill/pull/2674
* https://github.com/apache/drill/pull/2675
* https://github.com/apache/drill/pull/2676
* https://github.com/apache/drill/pull/2677
* https://github.com/apache/drill/pull/2678
* https://github.com/apache/drill/pull/2682
N/A
UT

[BACKPORT-TO-STABLE] Bugfix Release 1.20.3 Phase 4

---

docs/dev/Release.md
pom.xml
tools/release-scripts/release.sh

While [DRILL-8113](https://issues.apache.org/jira/browse/DRILL-8113) enabled the building of Drill using a modern JDK, more work is required to enable a Maven release of Drill using a modern JDK. Presently, the Maven Release Plugin will fail on Javadoc generation when run with a newer JDK while it succeeds with JDK 8. The failures are due to dependencies missing from the Maven Javadoc Plugin's config which I assume get treated with a more lenient "warn and skip" policy in the javadoc tool shipped with JDK 8 but cause errors in newer JDKs (in my case OpenJDK 17).
In particular, the presence of the `sourcepath` property in the javadoc plugin's config in the root pom causes the default javadoc:javadoc goal to try to generate docs for our src/test packages. Unlike the javadoc:test-javadoc, …

DRILL-8378: Support doing Maven releases using modern JDKs

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/AggPrelBase.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java

For the case when filtering expression is specified, Drill will generate an `if` expression to obtain field value that will be used in aggregate function only when the filter predicate is true. Filter expression specified within an aggregate function is present in the underlying project, so it is enough to get a reference to it to use it as a condition.
NA
Added UT.

DRILL-8381: Add support for filtered aggregate calls

---

contrib/storage-cassandra/README.md
contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStorageConfig.java
contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStoragePlugin.java
contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/schema/CassandraRootDrillSchemaFactory.java
contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/BaseCassandraTest.java
contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraUserTranslationTest.java
contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuite.java
contrib/storage-splunk/README.md

Adds support for user translation for Apache Cassandra.
Updated README.

DRILL-8386: Add Support for User Translation for Cassandra

---

contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraUserTranslationTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/TestSplunkUserTranslation.java

This minor modification to the Splunk unit tests clears for user translation explicitly clears the result sets.  During some other work, I found that these tests would occasionally fail.   This fixes that.

[MINOR UPDATE]: Clear Results after Splunk Unit Tests

---

contrib/format-pdf/README.md
contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfMetadataReader.java
contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfRowIterator.java
contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfUtils.java
contrib/format-pdf/src/test/java/org/apache/drill/exec/store/pdf/TestPdfFormat.java

This PR makes some minor improvements to the PDF reader including:
* Fixes a minor bug where certain configurations the first row of data was skipped
* Fixes a minor bug where empty tables were causing crashes with the spreadsheet extraction algorithm was used
* Adds a `_table_count` metadata field
* Adds a `_table_index` metadata field to reflect the current table.
See above.  Updated README.
Ran existing unit tests.  Manually tested against customer data.

DRILL-8390:  Minor Improvements to PDF Reader

---

drill-yarn/src/main/resources/drill-am/login.ftl
exec/java-exec/src/main/resources/rest/login.ftl

In order to avoid triggering security scanners it is necessary to set autocomplete = "off" on the password field in the web UI login forms. This change probably has no real world security benefit (or cost) because
> Even without a master password, in-browser password management is generally seen as a net gain for security. Since users do not have to remember passwords that the browser stores for them, they are able to choose stronger passwords than they would otherwise.
> 
> For this reason, many modern browsers do not support autocomplete="off" for login fields:
> 
> - If a site sets autocomplete="off" for a form, and the form includes username and password input fields, then the browser still offers to remember this login, and if the user agrees, the browser will autofill those fields …

DRILL-8391: Disable auto complete on the password field of web UI login forms

---

contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java

In certain conditions, Drill will generate an Index Out of Bounds exception.  This minor PR fixes that.  Basically, when a schema is not provided, Drill will ignore empty cells in rows. 
Ran existing unit tests and tested with customer data.

DRILL-8392: Empty Tables Causes Index Out of Bounds Exception on PDF Reader

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/limit/LimitRecordBatch.java
exec/java-exec/src/test/java/org/apache/drill/TestBugFixes.java

With the following data layout
```
/tmp/foo
├──a
│  └──test_data.csvh
└──b
└──test_data.csvh
```
a LIMIT 0 query over it results in unfreed buffer errors as shown below.
```
apache drill (dfs.tmp)> select * from `foo` limit 0;
Error: SYSTEM ERROR: IllegalStateException: Allocator[op:0:0:4:EasySubScan] closed with outstanding buffers allocated (3).
Allocator(op:0:0:4:EasySubScan) 1000000/299008/3182592/10000000000 (res/actual/peak/limit)
child allocators: 0
ledgers: 3
ledger[113] allocator: op:0:0:4:EasySubScan), isOwning: true, size: 262144, references: 1, life: 277785186322881..0, allocatorManager: [109, life: 277785186258906..0] holds 1 buffers.
DrillBuf[142], udle: [110 0..262144]
ledger[114] allocator: op:0:0:4:EasySubScan), isOwning: true, size: 32768, references: 1, life: …
```

DRILL-8372: Unfreed buffers when running a LIMIT 0 query over delimited text

---

contrib/storage-hive/hive-exec-shade/pom.xml
exec/java-exec/pom.xml
exec/jdbc/pom.xml
pom.xml

- logback 1.2.11 → 1.4.5.
- log4j 2.18.0 → 2.19.0.
- slf4j 1.7.26 → 2.0.6.
N/A
Run embedded Drill and check its log output.

DRILL-8309: Upgrade slf4j to 2.0.x

---

common/src/test/resources/logback-test.xml
distribution/docker-cluster-mode/logback.xml
distribution/src/main/resources/logback.xml
drill-yarn/src/test/resources/doy-test-logback.xml

Replaced the `level` tag with the attribute, so no extra output is printed to the console.
NA
Checked manually

DRILL-8397: Drill prints warnings to console when starting it

---

pom.xml

As it turned out, Checkstyle 10.x version is supported only on JDK 11+ (https://checkstyle.org/#JRE_and_JDK), so it causes failures when attempting to build Drill on JDK 8. We didn't notice it because CI doesn't use JDK 8 (though it should).
To fix it, I have replaced it with the `checkstyle-backport-jre8` library which works fine on JDK 8 and is referenced in the official docs: https://checkstyle.org/#Backport
Also, logback 1.4.x doesn't work with JDK 8, decreased it to 1.3.5. See https://logback.qos.ch/dependencies.html
NA

DRILL-8396: Checkstyle plugin works only with JDK 11+

---

contrib/format-access/src/main/java/org/apache/drill/exec/store/msaccess/MSAccessBatchReader.java
contrib/format-access/src/test/java/org/apache/drill/exec/store/msaccess/TestMSAccessReader.java

Minor bug fix.  Drill was misinterpreting some data types in MS Access files.  This fixes that.
N/A

DRILL-8399: MS Access Reader Misinterprets Data Types

---

.github/workflows/ci.yml
contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveStoragePlugin.java
contrib/storage-hive/core/src/test/java/org/apache/drill/exec/TestHivePartitionPruning.java
contrib/storage-phoenix/pom.xml
exec/java-exec/src/test/java/org/apache/drill/TestTpchDistributedConcurrent.java
exec/java-exec/src/test/java/org/apache/drill/exec/server/TestDrillbitResilience.java
pom.xml

Added `actions/setup-java` action to use dedicated java version for tests instead of using provided with the instance one. This PR is based on the commit for DRILL-8396 to avoid early failures for JDK 8. 
Need to fix hive tests that were broken earlier (because they run only with JDK 8).
NA
TBA

DRILL-8398: Fix GitHub Actions to use proper JDK version

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java

This extends the work of [DRILL-8272](https://issues.apache.org/jira/browse/DRILL-8272) in order to handle nested empty MAPs which currently also break the Parquet writer.
N/A
Extension of TestParquetWriter#testResultWithEmptyMap

DRILL-8401: Skip nested MAP column without children when creating parquet tables

---

exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillReduceAggregatesRule.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/AggPrelBase.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java

Passing filters to agg calls when applying agg reduce rule.
NA
Added UT.

DRILL-8403: Generated aggregate function calls are missing required filters when used with PIVOT

---

.asf.yaml

Per suggestion from Christofer Dutz at ASF, we can add these template subjects to github emails which will facilitate people actually being able to organize and read them.

[MINOR UPDATE] Add Email Templates to ASF.yml

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CharSequenceWrapper.java
exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestRegexpFunctions.java

Adds `regexp_extract` functions to Drill.
This PR adds support for `regexp_extract(<text>, <pattern>)` which returns an array of text corresponding with the capturing groups in the regex.  It also includes `regexp_extract(<text>, <pattern>, <index>)` which returns the text of a specific capturing group.
```sql
SELECT regexp_extract('123-456-789', '([0-9]{3})-([0-9]{3})-([0-9]{3})');
+---------------------+
|       EXPR$0        |
+---------------------+
| ["123","456","789"] |
+---------------------+
SELECT regexp_extract('123-456-789', '([0-9]{3})-([0-9]{3})-([0-9]{3})', 0);
+-------------+
|   EXPR$0    |
+-------------+
| 123-456-789 |
+-------------+
SELECT regexp_extract('123-456-789', '([0-9]{3})-([0-9]{3})-([0-9]{3})', 3);
+--------+
| EXPR$0 |
+--------+
| 789    |
+--------+
``` …

DRILL-8402: Add REGEXP_EXTRACT Function

---

metastore/rdbms-metastore/pom.xml
pom.xml

upgrade to snakeyaml 2.0 due to CVE - also upgrades liquibase jar because we need a version of that jar that supports newer APIs of snakeyaml
CI build

DRILL-8405: Upgrade to snakeyaml 2.0 due to CVE

---

common/src/main/java/org/apache/drill/common/Typifier.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/columns/GoogleSheetsColumnWriter.java
contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsRangeBuilder.java
contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java

The GoogleSheets reader hits the batch limit from the GoogleSheets SDK of 1000 rows and stops.   This PR fixes that.  
It also fixes a minor but annoying issue whereby the GoogleSheets reader determines a column is a date/time, but is then unable to parse it because it is in a non-standard format.
N/A
Ran existing unit tests and tested manually.

DRILL-8411: GoogleSheets Reader Will Not Read More than 1K Rows

---

contrib/udfs/README.md
contrib/udfs/pom.xml
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DNSFunctions.java
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DNSUtils.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDNSFunctions.java
pom.xml

See below
These functions enable DNS research using Drill.
* `getHostName(<IP address>)`:  Returns the host name associated with an IP address.
* `getHostAddress(<host>)`:  Returns an IP address associated with a host name.
* `dnsLookup(<host>, [<Resolver>])`:  Performs a DNS lookup on a given host.  You can optionally provide a resolver.  Possible resolver values are: `cloudflare`,  `cloudflare_secondary`, `google`, `google_secondary`, `verisign`, `verisign_secondary`, `yandex`, `yandex_secondary`.
* `whois(<host>, [<Resolver>])`:  Performs a whois lookup on the given host name.  You can optionally provide a resolver URL. Note that not all providers allow bulk automated whois lookups, so please follow the terms fo service for your provider.

DRILL-8413: Add DNS Lookup Functions

---

exec/java-exec/pom.xml
exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/ControllerImpl.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataConnectionCreator.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
exec/java-exec/src/main/java/org/apache/drill/exec/service/ServiceEngine.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetRecordReader.java
exec/java-exec/src/main/java/org/apache/parquet/hadoop/ParquetColumnChunkPageWriteStore.java
exec/java-exec/src/main/resources/drill-module.conf
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitRpc.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/BasicServer.java

Drill provides the DRILL_HOST_NAME env var which determines what Drillbit host name will be exchanged over RPC for later look up by a remote client or Drillbit. This host name is used to check whether Drill is being asked to bind to the loopback address in distributed mode
```
if (isDistributedMode && InetAddress.getByName(hostName).isLoopbackAddress()) {
throw new DrillbitStartupException("Drillbit is disallowed to bind to loopback address in distributed mode.");
}
```
but is not ever used set the bind address used for the Drillbit's RPC and web ports! This PR adds new boot options
```
drill.exec.rpc.bind_addr
drill.exec.http.bind_addr
```
and uses them to set the bind addresses used for RPC services and the HTTP service respectively.
Document all three of DRILL_HOST_NAME and the two new …

DRILL-8409: Support the configuration of bind addresses for network services

---

.github/workflows/ci.yml
contrib/storage-splunk/pom.xml
distribution/src/main/resources/drill-override-example.conf
exec/java-exec/src/test/resources/drill-udf/pom.xml
pom.xml

- Set drill.version in drill-udf/pom.xml to 1.22.0-SNAPSHOT.
- Drop conjars repository.
- Upgrade parquet to 1.12.3 and parquet-format to 2.9.0.
- Move Splunk Maven repository declaration to contrib/storage-splunk/pom.xml.
- Revert ci.yml to ubuntu-latest.
- Add RPC and HTTP bind address lines to drill-override-example.conf.

[MINOR-UPDATE]: Drop conjars repo and revert ci.yml runner image to ubuntu-latest

---

.gitignore
.mvn/extensions.xml
distribution/pom.xml
exec/java-exec/src/main/codegen/templates/Parser.jj
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/conversion/DrillRexBuilder.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestCastFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
pom.xml

Resolves the current CI test failues affecting decimal and empty-literal-to-null casting. Also incorporates upstream syntax additions in Drill's Parser.jj which can only be dropped when [CALCITE-5579](https://issues.apache.org/jira/browse/CALCITE-5579) is resolved.
* Incorporate method signature changes in RexBuilder made by CALCITE-5557.
* Fix float rounding error in TestCastFunctions.testCastFloatDecimalOverflow.
* Incorporate Calcite parser changes.
* [CALCITE-5557] Add SAFE_CAST function (enabled in BigQuery library)
* [CALCITE-5548] Add MSSQL-style CONVERT function (enabled in MSSql library)
* [CALCITE-5554] In EXTRACT function, add DAYOFWEEK and DAYOFYEAR as synonyms for DOW, DOY
* Ignore .mvn/maven.config.
* Upgrade Apache RAT plugin.
* Upgrade os-maven-plugin.
* Move distro …

DRILL-8424: Accommodate RexBuilder changes made for SAFE_CAST

---

contrib/storage-elasticsearch/README.md
contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
contrib/storage-elasticsearch/src/main/resources/bootstrap-storage-plugins.json
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticComplexTypesTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticInfoSchemaTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchPlanTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchUserTranslationTest.java

Adds a config option to the ElasticSearch plugin, `disableSSLVerification` which disables SSL verification.  Defaults to `false`.
See above. 
Updated unit tests.

DRILL-8385: Add support for disabling SSL certificate verification in the Elasticsearch plugin

---

contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java

This PR fixes a minor issue with the ElasticSearch storage plugin whereby certain config variables were not saved.
Ran unit tests

DRILL-8428: ElasticSearch Config Missing Getters

---

contrib/udfs/README.md
contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DistributionFunctions.java
contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDistributionFunctions.java

Adds a new UDF, `percent_change(x,y)` which calculates the percent change between the two variables.  While this is relatively easy to do in SQL, it also requires null and zero checks to prevent division by zero errors.  This makes this calculation simpler.
See README.

DRILL-8433: Add Percent Change UDF to Drill

---

exec/java-exec/src/main/codegen/templates/Parser.jj
exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/conversion/DrillRexBuilder.java
exec/java-exec/src/main/java/org/apache/drill/exec/resolver/ResolverTypePrecedence.java
exec/java-exec/src/test/java/org/apache/drill/TestImplicitCasting.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestTimestampAddDiffFunctions.java
pom.xml

Unfortunately the experiment to depend on the latest snapshot of the Calcite main branch has resulted in too much breakage, as some feared it would. Here we propose to pin the dependency on ~~the last known good snapshot of Calcite 1.35~~ Calcite 1.34 in the hopes that Drill 1.22 will later be releasable based on Calcite >= 1.35.
- Adjust casting costs so that VARCHAR -> BIGINT is cheaper than VARCHAR -> FLOAT8.
- Pin Calcite to ~~1.35.0-20230417.123552-29~~ 1.34 and reenable testTimestampAddDiffLiteralTypeInference.
- Upgrade javassist -> 3.29.2-GA.
N/A
Existing and new unit tests.

DRILL-8435: Pin the version of Calcite in the master branch

---

contrib/storage-http/.gitignore
contrib/storage-http/Pagination.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPaginatorConfig.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/HeaderIndexPaginator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/PagePaginator.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java

See below
Updated README.
Header index pagination is used when the API in question returns a link to the next page in the response header.  Shopify is one such example of an API that does this. 
The only configuration option is the `nextPageParam` which is the parameter that Drill should look for in the response header.
```json
"paginator": {
"nextPageParam": "page",
"method": "HEADER_INDEX"
}
```
Added UT and manually tested with Shopify API.

DRILL-8437: Add Header Index Pagination

---

pom.xml

Remove git.total.commit.count from the git-commit-id-plugin.
N/A
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/drill/README.md

DRILL-8158: Remove non-reproducible entry

---

contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/DeltaRowGroupScan.java
contrib/format-deltalake/src/test/java/org/apache/drill/exec/store/delta/DeltaQueriesTest.java

NA
Updated unit test to cover the failing case.
Closes #2810

DRILL-8442: Fix DeltaRowGroupScan deserialization

---

exec/java-exec/src/main/resources/rest/options.ftl
exec/java-exec/src/main/resources/rest/query/result.ftl

CSS-based properties use a colon(`:`) to assign values. The `result.ftl` and `options.ftl` have the property `width` with an equal sign(`=`) instead of a colon(`:`).
This typo makes a query result table has an incorrect display.
Steps to reproduce:
1. Execute example query: `select full_name from cp.`employee.json` limit 1`;
2. Push the "Column visibility" button, toggle "full_name" column visibility off, and turn it back on.
None requerid
Visual test of UI

DRILL-8449: fix typo in width property in FreeMarker templates

---

exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/BaseTestImpersonation.java
exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestInboundImpersonation.java

The following changes are made to resolve the "IO Running in secure mode, but config doesn't have a keytab" errors currently plaguing the Hadoop 3 impersonation tests when (and only when) they run in the GitHub CI [1]. 
- Ensure that MiniDFS is using simple auth in BaseTestImpersonation.
- Shut down MiniDFS cluster in TestInboundImpersonation.selectChainedView
These changes are sufficient to fix what I believe is a racy test harness set up / clean up bug that at this time only presents itself in the GitHub CI, and even then only with recent GitHub Runner images.
1. Example: https://github.com/apache/drill/actions/runs/5867741986/job/15909061405
N/A
CI runs.

[MINOR UPDATE]: Fix Hadoop 3 impersonation test errors during CI runs

---

common/src/main/java/org/apache/drill/common/Typifier.java
contrib/format-xml/README.md
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatConfig.java
contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
contrib/storage-http/XML_Options.md
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXmlOptions.java
contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java

This PR adds data type inference to the XML format plugin.  In similar fashion to other plugins, it adds a new configuration parameter: `allTextMode`, which when set to `true`, reads all data as strings.  The default is `true`.
Note that the inference is limited to doubles, date, timestamps, boolean and strings.
Updated README

DRILL-8450: Add Data Type Inference to XML Format Plugin

---

contrib/storage-hive/core/pom.xml
contrib/storage-phoenix/pom.xml
exec/java-exec/pom.xml
exec/jdbc-all/pom.xml
exec/jdbc-all/src/main/resources/core-site.xml
exec/jdbc-all/src/test/java/org/apache/drill/jdbc/ITTestShadedJar.java
exec/jdbc-all/src/test/resources/core-site.xml
pom.xml

Hadoop is upgraded to 3.3.6.
N/A
Existing unit tests, manual testing of Drill HTTP services. Manual testing Drill JDBC driver.
Rebased onto #2823.

DRILL-8436: Upgrade Hadoop 3.2.4 → 3.3.6

---

.github/workflows/ci.yml
pom.xml

1. Add a 2GB swap file when setting up the Actions Runner.
2. Remove /proc/sys/vm/drop_caches [snake oil](https://www.linuxatemyram.com/).
3. Tune the heap and direct memory limits applied to the test suite.
Improve the comments in the CI workflow yaml.
Full CI run.

[MINOR UPDATE]: Improve the Github CI memory constraint workarounds

---

pom.xml

[DRILL-8459]: Bump Avro to 1.11.3

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
contrib/format-xml/src/test/resources/xml/bad.xml

Drill's XML reader would allow a maliciously crafted XML file to perform an XML eXternal Entity injection (XXE)  attack.  This fix disables DTD parsing in the XML format plugin and prevents XXE attacks.
Added unit test and tested manually.

DRILL-8461: Prevent XXE Attacks in XML Format Plugin

---

common/src/main/java/org/apache/drill/exec/metrics/CpuGaugeSet.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/TestSplunkUserTranslation.java

Simplify CpuGaugeSet fixing the non-Sun/Oracle code path in the process.
The com.sun.management internal implementation of OperatingSystemMXBean is used by Drill to report a CPU metric that is not available in the public interface. Even though code to handle non-Sun/Oracle runtimes for the OperatingSystemMXBean was present, it would still cause them to attempt to load a class from com.sun.management causing a NoClassDefFoundError.
N/A
Launch Drill and check the affected gauges in 
- OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-1, mixed mode, sharing)
- IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230817_56476 (JIT enabled, AOT enabled)

DRILL-8446: Incorrect use of OperatingSystemMXBean

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java

The issue is caused by plugin registry refactoring: https://github.com/apache/drill/pull/1988
After this change, `drill.exec.storage.action_on_plugins_override_file` doesn't work as described in our documentation: https://drill.apache.org/docs/configuring-storage-plugins/#configuring-storage-plugins-with-the-storage-plugins-overrideconf-file
`storage-plugins-override.conf` is neither removed nor renamed on Drill restart.
No updates
Manual

DRILL-8468: Drill doesn't perform drill.exec.storage.action_on_plugins_override_file action

---

distribution/src/assemble/component.xml
pom.xml

Includes some corrections to the 3rdpaty/ and classb/ library separation.
N/A
Unit tests pass.

DRILL-8445: Upgrade Janino 3.1.8 → 3.1.11

---

exec/jdbc-all/pom.xml
pom.xml

Note that the initial attempt to upgrade ZooKeeper to 3.7.2 for this ticket led to test failures and so to keep this upgrade backportable the upgrade is limited to 3.5.10.
N/A
Unit tests pass.

DRILL-8460: Upgrade ZooKeeper 3.5.7 → 3.5.10 and Curator 5.2.0 → 5.5.0

---

contrib/format-deltalake/pom.xml
contrib/format-image/pom.xml
contrib/format-image/src/test/resources/image/jpeg.json
pom.xml

Update the mongoDB Java driver to the latest version..
This PR also includes: 
* [DRILL-8471](https://issues.apache.org/jira/browse/DRILL-8471):  Bump DeltaLake Driver to 3.0.0
* [DRILL-8742](https://issues.apache.org/jira/browse/DRILL-8472): Bump Image Metadata Library to Latest Version
N/A
Ran unit tests.

DRILL-8470: Bump MongoDB Driver to Latest Version

---

.asf.yaml
docs/dev/Release.md

1. Disable forced pushes to the master branch.
2. Update Javadoc instructions in Release.md.
The relevant ASF documentation [is here](https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection).
Test by trying to do a (trivial and harmless) force push to master _after merging_. There is unfortunately no way to test before merging and I don't believe we can view the branch protection status in the repo settings page.

[MINOR UPDATE]: Enable master branch protection

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/HashPartition.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/AbstractHashBinaryRecordBatch.java

https://issues.apache.org/jira/browse/DRILL-8478
when allocating memory for hashParttion with OutOfMemoryException,it cause memory leak.
beacuase hashpartiton object  cannot be created successfully, so it cannot be cleaned up In the closing phase.
(1) script
i run sql8 (sql detail as Additional context) with 20 concurrent
tpch test script 
```
fileName=/data/drill/tpch_sql/1s/shf.txt
random_sql(){
#for i in `seq 1 3`
while true
do
num=$((RANDOM%22+1))
if [ -f $fileName ]; then
echo "$fileName" " is exit"
exit 0
else
$jupiter_home/sqlline -u \"jdbc:drill:zk=ip:2181/drill/jupiterbits1_performance_test_shf\" -f tpch_sql8.sql >> …
```

DRILL-8478. HashPartition memory leak when it allocate memory exception with OutOfMemoryException (#2874)

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
contrib/format-xml/src/test/resources/xml/no_nest.xml

Drill did not have the ability to query attributes of the root element.  That bug has been fixed in this PR.

DRILL-8141: Ability to query XML root attributes

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/MergeJoinBatch.java

when fragment failed, it call close() from MergeJoinBatch. but if  leftIterator.close() throw exception, we could not call  rightIterator.close() to release memory。
Relates to: (#2876)
The test method is the same with link, only one parameter needs to be modified,
set planner.enable_hashjoin =false  to  ensure use mergejoin operator
link
[DRILL-8478](https://github.com/apache/drill/pull/2875): HashPartition memory leak when it allocate memory exception with OutOfMemoryException (#2874)

DRILL-8479: Merge Join Leak When Depleting Incoming Batches Throw Exception

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish-snapshot.yml

* node 16 support is being removed so we need to upgrade actions
* also updated jobs to only run for this repo and not for forks
* currently, if you do a PR, the full build runs in the user's fork and in apache project
* one of these days, GitHub are going to start capping build credits
* we can delay this by not running big CI jobs on forks

[MINOR UPDATE] upgrade actions

---

contrib/format-excel/pom.xml
pom.xml

Updating due to 2 CVEs in commons-compress
https://mvnrepository.com/artifact/org.apache.commons/commons-compress
I released a new version of excel-streaming-reader that was built with the new version of commons-compress.

[MINOR UPDATE] update commons-compress due to CVEs

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenEntryDictionaryReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenEntryReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenNullableDictionaryReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenNullableEntryReader.java

Drill, during a bulk reading of a parquet file, unproperly handles a long value of parquet file entry. Drill reads the value, but after he finds that he can’t handle the value in the current batch, he just moves on, without persisting the read value. Since the value wasn’t pushed back to the reader object, the total read and left-to-read records counts are now in unproper state which causes data reading to fail in the future.
This issue hasn’t been faced before, because the conditions to get into this state are rare.
**Solution**
Push back the value to the reader object to read it in the next iteration, if the current batch can’t hold it.
\-
Manual testing with a parquet file from the Jira ticket: [DRILL-8486](https://issues.apache.org/jira/browse/DRILL-8486). It's hard to reproduce this …

DRILL-8486: ParquetDecodingException: could not read bytes at offset 

---

logical/src/main/java/org/apache/drill/common/util/AbstractDynamicBean.java

`put(String propertyName, JsonNode value)` is deprcated in 2.4 version. It's recommended to replace it.

[MINOR UPDATE] replace deprecate method use in jackson

---

contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
contrib/format-xml/src/test/resources/xml/sitemap.xml

This PR fixes an issue whereby if an XML file has a namespace defined, Drill may ignore all data.

DRILL-8493: Drill Unable to Read XML Files with Namespaces

---

exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcEncoder.java

When encode throw Exception, if encode msg  instanceof ReferenceCounted, netty can release msg, but drill convert msg to OutboundRpcMessage, so netty can not release msg. 
we can  reproduce this scenario by break point and add debug log. Seeing Testing#Test1
**1. set -Ddrill.memory.debug.allocator=TRUE**
**2. we  add  debug log as following**
DrillByteBufAllocator #DrillByteBufAllocator
```
public ByteBuf buffer() {
File file = new File("/data/shf/b.log");
if (file.exists()) {
throw new OutOfMemoryException("shf encode exception");
}
return buffer(DEFAULT_BUFFER_SIZE);
}
```
**3. restart drillbit**
**4. Run tpch sql8**
```
select
o_year,
sum(case when nation = 'CHINA' then volume else 0 end) / …
```

DRILL-8489: Sender memory leak when rpc encode exception

---

exec/java-exec/src/main/java/org/apache/drill/exec/cache/VectorAccessibleSerializable.java

(Please replace `PR Title` with actual PR Title)
We should catch the OutOfMemoryException instead of OutOfMemoryError, see buffer method for allacate memory 
```
public DrillBuf buffer(final int initialRequestSize, BufferManager manager) {
if (!outcome.isOk()) {
throw new OutOfMemoryException**(createErrorMsg(this, actualRequestSize, initialRequestSize));
}
}
```
[drill-8485](https://issues.apache.org/jira/browse/DRILL-8485)

DRILL-8488: HashJoinPOP memory leak is caused by  OutOfMemoryException

---

contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java

A minor bug was introduced in [DRILL-8329](https://github.com/apache/drill/pull/2669) which caused the cache in the HTTP storage plugin to be deleted after every query.  This minor update fixes that bug.

DRILL-8495: HTTP Caching Not Saving Pages

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/NestedLoopJoin.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/NestedLoopJoinBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/NestedLoopJoinTemplate.java

Nested Loop Join operator (`NestedLoopJoinBatch`, `NestedLoopJoin`) unproperly handles batch iteration outcome `OK` with 0 records. Drill design of the processing of batches involves 5 states:
* `NONE` (batch can have only 0 records)
* `OK` (batch can have 0+ records)
* `OK_NEW_SCHEMA` (batch can have 0+ records)
* `NOT_YET` (undefined)
* `EMIT` (batch can have 0+ records)
The Nested Loop Join operator in some circumstances could receive `OK` outcome with 0 records, and instead of requesting the next batch, the operator stops data processing and returns `NONE` outcome to upstream batches(operators) without freeing resources of underlying batches.
**Solution**
Make the Nested Loop Join operator properly handle `OK` and `OK_NEW_SCHEMA` outcomes with 0 records and keep processing until …

DRILL-8480: Cleanup before finished. 0 out of 1 streams have finished 

---

contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/readers/HiveDefaultRecordReader.java
contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/writers/HiveValueWriterFactory.java
contrib/storage-hive/core/src/test/java/org/apache/drill/exec/hive/TestHiveStorage.java
contrib/storage-hive/core/src/test/java/org/apache/drill/exec/hive/TestInfoSchemaOnHiveStorage.java
contrib/storage-hive/core/src/test/java/org/apache/drill/exec/store/hive/HiveTestDataGenerator.java

The root cause of the issue is that multiple HiveWriters use the same `DrillBuf` and during execution they may reallocate the buffer if size of the buffer is not enough for a value (256 bytes+). Since `drillBuf.reallocIfNeeded(int size)` returns a new instance of `DrillBuf`, all other writers still have a reference for the old one buffer, which after `drillBuf.reallocIfNeeded(int size)` execution is unmanaged now.
`HiveValueWriterFactory` now creates a unique `DrillBif` for each writer. 
HiveWriters are actually used one-by-one and we could utilize a single buffer for all the writers. To do this, I could create a class holder for `DrillBuf`, so each writer has a reference for the same holder, where will be stored a new buffer from every `drillBuf.reallocIfNeeded(int size)` call. But I …

DRILL-8495: Tried to remove unmanaged buffer

---

distribution/src/main/resources/drill-config.sh
distribution/src/main/resources/sqlline

Add Java system options to Sqlline arguments list to hide possible warnings due to illegal reflective access.
\-
I manually verified the warning doesn't appear anymore.

DRILL-8498: Hide sqlline reflective access warnings

---

exec/java-exec/src/main/java/org/apache/drill/exec/ops/AccountingDataTunnel.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/DataTunnelStatusHandler.java
exec/java-exec/src/main/java/org/apache/drill/exec/ops/SendingAccountor.java
exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataTunnel.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/AbstractRemoteConnection.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RequestIdMap.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcBus.java
exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcOutcomeListener.java

when ChannelClosedException, .ReconnectingConnection#CloseHandler release sendingAccountor reference counter before netty release buffer, so operator was closed before memory is released by netty
later
1. TPCH test condition
(1) script
```
i run sql8 (sql detail as Additional context) with 20 concurrent
tpch test script
```
```
fileName=/data/drill/tpch_sql/1s/shf.txt
random_sql(){
#for i in `seq 1 30`
while true
do
num=$((RANDOM%22+1))
if [ -f $fileName ]; then
echo "$fileName" " is exit"
exit 0
else
$drill_home/sqlline -u \"jdbc:drill:zk=ip:2181/drill/drillbits1_performance_test_shf\" -f tpch_sql8.sql >>/tpch1s_sql${num}.log 2>&1
fi
done
}
```
(2) parameter
{DRILL_MAX_DIRECT_MEMORY:-"5G"}
open debug : set drill.memory.debug.allocator =true (Check for memory leaks )
(3) sql8
`select …

DRILL-8490: Sender operator fake memory leak result to sql failed  and memory statistics error when ChannelClosedException

---

exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/conv/JsonConvertFrom.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonConversionUDF.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonNanInf.java
exec/java-exec/src/test/resources/jsoninput/allTypes.csvh

The `convert_fromJSON()` function was ignoring Drill system configuration variables for reading JSON.  This PR adds support for `allTextMode` and `readNumbersAsDouble` to this function.  Once merged, the `convert_fromJSON()` function will follow the system settings.
I also split one of the unit test files because it had all the UDF tests mixed with NaN tests. 
This PR adds the possibility of setting `allTextMode` and `readNumbersAsDouble` in the function call itself.   The new usage is:
`SELECT convert_fromJSON(<field>, <allTextMode>, <readNumbersAsDouble>)`
Thus you could write a query:
```sql
SELECT convert_fromJSON(jsonField, false, true) FROM dfs.somedata
```

DRILL-8501: Json Conversion UDF Not Respecting System JSON Options

---

contrib/format-excel/pom.xml
pom.xml

excel-streaming-reader now makes poi-shared-strings optional and Drill doesn't need it (or its h2 dependency).

[MINOR UPDATE] update to poi 5.3.0

---

exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/resources/drill-module.conf

This PR removes 3 unused properties and 1 duplicate property and makes `drill.exec.options.drill.exec.testing.controls` visible all the time, not only when assertions mode is enabled. 
During an investigation of the Drill configuration system, I noticed Drill has several system options(`drill.exec.options.*` properties), which are absent in `SystemOptionManager`, but present in `DrillConfig`:
```sql
apache drill> select name from sys.boot where name like 'drill.exec.options%' AND name not in (select concat('drill.exec.options.', name) from sys.internal_options union all select concat('drill.exec.options.', name) from sys.options);
+-------------------------------------------------------+
|                         name                          | …
```

DRILL-8502: some boot options with drill.exec.options prefix are missed in configuration options

---

tools/fmpp/src/main/java/org/apache/drill/fmpp/mojo/FMPPMojo.java

Without this annotation Maven assumes the plugin is NOT threadsafe, and any parallel builds spews log warnings
Fixes: #2928

Add threadSafe annotation to fmpp Maven Plugin

---

contrib/storage-splunk/README.md
contrib/storage-splunk/pom.xml
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkUtils.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java

in corporate installations, sometimes the organization will use self-signed certificates which can cause problems.  This PR adds an option to bypass host validation for SSL connections in Splunk.  The "correct" way to fix this would be to provide better SSL information, to include the certificate in the Splunk connection, however, Splunk's SDK does not allow for this and there are several open issues and PRs relating to this.  
This PR also bumps the Splunk SDK version to the latest version which is 1.9.5.  
An additional configuration option: `validateHostnames` has been added to the Splunk configuration.  I updated the README.md file with this information and will be updating the documentation once this has been merged.
Ran existing unit tests and tested manually.

DRILL-8503: Add Configuration Option to Skip Host Validation for Splunk

---

Dockerfile
hooks/build

1. Use a single threaded Maven build to avoid thread-unsafe Maven plugin issues.
2. Move the _latest_ and _master_ tags to OpenJDK 17. Images based on on all three of OpenJDK 8, 11 and 17 continue to be published and tagged accordingly but the "default" tags of _latest_ and _master_ are repointed to OpenJDK 17. This affects the _master_ image as soon as this PR is merged, while the _latest_ image will only change with the next Drill release.
N/A
Manual test of the Docker Hub automated build based on the temporary drill-8505 branch in the apache/drill repo. The temporary branch are resulting container image on Docker Hub are to be cleaned up after this PR is finalised.

DRILL-8505: Fix Docker Hub automated container image builds

---

exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/ObjectParser.java
exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestBasics.java

If Drill encounters a JSON field with an empty key, currently Drill throws an exception.   This behavior prevents Drill from reading the rest of the data.  This PR modifies Drill's behavior by simply ignoring JSON data with empty keys.   Drill will generate a log warning message when this happens.
No significant user facing changes.

DRILL-8506: Ignore JSON Elements with Empty Keys

---

contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
pom.xml

Older versions of MSSQL [are not compatible with Linux 6.7](https://github.com/microsoft/mssql-docker/issues/868). This upgrades the MSSQL test container and disables two unit tests that are broken by that upgrade (for unrelated reasons).
N/A
CI test suite.

[MINOR UPDATE]: Upgrade the MSSQL test container for compatibility with Linux 6.7.

---

pom.xml

[MINOR UPDATE] Upgrade jetty to 9.4.56.v20240826 due to CVE-2024-8184

---

exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinProbeTemplate.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestHashJoin.java
exec/java-exec/src/test/resources/join/hj_right_outer_empty_left_input.json

Drill returns no results on the right Hash Join if the probe(left) table is empty.
The root cause is simple. Stack-trace of the point of failure:
```
changeToFinalProbeState:123, HashJoinProbeTemplate (org.apache.drill.exec.physical.impl.join)
setup:105, ProbeTemplate (org.apache.drill.exec.physical.impl.join) <---- The issue comes from here. Because the changeToFinalProbeState() is called before all necessary variables are initialized by the HashJoinProbeTemplate#setup() method.  
setup:45, HashJoinProbeTemplate (org.apache.drill.exec.physical.impl.join) 
setupProbe:108, HashJoinBatch (org.apache.drill.exec.physical.impl.join)
innerNext:585, AbstractHashBinaryRecordBatch (org.apache.drill.exec.physical.impl.join)
```
`HashJoinProbeTemplate#setup()` calls it's super `#setup()` before …

DRILL-8513: Right Hash Join with empty Left table ruturns 0 result

---

exec/java-exec/pom.xml

avro 1.11.4 does not publish this jar any more
simplifies #2953

[MINOR UPDATE] remove avro test dependency

---

tools/fmpp/pom.xml

Relates to #2946 - but might be better to use same commons-io version in all Drill projects

[MINOR UPDATE] use same version of commons-io in all drill projects

---

.github/workflows/ci.yml

Subjob is failing in today's builds - make tool issues when running protobuf bits.
GitHub CI recently moved to unbuntu 24 for 'latest' install.
eg
https://github.com/apache/drill/actions/runs/12504907055/job/34889343661

[CI] use ubuntu 22 for checkstyle/protobuf job

---

contrib/storage-phoenix/pom.xml
pom.xml

[DRILL-8515](https://issues.apache.org/jira/browse/DRILL-8515)
Upgrade HBase client due to issues with zookeeper upgrade - #2893 

DRILL-8515: Upgrade to HBase client 2.6.1

---

.github/workflows/ci.yml
exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassCompilerSelector.java
exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassTransformer.java
exec/java-exec/src/main/java/org/apache/drill/exec/compile/QueryClassLoader.java
exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
exec/java-exec/src/test/java/org/apache/drill/exec/compile/TestClassTransformation.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestNestedDateTimeTimestamp.java
exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitRpc.java
exec/java-exec/src/test/java/org/apache/drill/exec/vector/accessor/GenericAccessorTest.java
exec/java-exec/src/test/java/org/apache/drill/exec/work/fragment/FragmentStatusReporterTest.java
exec/jdbc-all/pom.xml
pom.xml

This PR removes the CI actions for Java 8 and effectively ends Drill's support for Java 8.  As a consequence of that, Drill no longer supports Hadoop 2.   The profile is still in the pom.xml file should anyone want to build Drill for Hadoop 2, but we are no longer running CI with those tests.
This seems to have the added benefit of fixing the flaky Hive tests in the Hadoop-2 runs.
This PR also adds CI tests for Java 21. 

DRILL-8523: Remove Support for Java 8

---

contrib/storage-http/pom.xml
contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/OffsetPaginator.java

This PR fixes a minor bug with the Offset paginator.  When the URL params have a `$` or other control character, the pagination was not properly updating the URL and adding duplicate parameters to the URL.  This PR solves that. 
Additionally, this PR bumps OkHTTP to the latest version. 
Tested against user provided API.  Ran existing unit tests.

DRILL-8524: Drill Adding Duplicate Parameters in Offset Paginator

---

contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/coord/zk/ZKClusterCoordinator.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/HashAggBatch.java
exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectionMaterializer.java
exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/LateralJoinPrel.java
exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/RecordCollector.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java
exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet2/DrillParquetReader.java
exec/java-exec/src/main/java/org/apache/drill/exec/work/filter/RuntimeFilterRouter.java
pom.xml

To my surprise, Drill still uses classes from commons-collections (`3.x` release) in a few places, and Drill has not even declared it as a dependency. Drill used transitive dependency from `hadoop-commons`:
```
[INFO] --- dependency:3.6.1:tree (default-cli) @ drill-java-exec ---
[INFO] org.apache.drill.exec:drill-java-exec:jar:1.22.0-SNAPSHOT
[INFO] +- org.apache.hadoop:hadoop-common:jar:3.3.6:compile
[INFO] |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] \- org.apache.commons:commons-collections4:jar:4.4:compile
```
But starting from `3.4.2` release, Hadoop drops it: https://issues.apache.org/jira/browse/HADOOP-15760
Time to clean our code too and completely migrate to `4.x` :)
No user-visible changes
Unit tests

DRILL-8525: Migrate Fully to Apache Commons Collections 4.x

---

contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseGroupScan.java
contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBasePushFilterIntoScan.java
contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseRecordReader.java
contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseScanBatchCreator.java
contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseStoragePlugin.java
contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseSubScan.java
contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestHBaseFilterPushDown.java

support  Limit Push Down for HBase.i test 
select * from clicks limit 3
The log shows that The storage layer hbase （HBaseRecordReader）only got 3 rows of data
`2025-07-11 01:48:17,297 [178f302e-26db-37dd-500d-db2797b17a5c:frag:0:0] INFO  o.a.d.e.s.hbase.HBaseRecordReader - Took 7 ms to get 3 records`
plan is as follow
```
00-00    Screen : rowType = RecordType(ANY row_key, (VARCHAR(65535), ANY) MAP clickinfo, (VARCHAR(65535), ANY) MAP iteminfo): rowcount = 3.0, cumulative cost = {18.3 rows, 51.3 cpu, 0.0 io, 0.0 network, 0.0 memory}, id = 301
00-01      Project(row_key=[$0], clickinfo=[$1], iteminfo=[$2]) : rowType = RecordType(ANY row_key, (VARCHAR(65535), ANY) MAP clickinfo, (VARCHAR(65535), ANY) MAP iteminfo): rowcount = 3.0, cumulative cost = {18.0 rows, 51.0 cpu, 0.0 io, 0.0 network, …
```

DRILL-8528: HBase Limit Push Down

---

contrib/format-deltalake/pom.xml

Update Delta Lake libraries to version 4.0

[MINOR UPDATE] Bump Delta Lake to Version 4.0
