apache/drill

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/mergereceiver/MergingRecordBatch.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/PreProcessLogicalRel.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DefaultSqlHandler.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/UnsupportedOperatorsVisitor.java
- exec/java-exec/src/main/java/org/apache/drill/exec/util/ApproximateStringMatcher.java
- exec/java-exec/src/test/java/org/apache/drill/exec/TestWindowFunctions.java
- exec/java-exec/src/test/java/org/apache/drill/exec/util/TestApproximateStringMatcher.java
> Drill 3156: Fix Calcite trace by registering RelMetadataProvider with HepPlanner used for window function planning.

- contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveDrillNativeParquetScan.java
- contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveScan.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/ScanPrel.java
@amansinha100 Could you please review the patch?
> DRILL-3884: Fix lower parallelization issues with Hive's native scan.

- pom.xml
Added *.seq files to RAT's exclusion list.
> DRILL-4040: Build failure on master

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/JoinStatus.java
> DRILL-4165 Add a precondition for size of merge join record batch.

- _docs/performance-tuning/070-monitoring-metrics.md
- mailinglists.md
Hi,
I’ve updated the mailing list page with a few guidelines. I’ll post the update to drill.apache.org if everyone is okay with the content. 
Thanks,
Bridget
> update mailing list with note

- exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
Currently, the check for the Java compiler is made only during query execution.
This commit ensures that if the java executable used for instantiating the Drillbit is from a JRE (i.e. the Java compiler is not available), the Drillbit will fail with the exception reported in the logs:
```
Exception in thread "main" org.apache.drill.exec.exception.DrillbitStartupException: JDK Java compiler not available. Ensure Drill is running with the java executable from a JDK and not a JRE
at org.apache.drill.exec.server.Drillbit.<init>(Drillbit.java:138)
at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:409)
at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:389)
at org.apache.drill.exec.server.Drillbit.main(Drillbit.java:385)
```
> DRILL-5990: Drill should not startup with JRE sourced java executable

- exec/java-exec/src/test/java/org/apache/drill/test/TestGracefulShutdown.java
> DRILL-6415: Fixed TestGracefulShutdown.TestRestApi test from timing out

- _docs/odbc-jdbc-interfaces/configuring-odbc/010-odbc-configuration-reference.md
Add the RDBMS to the schema types which driver supports.
> add the RDBMS to the schema types

- exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
Details in Jira [DRILL-6466](https://issues.apache.org/jira/browse/DRILL-6466).
> DRILL-6466: Add HttpOnly flag to response cookies

- contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/CompareFunctionsProcessor.java
- contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestHBaseFilterPushDown.java
Details in [DRILL-6489](https://issues.apache.org/jira/browse/DRILL-6489).
> DRILL-6489: Fix filter push down for Hbase & Mapr-DB binary tables when convert function is used in a view

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/config/LateralJoinPOP.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/LateralJoinBatch.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestLateralJoinCorrectness.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/unnest/TestUnnestWithLateralCorrectness.java
@parthchandra - Please help to review.
> DRILL-6503: Performance improvements in lateral

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/managed/ExternalSortBatch.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/managed/MergeSortWrapper.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/managed/PriorityQueueCopierWrapper.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/managed/SortImpl.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/xsort/managed/SpilledRuns.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TopN/TestTopNEmitOutcome.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/lateraljoin/TestE2EUnnestAndLateral.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/xsort/managed/TestSortEmitOutcome.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/xsort/managed/TestSortImpl.java
@parthchandra / @Ben-Zvi - please help to review.
> DRILL-6498: Support for EMIT outcome in ExternalSortBatch

- exec/java-exec/src/main/resources/rest/index.ftl
> DRILL-6663: Fixed shutdown button in Web UI

- _includes/menu.html
- apacheASF.html
- download.html
- index.html
* Apache page
* Drill book download link
* Checksum links
> Drill website update :

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/SchemalessScan.java
- exec/java-exec/src/test/java/org/apache/drill/exec/TestEmptyInputSql.java
Details in [DRILL-6721](https://issues.apache.org/jira/browse/DRILL-6721).
> DRILL-6721: Fix SchemalessScan plan serialization / deserialization

- _docs/connect-a-data-source/plugins/110-s3-storage-plugin.md
Adding instructions for using drill with AWS Instance Profiles/IAM Roles for accessing S3.
>  Docs for configuring Drill to S3 Instance Profiles - DRILL-6748

- _docs/connect-a-data-source/plugins/115-azure-blob-storage-plugin.md
Created Azure Blob Storage documentation. Used existing S3 document as a starting point to maintain consistency
> Added Azure Blob Storage documentation

- _docs/performance-tuning/026-parquet-filter-pushdown.md
Fixing broken links to CTAS and Explain Commands
> DRILL-6749:  Fixing broken links to CTAS and Explain Commands

- exec/java-exec/src/main/resources/rest/generic.ftl
See details in description of the [DRILL-6776](https://issues.apache.org/jira/browse/DRILL-6776).
> DRILL-6776: Drill Web UI takes long time for first time load in network isolated environment

- exec/java-exec/src/main/codegen/templates/EventBasedRecordWriter.java
- exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java
- exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CompareUntypedNull.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
- exec/java-exec/src/test/java/org/apache/drill/TestUntypedNull.java
- exec/vector/src/main/codegen/templates/AbstractFieldReader.java
- exec/vector/src/main/codegen/templates/BasicTypeHelper.java
- exec/vector/src/main/java/org/apache/drill/exec/vector/UntypedNullHolder.java
- exec/vector/src/main/java/org/apache/drill/exec/vector/UntypedNullVector.java
- exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/AbstractBaseReader.java
- exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/UntypedHolderReaderImpl.java
- exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/UntypedReader.java
- exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/UntypedReaderImpl.java
Details in [DRILL-6797](https://issues.apache.org/jira/browse/DRILL-6797).
> DRILL-6797: Fix UntypedNull handling for complex types

- exec/java-exec/src/main/resources/rest/error.ftl
- exec/java-exec/src/main/resources/rest/index.ftl
- exec/java-exec/src/main/resources/rest/login.ftl
- exec/java-exec/src/main/resources/rest/logs/list.ftl
- exec/java-exec/src/main/resources/rest/logs/log.ftl
- exec/java-exec/src/main/resources/rest/metrics/metrics.ftl
- exec/java-exec/src/main/resources/rest/options.ftl
- exec/java-exec/src/main/resources/rest/profile/list.ftl
- exec/java-exec/src/main/resources/rest/profile/profile.ftl
- exec/java-exec/src/main/resources/rest/query/errorMessage.ftl
- exec/java-exec/src/main/resources/rest/query/list.ftl
- exec/java-exec/src/main/resources/rest/query/query.ftl
- exec/java-exec/src/main/resources/rest/query/result.ftl
- exec/java-exec/src/main/resources/rest/status.ftl
- exec/java-exec/src/main/resources/rest/storage/list.ftl
- exec/java-exec/src/main/resources/rest/storage/update.ftl
- exec/java-exec/src/main/resources/rest/threads/threads.ftl
Details in [DRILL-6819](https://issues.apache.org/jira/browse/DRILL-6819).
> DRILL-6819: Remove invisible back link in Drill WebUI

- blog/_posts/2018-10-16-drill-user-meetup.md
- index.html
@aashreya , @bbevens Please review
> Md 4946: Added Developer Day and User Meet-up links

- _docs/connect-a-data-source/plugins/090-mongodb-storage-plugin.md
Adding information about possible authentication settings in connection URL for mongodb
> DRILL-6831: Adding information about possible authentication settings in connection URL for mongodb

- exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenAbstractPageEntryReader.java
**Problem Description -**
- The code sampled a varchar field and realized it is of fixed length type
- It processed a couple of internal batches (4k max) just fine
- Somehow at the last batch of the row-group, the column precision became lower
- The logic to compute the next-record-batch was based on how much data it has loaded in the byte buffer and the expected precision: "loaded-data / expected-precision"
- Hence the chunk-size became zero when the loaded data changed precision
**Fix -**
- The logic to compute the next-record-batch should only worry that we do not try to read beyond the byte-buffer (to handle changes in precision for the last few values)
- Modified the code to use: "buffer-capacity / expected-precision"
- This way the code will have a chance to discover the change in …
> Fixed IllegalStateException while reading Parquet data

- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillSqlWorker.java
- exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryWrapper.java
The fix is to force setting to zero IFF autoLimit was intended to be set originally but is inapplicable; such as 'SHOW DATABASES'. If autolimit was not intended to be applied, setting the value to zero is not required.
> DRILL-7160: e.q.max_rows QUERY-level option shown even if not set

- exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
Details - [DRILL-7186](https://issues.apache.org/jira/browse/DRILL-7186).
> DRILL-7186: Add back storage.json REST endpoint (regression after DRILL-6562)

- exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
- exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
See details:
https://issues.apache.org/jira/browse/DRILL-7190?focusedCommentId=16822315&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16822315
> DRILL-7190: Missing backward compatibility for REST API with DRILL-6562

- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBFormatMatcher.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBFormatPlugin.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBGroupScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBPushFilterIntoScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBPushLimitIntoScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBRestrictedScanBatchCreator.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBScanBatchCreator.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBSubScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/RestrictedMapRDBSubScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/binary/BinaryTableGroupScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/JsonTableGroupScan.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/MaprDBJsonRecordReader.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/RestrictedJsonRecordReader.java
- contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/RestrictedJsonTableGroupScan.java
- contrib/storage-hive/core/scrMapr/main/java/org/apache/drill/exec/planner/sql/logical/ConvertHiveMapRDBJsonScanToDrillMapRDBJsonScan.java
- contrib/storage-hive/core/src/main/java/org/apache/drill/exec/planner/types/HiveToRelDataTypeConverter.java
- contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveUtilities.java
- contrib/storage-hive/core/src/test/java/org/apache/drill/exec/store/hive/schema/TestSchemaConversion.java
- exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
- exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
- exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/JsonReaderUtils.java
- exec/java-exec/src/main/java/org/apache/drill/metastore/FileSystemMetadataProviderManager.java
- exec/java-exec/src/main/resources/drill-module.conf
- exec/vector/src/main/codegen/templates/ComplexCopier.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/RepeatedListBuilder.java
- metastore/metastore-api/src/main/java/org/apache/drill/metastore/util/SchemaPathUtils.java
For problem description please see [DRILL-7313](https://issues.apache.org/jira/browse/DRILL-7313).
> DRILL-7313: Use Hive schema for MaprDB native reader when field was empty

- exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
See [DRILL-7360](https://issues.apache.org/jira/browse/DRILL-7360) for details.
> DRILL-7360: Refactor WatchService in Drillbit class and fix concurrency issues

- exec/java-exec/src/main/codegen/data/Parser.tdd
- exec/java-exec/src/main/codegen/includes/parserImpls.ftl
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/SchemaHandler.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/SqlHandlerUtil.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/CompoundIdentifierConverter.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlSchema.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/schema/InlineSchemaProvider.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/schema/PathSchemaProvider.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/schema/SchemaProvider.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/metadata/schema/StorageProperties.java
- exec/java-exec/src/test/java/org/apache/drill/TestSchemaCommands.java
- exec/java-exec/src/test/java/org/apache/drill/exec/record/metadata/TestTupleSchema.java
- exec/java-exec/src/test/java/org/apache/drill/exec/record/metadata/schema/TestSchemaProvider.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/AbstractColumnMetadata.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/AbstractPropertied.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/Propertied.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/TupleSchema.java
Jira - [DRILL-7168](https://issues.apache.org/jira/browse/DRILL-7168).
> DRILL-7168: Implement ALTER SCHEMA ADD / REMOVE commands

- exec/java-exec/pom.xml
- exec/java-exec/src/main/java/org/apache/drill/exec/ops/ExecutorFragmentContext.java
- exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContext.java
- exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
- exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
- exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
- exec/java-exec/src/test/java/org/apache/drill/test/OperatorFixture.java
- exec/java-exec/src/test/java/org/apache/drill/test/PhysicalOpUnitTestBase.java
- metastore/iceberg-metastore/pom.xml
- metastore/iceberg-metastore/src/main/java/org/apache/drill/metastore/iceberg/operate/Overwrite.java
- metastore/iceberg-metastore/src/test/java/org/apache/drill/metastore/iceberg/components/tables/TestBasicRequests.java
Jira [DRILL-7368](https://issues.apache.org/jira/browse/DRILL-7368).
> DRILL-7368: Fix Iceberg Metastore failure when filter column contains nulls

- contrib/storage-hive/core/src/test/java/org/apache/drill/exec/hive/complex_types/TestHiveMaps.java
- contrib/storage-hive/core/src/test/java/org/apache/drill/exec/hive/complex_types/TestHiveStructs.java
- exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java
Covers case from [DRILL-7387](https://issues.apache.org/jira/browse/DRILL-7387).
> DRILL-7387: Failed to get value by int key from map nested into struct

- _docs/odbc-jdbc-interfaces/015-using-jdbc-driver.md
JIRA: https://issues.apache.org/jira/browse/DRILL-7462
> Update Documentation to use SSL for Download Links

- .github/PULL_REQUEST_TEMPLATE.md
Adds a pull request template to github.
> DRILL-7478: Add Pull Request Template

- .github/workflows/ci.yml
- exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestAnalyze.java
- exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java
Updated sample statistics tests
NA
Checked that updated unit tests pass
> DRILL-7570: Fix unstable statistics tests

- _docs/sql-reference/sql-functions/030-date-time-functions-and-arithmetic.md
Noticed some issues with this doc, here are the fixes.
> Some little fixups for the docs for date & time functions

- _docs/developer-information/rest-api/010-rest-api-introduction.md
> DRILL-7580: Fix Web UI link

- exec/java-exec/src/test/java/org/apache/drill/TestTpchDistributedConcurrent.java
- exec/java-exec/src/test/java/org/apache/drill/exec/compile/TestLargeFileCompilation.java
Increased test and client timeouts for `TestLargeFileCompilation` and `TestTpchDistributedConcurrent` tests and moved tests to `ClusterTest`.
Fixed failure of `TestTpchDistributedConcurrent` caused by concurrency issue when `completionSemaphore` is released and listeners list size is checked before removing listener from the list.
NA
Submitted several GitHub Actions jobs to verify that the issues above are fixed.
> DRILL-7651: Increase timeout for TestLargeFileCompilation to avoid GitHub Action failures and fix concurrent issue in TestTpchDistributedConcurrent

- exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java
- exec/java-exec/src/test/java/org/apache/drill/TestUntypedNull.java
- exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetComplex.java
- exec/java-exec/src/test/resources/physical_untyped_null.json
None.
Added unit test and ran test suits.
> DRILL-7759: Code compilation exception for queries containing (untyped) NULL

- exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
> Revert "DRILL-7801 Changed the scope of output_batch_size option to system and session"

- exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/DrillFileSystem.java
Some format plugins that use third party parsers throw errors when they receive compressed input streams from Drill.  This PR proposes to introduce three utility functions to the DrillFileSystem:
* `isCompressed(<path>)`:  Returns true/false whether the input file is compressed
* `getCodec(<path>)`  This method returns the codec of the file if any
* `openDecompressedInputStream(<path>)`:  Returns an InputStream that should be readable by parsers that read raw bytes.  This method converts the original InputStream to a byte[] first, then returns that via a ByteArrayInputStream.
> DRILL-7834: Add Utility Functions for Compressed Files

- _docs/connect-a-data-source/036-configuring-storage-plugins.md
Fix formatting on "Configuring Storage Plugins" page
> Fix formatting on "Configuring Storage Plugins" page

- contrib/storage-cassandra/pom.xml
Update the storage plugin name of `pom.xml`
See also [#2147](https://github.com/apache/drill/pull/2147)
<pre>
[INFO] Drill : Contrib : .................................. SUCCESS [  0.785 s]
[INFO] Drill : Contrib : Data : ........................... SUCCESS [  0.016 s]
[INFO] Drill : Contrib : Data : TPCH Sample ............... SUCCESS [  0.219 s]
[INFO] Drill : Contrib : UDFs ............................. SUCCESS [  1.703 s]
[INFO] Drill : Contrib : Storage : HBase .................. SUCCESS [  0.572 s]
[INFO] Drill : Contrib : Format : MaprDB .................. SUCCESS [  0.526 s]
[INFO] Drill : Contrib : Format : Syslog .................. SUCCESS [  0.357 s]
[INFO] Drill : Contrib : Format : LTSV .................... SUCCESS [  0.240 s]
[INFO] Drill : Contrib : Format : Excel …
> Minor Fix: Use a consistent naming for Cassandra

- _docs/110-troubleshooting.md
Anchor point invalid when title contains special characters. The PR hint the anchor point try to using `<span>`.
N/A
> [DOC UPDATE] Fix invalid link for 110-troubleshooting.md

- contrib/storage-cassandra/pom.xml
- contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/BaseCassandraTest.java
- contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuit.java
- contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestKafkaSuit.java
- exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/InteractiveUI.java
- exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestRestJson.java
- exec/java-exec/src/test/java/org/apache/drill/exec/util/ExecutorServiceUtilTest.java
- exec/java-exec/src/test/java/org/apache/drill/exec/util/TestQueryMemoryAlloc.java
- pom.xml
Please see Jira's description for issues that fixed here.
NA
NA
> DRILL-7857: Fix misc GitHub Actions failures

- contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
Add `TestMongoDrillIssue.class` to mongo TestSuite list
N/A
N/A
> Minor Fix: Update the mongo TestSuite list

- _docs/sql-reference/sql-commands/050-create-view.md
Such as the title description.
N/A
N/A
> [DOC UPDATE] Format the output to readable for 050-create-view.md

- README.md
(this is a small grammar edit for the README, so I didn't file a JIRA issue)
This PR fixed some grammar issues in the README.
This updated the README.
None, this is a trivial change.
> [DOC UPDATE] Grammar edit

- _docs/developer-information/design-docs/050-value-vectors.md
This is a doc update for 050-value-vectors.md, No JIRA issue filed here.
In PR #2204, I pushed two different commits together by accident. Due to there are some valuable comments put on the updated parts of apache-drill-contribution-ideas.md already, so I closed PR #2204 to keep the comment. And now, I submit the PR for 050-value-vectors.md individually here. For the update of apache-drill-contribution-ideas.md, there are still something need to confirm. Sorry for the misunderstand.
Removed bad links of Operators and Record Batch.
This PR updates 050-value-vectors.md.
None, this is a doc update.
> remove bad links

- contrib/storage-kafka/pom.xml
- contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestKafkaSuit.java
- contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/cluster/EmbeddedKafkaCluster.java
NA
NA
Checked that unit tests pass
> DRILL-7917: Update Kafka version to 2.8.0

- _docs/developer-information/rest-api/010-rest-api-introduction.md
Updated docs for REST API to contain the `defaultSchema` field and new information about error reporting.
N/A
N/A
> DRILL-7920: Update Documentation for REST API

- _docs/sql-reference/sql-functions/040-string-manipulation.md
Add doc for new split_part parameter
NA
NA
> DRILL-7928: [DOC-UPDATE] Add doc for split_part

- NOTICE
Update NOTICE copyright year to 2021
> Update NOTICE copyright year

- zh/index.html
Translate Index.html to Chinese version which referred to READ.me of gh-pages and the timely instruction from @dzamo (James Turton). 
This is a translation PR, reference to drill/gh-pages/zh/index.html
This is a translation PR, no test here.
> [DOC UPDATE] Index.html Chinese Translation

- .gitignore
- tools/drill-patch-review.py
This PR fixes a code quality alert and updates the patch review script to use Python 3 instead of the long deprecated Python 2.7. 
Ran script locally.
> [MINOR UPDATE] Update Patch Review Script to use Python 3

- _docs/zh/tutorials/030-analyzing-the-yelp-academic-dataset.md
- _docs/zh/tutorials/040-learn-drill-with-the-mapr-sandbox.md
- _docs/zh/tutorials/learn-drill-with-the-mapr-sandbox/005-about-the-mapr-sandbox.md
Translate three tutorials to Chinese:
- 030-analyzing-the-yelp-academic-dataset.md
- 040-learn-drill-with-the-mapr-sandbox.md
- 005-about-the-mapr-sandbox.md
Overall 5 tutorials have been translated, 9 tutorials to go.
Please refer to Chinese version's tutorial.
This is a doc update, no test here.
> [DOC UPDATE] Translate Tutorial to Chinese 5/14

- exec/java-exec/pom.xml
- exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
- exec/jdbc-all/pom.xml
Fixes a possible XSS vulnerability. 
> DRILL-7976: Fix XSS Vulnerability

- _docs/zh/tutorials/050-analyzing-highly-dynamic-datasets.md
- _docs/zh/tutorials/060-analyzing-social-media.md
Translate two tutorials to Chinese:
050-analyzing-highly-dynamic-datasets.md
060-analyzing-social-media.md
Overall 7 tutorials have been translated, 7 tutorials to go.
Please refer to Chinese version's tutorial.
This is a doc update, no test here.
> [DOC UPDATE] Translate Tutorial to Chinese 7/14

- contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithClickhouse.java
This is a quick fix for Travis CI, change the clickhouse image to be able to run on both x86-64 and arm64
> [TRAVIS CI FIX]: Change clickhouse image to be able to run on both x86-64 and arm64

- contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
Import the source code into the Eclipse (newer version), got the error message below :
```
Type mismatch: cannot convert from Z#0-SELF'#8 extends GenericContainer<Z#0-SELF'#8> & ... to Z#0-SELF'#4 extends GenericContainer<Z#0-SELF'#4> & ...
```
N/A
This error is gone in eclipse.
> DRILL-7997: Fix the type mismatch of mongo module in eclipse

- contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableRecordReader.java
See Jira ticket for details
NA
Added UT
> DRILL-8002: Expose clear error message for the case of errors from ElasticSearch

- exec/java-exec/src/test/java/org/apache/drill/exec/server/TestDrillbitResilience.java
DRILL-7908 fixes distributed deadlocks in TestDrillbitResilience and add better timing for simulation the different Drill states. But sometimes several tests failed.
1. Sometimes tests indicate memory leak:
```
Error:  Failures: 
3419Error:  org.apache.drill.exec.server.TestDrillbitResilience.cancelInMiddleOfFetchingResults
3420Error:    Run 1: TestDrillbitResilience.cancelInMiddleOfFetchingResults:375 We are leaking 3000000 bytes ==> expected: <0> but was: <3000000>
```
But actually there is no memory leak. Looks like Drill just check actual memory to early, when not all fragments are closed, so adding timeout before final countAllocatedMemory fixes the issue.
The other reason of test failures - the queries were not in expected state before cancelling (for instance in STARTING state …
> DRILL-8030: Intermittent TestDrillbitResilience cancelInMiddleOfFetchingResults and foreman_runTryEnd failures

- contrib/format-excel/pom.xml
- contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
upgrade to poi 5.2.0
No changes
existing unit tests
> DRILL-8095: upgrade to poi 5.2.0

- .github/workflows/ci.yml
- .travis.yml
- contrib/storage-jdbc/pom.xml
- contrib/storage-phoenix/pom.xml
Based on the OWASP dependency check report and dependabot.
N/A
Existing tests.
> DRILL-7994: Dependency version updates for severe vulnerabilities

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/file/ImplicitColumnMarker.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/file/ImplicitColumnResolver.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/OutputBatchBuilder.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/AbstractSchemaTracker.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/MutableTupleSchema.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/validate/IteratorValidatorBatchIterator.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorContainer.java
Fixes case in which the projection order of implicit columns changes across readers.
N/A
Found and tested in unit tests for the Text Format reader. That work will appear in a later PR.
> DRILL-8124: Fix implicit column issue with EVF 2

- contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
The SAS reader uses the first row of data to infer the data types.  If the first row has null values, the SAS reader was throwing a NPE.  This PR fixes that.
Manually tested using customer proprietary data.
> DRILL-8142: SAS Reader Returns NPE

- contrib/format-excel/pom.xml
https://logging.apache.org/log4j/2.x/changes-report.html
CI build
> [DRILL-8150] log4j 2.17.2

- contrib/format-excel/pom.xml
> DRILL-8154: Upgrade to poi 5.2.1

- exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileBatchReader.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileFormatPlugin.java
Second refactor of the SequenceFile format.
N/A
Use the CI.
> DRILL-8171: Convert SequenceFile to EVF2

- .github/workflows/codeql-analysis.yml
[MINOR UPDATE] Add license to CodeQL YAML
Fixing the failure of the `checkstyle and generate protobufs` on the CI.
N/A
Use the CI.
> [MINOR UPDATE] Add license to CodeQL YAML

- exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassCompilerSelector.java
> [MINOR UPDATE] Fix the word spelling error

- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
> [DRILL-8176]upgrade jackson due to cve

- pom.xml
See notes in https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13#micro-patches
> DRILL-8176: minor issue in previous jackson bom

- pom.xml
See Calcite ticket for details
NA
Checked manually
> DRILL-8187: Dialect factory returns ANSI SQL dialect for BigQuery

- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/DynamicSchemaFilter.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroBatchReader.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroFormatPlugin.java
Second refactor of the Avro format.
N/A
Use the CI.
> DRILL-8174: Convert Avro format to EVF2

- exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillConvertletTable.java
See Jira ticket description for details
NA
Unit test pass on newer Calcite
> DRILL-8210: Add substring convertlet

- contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
... in order to fix the Travis CI.
> [MINOR UPDATE] Disable TestJdbcPluginWithMSSQL when not on amd64.

- .github/workflows/codeql-analysis.yml
Update to CodeQL v2 as v1 will be deprecated.
N/A
Ran unit tests
> [MINOR-UPDATE]: Update CodeQL to v2

- exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
Add Drillbit http port in log file, for find the port number easily.
> [Minor Update] Add port number in log file for maintenance convenience

- contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
- contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticComplexTypesTest.java
- contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticInfoSchemaTest.java
- contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchPlanTest.java
- contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
- pom.xml
> DRILL-8255: Update Drill-Calcite version to include fix for CALCITE-4992

- pom.xml
https://issues.apache.org/jira/browse/DRILL-8264
> DRILL-8264: upgrade joda-time

- contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestTableGenerator.java
- contrib/udfs/src/main/java/org/apache/drill/exec/udfs/NetworkFunctions.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/HashTableTemplate.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/RecordBatchSizer.java
- exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorInitializer.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableColumnReader.java
- exec/java-exec/src/main/java/org/apache/drill/exec/util/filereader/BufferedDirectBufInputStream.java
- exec/java-exec/src/test/java/org/apache/drill/exec/DrillSeparatePlanningTest.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestWriter.java
- exec/java-exec/src/test/java/org/apache/drill/test/ProfileParser.java
> DRILL-8266: number narrowing issues

- .github/workflows/ci.yml
- contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
- contrib/format-maprdb/pom.xml
- contrib/storage-hbase/pom.xml
- contrib/storage-hive/core/pom.xml
- contrib/storage-phoenix/pom.xml
- distribution/pom.xml
- docs/dev/Release.md
- exec/java-exec/pom.xml
- exec/java-exec/src/main/codegen/templates/AbstractRecordWriter.java
- exec/java-exec/src/main/codegen/templates/EventBasedRecordWriter.java
- exec/java-exec/src/main/codegen/templates/ParquetOutputRecordWriter.java
- exec/java-exec/src/main/codegen/templates/RecordWriter.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileBatchReader.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
- exec/java-exec/src/main/resources/drill-module.conf
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
- exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestTupleProjection.java
- exec/jdbc-all/pom.xml
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/DictColumnMetadata.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MapColumnMetadata.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/RepeatedListColumnMetadata.java
- exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantColumnMetadata.java
- pom.xml
- tools/release-scripts/release.sh
Merged serveral backport-to-stable commits to new bugfix release 1.20.2, which includes:
* https://github.com/apache/drill/pull/2610
* https://github.com/apache/drill/pull/2613
* https://github.com/apache/drill/pull/2615
N/A
UT
> [BACKPORT-TO-STABLE] Bugfix Release 1.20.2 Phase 3

- exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilter.java
- exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchema.java
[DRILL-8057](https://issues.apache.org/jira/browse/DRILL-8057) brought in a regression whereby info schema LIKE patterns containing an escape character are not correctly processed. For example if a storage plugin called dfs_foo (note the presence of the special '_') is present then the following query wrongly returns no records.
```
apache drill> show databases where schema_name like 'dfs^_foo.%' escape '^';
No rows selected (2.305 seconds)
```
This PR makes schema path prefix comparison use RegexpUtil.SqlPatternInfo#getSimplePatternString when comparing prefixes so that escape characters are correctly processed.
In a misguided burst of zeal, TestInfoSchema was upgraded to a ClusterTest in the process.
N/A
TestInfoSchema#likePatternWithEscapeChar
> DRILL-8281: Info schema LIKE with ESCAPE push down bug

- pom.xml
> DRILL-8300: Upgrade to snakeyaml 1.31 due to cve

- contrib/storage-cassandra/pom.xml
- exec/java-exec/src/main/java/org/apache/drill/exec/compile/JaninoClassCompiler.java
- pom.xml
> DRILL-8304: Update Calcite to 1.32.0

- common/src/main/java/org/apache/drill/common/config/DrillProperties.java
- contrib/storage-kudu/src/main/java/org/apache/drill/exec/store/kudu/KuduGroupScan.java
- exec/java-exec/src/main/java/org/apache/drill/exec/expr/ClassGenerator.java
- exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionGenerationHelper.java
- exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinBatch.java
- exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/MergeJoinBatch.java
- exec/java-exec/src/main/java/org/apache/drill/exec/planner/index/generators/AbstractIndexPlanGenerator.java
- exec/java-exec/src/main/java/org/apache/drill/exec/schema/ListSchema.java
- exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
- exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/OperatorWrapper.java
- exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableColumnReader.java
- exec/java-exec/src/main/java/org/apache/drill/exec/util/filereader/BufferedDirectBufInputStream.java
Some issues listed on https://lgtm.com/projects/g/apache/drill/?mode=list
> [MINOR-UPDATE] fix some issues highlighted in lgtm.com

- pom.xml
Another snakeyaml release and looks like another security issue
> DRILL-8300: Upgrade snakeyaml to 1.32

- contrib/format-excel/pom.xml
- pom.xml
Upgrade POI libs and related libs
> DRILL-8308: Upgrade POI to 5.2.3

- contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogBatchReader.java
- contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogFormatPlugin.java
This PR converts the Syslog format reader to use EVF V2.  
> DRILL-8310: Convert Syslog Format to EVF V2

- contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssBatchReader.java
- contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssFormatPlugin.java
This PR converts the SPSS format plugin to use EVF V2.
> DRILL-8311: Convert SPSS Format Plugin to EVF V2

- pom.xml
recent snakeyaml changes need extra fixes
> DRILL-8326: Bump Snakeyaml To 1.33

- contrib/format-hdf5/README.md
> MINOR UPDATE: HDF5 README lists 4 conf. vars. while it says 3.

- pom.xml
2 CVE fixes in this jackson release
> DRILL-8332: upgrade to jackson 2.13.4.20221012

- pom.xml
upgrade jackson due to issue in gradle module of previous release
> DRILL-8332: upgrade jackson due to issue in gradle module

- contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/PcapBatchReader.java
- contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/BasePcapFormatPlugin.java
- contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngBatchReader.java
Convert the PCAP format plugin to EVF2
> DRILL-8350: Convert PCAP Format Plugin to EVF2

- contrib/format-excel/pom.xml
A couple of small bugs fixed. Ones that may not actually affect Drill usage but still tidier to upgrade.
> DRILL-8362: bump excel-streaming-reader to v4.0.5

- exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetReaderUtility.java
- pom.xml
Update checkstyle version to the latest one
NA
> DRILL-8396: Update checkstyle version

- NOTICE
- distribution/src/main/resources/NOTICE
> [MINOR UPDATE]: Update year in copyright

- docs/dev/ClusterFixture.md
Update /docs base on the discussion in https://github.com/apache/drill/pull/2756
This is a doc update
N/A
> [MINOR UPDATE]: /docs update for DRILL-8117

- pom.xml
see #2590 for initial improvements
check of release 1.21.0 shows that there are still a few issues https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/drill/README.md
> DRILL-8158: Fix 2 Reproducible Builds issues Remaining After DRILL-8158

- contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateFunctions.java
Fixes a minor bug in the `nearest_date` UDF which prevented it from working at all. 
N/A
> [MINOR UPDATE]: Fix Code Gen Error in Nearest Date UDF

- exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemPlugin.java
This PR enables Drill to query files stored in SFTP file systems.
An SFTP file system behaves exactly as any other file system. 
To query data from an SFTP file system, follow the instructions for any other file system.  For the URL, provide the host as shown below:
```json
{
"type": "file",
"connection": "sftp://<your sftp server URL>",
"workspaces": {
"test": {
"location": "<path to test data>",
"writable": true,
"defaultInputFormat": null,
"allowAccessOutsideWorkspace": false
},
...
```
The SFTP plugin requires a username and password to authenticate.  The best way to do this is to provide the information via a `credentialProvider` as shown below.   SFTP file systems can be used with `USER_TRANSLATION` enabled, but not `USER_IMPERSONATION`.  
```json
"credentialsProvider": { …
```
> DRILL-8407: Add Support for SFTP File Systems

- contrib/format-excel/pom.xml
- pom.xml
> DRILL-8456: upgrade poi and commons-compress

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-snapshot.yml
[DRILL-8464](https://issues.apache.org/jira/browse/DRILL-8464)
> DRILL-8464. Upgrade to checkout action v4

- exec/java-exec/pom.xml
- exec/jdbc-all/pom.xml
- pom.xml
https://issues.apache.org/jira/browse/DRILL-8463
> DRILL-8463. Bouncy Castle 1.77

- pom.xml
https://issues.apache.org/jira/browse/DRILL-8466
> DRILL-8466. upgrade to logback 1.3.13

- pom.xml
https://issues.apache.org/jira/browse/DRILL-8466
An extra set of changes were made to improve on the original logback CVE fix
> DRILL-8466. upgrade to logback 1.3.14

- pom.xml
see https://issues.apache.org/jira/browse/HADOOP-19154 for details
> [MINOR UPDATE] update bouncycastle to 1.78.1 due to CVEs

- exec/memory/base/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java
- pom.xml
CVE-2024-29025
Update to latest versions regardless
> [MINOR UPDATE] update to netty 4.1.109 due to CVE-2024-29025

- distribution/src/main/resources/licenses/MISSING.properties
Update MISSING.properties with new Splunk SDK version.
N/A
> [MINOR UPDATE] Update MISSING.properties for Splunk SDK

- contrib/storage-druid/README.md
- contrib/storage-druid/src/test/resources/druid/docker-compose.yaml
- distribution/docker-compose/README.txt
- distribution/docker-compose/docker-compose.yml
* see https://github.com/orgs/community/discussions/116610
* version param is obsolete, see https://docs.docker.com/compose/compose-file/04-version-and-name/
> [MINOR UPDATE] Update Docker-Compose Docs

- pom.xml
> [MINOR UPDATE] upgrade to netty 4.1.115 (from 4.1.109) due due CVE-2024-47535

- pom.xml
> [MINOR UPDATE] upgrade logback due to CVE fixes

- NOTICE
- distribution/src/main/resources/NOTICE
Keeping the copyright years up to date
> [MINOR UPDATE] add 2025 to copyright

- pom.xml
Update the MongoDB client to version 5.5.1.
Ran unit tests.
> [MINOR UPDATE] Update Mongo Client
